wk_taa_taaqa/src/objects/AccountAutomationSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>IsTriggerOff__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Trigger Off</label>
        <type>Checkbox</type>
    </fields>
    <label>AccountAutomationSetting</label>
</CustomObject>

wk_taa_taaqa/src/objects/Monitoring_Log__c.object
<CustomObject>
    <description>This object is used to log informational and error messages - Currently for the Account Team Automation solution - ATA</description>
    <fields>
        <fullName>Apex_Job_ID__c</fullName>
        <description>Id of the batch job</description>
        <label>Apex Job ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Batch Job Result</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Monitoring Log</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monitoring Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/TAACustomSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>TAA Hierarchical custom setting</description>
    <label>TAA CustomSetting</label>
</CustomObject>

wk_taa_taaqa/src/objects/ZipCodeDTN__c.object
<CustomObject>
    <fields>
        <fullName>IsUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if this record is updated.</inlineHelpText>
        <label>IsUpdated</label>
        <type>Checkbox</type>
    </fields>
    <label>Zip Code DTN</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes DTN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/MassUpdateAccountBatch.cls
global class MassUpdateAccountBatch implements Database.Batchable<sObject> {
    public String query = null;
   // public TAACustomSetting__c taaCusSet =UtilCustomSettings.TAACustomSetting();
    public AccountAutomationSetting__c taaCusSet =UtilCustomSettings.TAACustomSetting();
    /*public String header = 'Account Name, Account Id \r\n';
    public String finalStr = header;
    public String recordStr;*/
    global Database.queryLocator start(Database.BatchableContext bc){
        set<String> setDirtyZipcodeDTN= new set<String>();
        for(ZipCodeDTN__c z : [Select Name from ZipCodeDTN__c where IsUpdated__c=true]){
            setDirtyZipcodeDTN.add(z.Name);
        }
        List<String>dirtyZipcodeDTNList= new List<String>();
        for (String s:setDirtyZipcodeDTN){
            dirtyZipcodeDTNList.add(s+'%');
        }
        System.debug('Size Of updated dirtyZipcodeDTNList'+dirtyZipcodeDTNList.size());
        if (dirtyZipcodeDTNList.size()>0)
            query=QueryServiceClass.massUpdateAccountStr+' ' +'OR BillingPostalCode Like : dirtyZipcodeDTNList)';
         else
            query= QueryServiceClass.massUpdateAccountStr +')';
            System.debug('Query for Batch>>>>>>>>>>>>>'+query);
        //query = QueryServiceClass.massUpdateAccountStr+' '+'OR BillingPostalCode in :setDirtyZipcodeDTN)';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext bc, List<sObject>scope){
         AsyncApexJob  job= [Select Id, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email from AsyncApexJob where Id =:bc.getJobId()];  
        //Set trigger off to run before starting batch process on Accounts update
        /*if(taaCusSet.IsTriggerOff__c ==false){
            taaCusSet.IsTriggerOff__c =true;
            update taaCusSet;
        }*/
        List<Account> updateAbleAccounts = (List<Account>)scope;
        /*for(Account a : updateAbleAccounts){
          recordStr += '"'+a.Name+'","'+a.Id+'"\r\n';
        }*/
        MassUpdateAccountBatchController controller = new MassUpdateAccountBatchController();
        controller.updateDTNAndSegmentAndSubsegment(updateAbleAccounts,job.id);
    }
    global void finish(Database.BatchableContext bc){
        //Set trigger on to run after batch process on Accounts update finished
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,ExtendedStatus,
         TotalJobItems, CreatedBy.Email
         FROM AsyncApexJob WHERE Id =
                :BC.getJobId()];
   
        Monitoring_Log__c m = LoggerUtil.createErrorRecord('MassUpdateAccountBatch','MassUpdateAccountBatchController','finish',
         'The batch Apex job processed ' + a.TotalJobItems +
               ' batches with '+ a.NumberOfErrors + ' failures.' +'\n' + a.ExtendedStatus);
        m.Apex_Job_ID__c= a.Id; 
        m.Type__c='ATA_MassUpdateAccountBatch';       
        insert m;
         //finalStr +=recordStr;
         //MassUpdateAccountBatchController.attachFileToMonitoringLog(finalStr, m.Id);
         
             
    }

}