wk_taa_taaqa/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Has_ATX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has ATX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Axcess_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Axcess Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Axcess_Practice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Axcess Practice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Axcess_Tax__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Axcess Tax SaaS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Axcess_Workstream__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Axcess Workstream</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_CCH_Expert_Treatises__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has CCH Expert Treatises</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_CORPC_MTG_PTP_3_Full_or_5_Lite_Stat__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has CORPC: MTG + PTP + 3 Full or 5 Lite</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_CORPP_MTG_TRC_50_States_Lite_Forms__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has CORPP: MTG+ TRC + 50 StatesLiteForms</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_ClientRelate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has ClientRelate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Compliance_Services__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Compliance Services</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Document_ASP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Document ASP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Document_On_Premise__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Document On Premise</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Engagement__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Engagement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Fixed_Assets__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Fixed Assets</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_GFX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has GFX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_IC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has IC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_IntelliForms__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has IntelliForms</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_International_Tax__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has International Tax</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Journals__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Journals</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Knowledge_Coach__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Knowledge Coach</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Knowledge_Tools__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Knowledge Tools</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Learning_and_Seminars__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Learning and Seminars</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Load_Utilities__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Load Utilities</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Open_Integrator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Open Integrator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Outsource__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Outsource</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_PDFlyer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has PDFlyer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_PROP1_PTP_Core_TPP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has PROP1: PTP &amp; Core TPP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_PROT3_TRC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has PROT3: TRC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Practice_Management__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Practice Management</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Practice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Practice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Sales_Tax_Office__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Sales Tax Office</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Tax__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has PFX Tax</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Trial_Balance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Trial Balance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting Firms</fullName>
                </value>
                <value>
                    <fullName>Banks and Financial Institutions</fullName>
                </value>
                <value>
                    <fullName>Consultants</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Financial and Estate Planners</fullName>
                </value>
                <value>
                    <fullName>General Corporate</fullName>
                </value>
                <value>
                    <fullName>Hospital and Payers</fullName>
                </value>
                <value>
                    <fullName>Insurance Companies</fullName>
                </value>
                <value>
                    <fullName>Legal Professionals</fullName>
                </value>
                <value>
                    <fullName>Retail Tax Preparers</fullName>
                </value>
                <value>
                    <fullName>Schools and Libraries</fullName>
                </value>
                <value>
                    <fullName>State and Local Government</fullName>
                </value>
                <value>
                    <fullName>Tax Exempt and Membership Organizations</fullName>
                </value>
                <value>
                    <fullName>Agriculture &amp; Mining</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Banks and Financial</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Business Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Computers &amp; Electronics</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Consumer Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Education</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Fin</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Financial Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Government</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Healthcare, Pharmaceuticals, &amp; Biotech</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Hospital &amp; Payers</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Law Schools</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Legal Professional</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Media &amp; Entertainment</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Sub_Segment__c</fullName>
        <label>SubSegment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market_Segment__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sole Proprietor</fullName>
                </value>
                <value>
                    <fullName>2-4 Total Employees</fullName>
                </value>
                <value>
                    <fullName>5-9 Total Employees</fullName>
                </value>
                <value>
                    <fullName>10-19 Total Employees</fullName>
                </value>
                <value>
                    <fullName>20-49 Total Employees</fullName>
                </value>
                <value>
                    <fullName>50-99 Total Employees</fullName>
                </value>
                <value>
                    <fullName>100+ Total Employees</fullName>
                </value>
                <value>
                    <fullName>Top 100 Firms</fullName>
                </value>
                <value>
                    <fullName>Global Enterprise</fullName>
                </value>
                <value>
                    <fullName>Large Enterprise</fullName>
                </value>
                <value>
                    <fullName>Mid Enterprise</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                </value>
                <value>
                    <fullName>Small</fullName>
                </value>
                <value>
                    <fullName>Dept of Agriculture</fullName>
                </value>
                <value>
                    <fullName>Dept of Commerce</fullName>
                </value>
                <value>
                    <fullName>Dept of Defense</fullName>
                </value>
                <value>
                    <fullName>Dept of Energy</fullName>
                </value>
                <value>
                    <fullName>Dept of Health and Human Services</fullName>
                </value>
                <value>
                    <fullName>Dept of Homeland Security</fullName>
                </value>
                <value>
                    <fullName>Dept of Housing and Urban Development</fullName>
                </value>
                <value>
                    <fullName>Dept of Interior</fullName>
                </value>
                <value>
                    <fullName>Dept of Justice</fullName>
                </value>
                <value>
                    <fullName>Dept of Labor</fullName>
                </value>
                <value>
                    <fullName>Dept of State</fullName>
                </value>
                <value>
                    <fullName>Dept of Treasury (not IRS)</fullName>
                </value>
                <value>
                    <fullName>Dept of Vet Affairs</fullName>
                </value>
                <value>
                    <fullName>EEOC</fullName>
                </value>
                <value>
                    <fullName>Exec Branch (White House)</fullName>
                </value>
                <value>
                    <fullName>FCC</fullName>
                </value>
                <value>
                    <fullName>FDIC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/AccountScoring__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>CustomerPoints__c</fullName>
        <label>CustomerPoints</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CustomerSegmentation__c</fullName>
        <label>CustomerSegmentation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberOfReturns__c</fullName>
        <label>NumberOfReturns</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Count__c</fullName>
        <label>Product Count</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProspectPoints__c</fullName>
        <label>ProspectPoints</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subsegment__c</fullName>
        <label>Subsegment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AccountScoring</label>
</CustomObject>

wk_taa_taaqa/src/classes/TestAccountScoring.cls
@istest
public class TestAccountScoring {
    static testMethod void AccountScoringTest(){
    
    
    AccountScoring__c CP = new AccountScoring__c();
        CP.Name = '2-4 Total Employees';
        CP.Subsegment__c = '2-4 Total Employees';
        CP.CustomerPoints__c = 43.0;
        CP.ProspectPoints__c = 43.0;
        Insert CP;
        
        AccountScoring__c CP1 = new AccountScoring__c();
        CP1.Name = '1 Product';
        CP1.Product_Count__c = '1 Product';
        CP1.CustomerPoints__c = 1.0;
        Insert CP1;
        
        AccountScoring__c CP2 = new AccountScoring__c();
        CP2.Name = '0-500 Returns';
        CP2.NumberOfreturns__c = '0-500 Returns';
        CP2.CustomerPoints__c = 1.0;
        Insert CP2;
        
        AccountScoring__c CP3 = new AccountScoring__c();
        CP3.Name = 'Advanced';
        CP3.CustomerSegmentation__c = 'Advanced';
        CP3.CustomerPoints__c = 1.0;
        CP3.ProspectPoints__c = 1.0;
        Insert CP3;






Account A = new Account(
            Name = 'myAcct', 
            BillingStreet='25 Upland Drive',
            BillingPostalCode='94127',
            BillingCountry='United States',
            BillingCity='San Francisco', 
            market_segment__c = 'Accounting Firms', 
            market_sub_segment__c = '2-4 Total Employees',
            has_axcess_tax__c = True,
            has_Axcess_Practice__c = True,
            has_Axcess_Document__c = true,
            has_Axcess_Workstream__c = true,
            has_document__c = True,
            has_engagement__c = true,
            has_trial_balance__c = true,
            has_fixed_assets__c = true,
            has_clientrelate__c = true,
            has_document_asp__c = true,
            has_tax__c = true,
            has_practice__c = true,
            has_practice_management__c = true,
            has_pdflyer__c = true,
            has_atx__c = true,
            Has_Compliance_Services__c  = true,
            Has_CORPC_MTG_PTP_3_Full_or_5_Lite_Stat__c  = true,
            Has_CORPP_MTG_TRC_50_States_Lite_Forms__c = true,
            Has_CCH_Expert_Treatises__c = true,
            Has_Document_On_Premise__c = true,
            Has_GFX__c = true,
            Has_IC__c = true,
            Has_Knowledge_Coach__c = true,
            Has_Knowledge_Tools__c = true,
            Has_Learning_and_Seminars__c = true,
            Has_Load_Utilities__c = true,
            Has_Open_Integrator__c = true,
            Has_Outsource__c = true,
            Has_International_Tax__c = true,
            Has_IntelliForms__c = true,
            Has_Journals__c = true,
            Has_Sales_Tax_Office__c = true,
            Has_PROT3_TRC__c  = true,
            Has_PROP1_PTP_Core_TPP__c = true,
            Has_Practice_Manager__c = true,
            Has_POS_Tax_Portal__c = true,
            Has_Portal_SaaS__c  = true,
            Has_Scan_SaaS__C = true,
            Has_SFS_Research__c = true,
            Has_Specialty_Planning__c = true,
            Has_State_Tax_Reporters__c = true,
            Has_Taxwise__c = true,
            Has_Tax_Prep_Partner__c = true,
            Has_SureTax__c = true,
            Has_Utility_DB_Lokup_RADAR_Flag__c = true,
            Has_Telecom_DB_Lookup_RADAR_Flag__c = true,
            Has_TAX2A_TRC_FED_Fed_TPP_1_State_Enti__c = true,
            Has_TAX1_TRC_FED_Federal_TPP_1_State__c = true,
            RecordTypeId = '012i0000000Ou0CAAS',
            YTD_TRNMT_RET_c__c = 250,
            customer_segmentation__c = 'Advanced' );
        insert A;
        
        Account A2 = new Account(
            Name = 'myAcct', 
            BillingStreet='25 Upland Drive',
            BillingPostalCode='94127',
            BillingCountry='United States',
            BillingCity='San Francisco', 
            market_segment__c = 'Accounting Firms', 
            market_sub_segment__c = '2-4 Total Employees',
            RecordTypeId = '012i0000000Ou0EAAS',
            customer_segmentation__c = 'Advanced' );
        insert A2;

        
                  
}
}