wk_taa_taaqa/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market_Sub_Segment__c</fullName>
        <label>SubSegment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market_Segment__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sole Proprietor</fullName>
                </value>
                <value>
                    <fullName>2-4 Total Employees</fullName>
                </value>
                <value>
                    <fullName>5-9 Total Employees</fullName>
                </value>
                <value>
                    <fullName>10-19 Total Employees</fullName>
                </value>
                <value>
                    <fullName>20-49 Total Employees</fullName>
                </value>
                <value>
                    <fullName>50-99 Total Employees</fullName>
                </value>
                <value>
                    <fullName>100+ Total Employees</fullName>
                </value>
                <value>
                    <fullName>Top 100 Firms</fullName>
                </value>
                <value>
                    <fullName>Global Enterprise</fullName>
                </value>
                <value>
                    <fullName>Large Enterprise</fullName>
                </value>
                <value>
                    <fullName>Mid Enterprise</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                </value>
                <value>
                    <fullName>Small</fullName>
                </value>
                <value>
                    <fullName>Dept of Agriculture</fullName>
                </value>
                <value>
                    <fullName>Dept of Commerce</fullName>
                </value>
                <value>
                    <fullName>Dept of Defense</fullName>
                </value>
                <value>
                    <fullName>Dept of Energy</fullName>
                </value>
                <value>
                    <fullName>Dept of Health and Human Services</fullName>
                </value>
                <value>
                    <fullName>Dept of Homeland Security</fullName>
                </value>
                <value>
                    <fullName>Dept of Housing and Urban Development</fullName>
                </value>
                <value>
                    <fullName>Dept of Interior</fullName>
                </value>
                <value>
                    <fullName>Dept of Justice</fullName>
                </value>
                <value>
                    <fullName>Dept of Labor</fullName>
                </value>
                <value>
                    <fullName>Dept of State</fullName>
                </value>
                <value>
                    <fullName>Dept of Treasury (not IRS)</fullName>
                </value>
                <value>
                    <fullName>Dept of Vet Affairs</fullName>
                </value>
                <value>
                    <fullName>EEOC</fullName>
                </value>
                <value>
                    <fullName>Exec Branch (White House)</fullName>
                </value>
                <value>
                    <fullName>FCC</fullName>
                </value>
                <value>
                    <fullName>FDIC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NAM_SAM_CNAM__c</fullName>
        <label>NAM/SAM/CNAM DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Named_Account_Type__c</fullName>
        <label>Named Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Small Firm Customer</fullName>
                </value>
                <value>
                    <fullName>Small Firm Key Account</fullName>
                </value>
                <value>
                    <fullName>Refunds Today</fullName>
                </value>
                <value>
                    <fullName>Small Firm Premier</fullName>
                </value>
                <value>
                    <fullName>MainStreet</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Small Firm Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>Small Firm Field</fullName>
                </value>
                <value>
                    <fullName>Small Firm Tax Customer</fullName>
                </value>
                <value>
                    <fullName>R&amp;L Key Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Named_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Named Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pro_SW_FSR__c</fullName>
        <label>Pro SW RSC DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QP__c</fullName>
        <label>QP DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_ASR__c</fullName>
        <label>R&amp;L RC DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_FSR__c</fullName>
        <label>R&amp;L RSC DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SW_ASR__c</fullName>
        <label>SW RC DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Source__c</fullName>
        <label>Service Source DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Account_X_Reference__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account X-Reference</relationshipLabel>
        <relationshipName>Account_X_Reference</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ApplicationID__c</fullName>
        <externalId>true</externalId>
        <label>Application ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS</fullName>
                </value>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>SFS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bill_To_Account_Name__c</fullName>
        <label>Bill To Account Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_City__c</fullName>
        <label>Bill To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Contact_Name__c</fullName>
        <label>Bill To Contact Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Country__c</fullName>
        <label>Bill To Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Fax__c</fullName>
        <label>Bill_To_Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Bill_To_Partner_Number__c</fullName>
        <label>Bill_To_Partner_Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Phone__c</fullName>
        <label>Bill_To_Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Bill_To_State__c</fullName>
        <label>Bill To State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Street_Line_1__c</fullName>
        <label>Bill To Street Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Street_Line_2__c</fullName>
        <label>Bill To Street Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Zip_Postal_Code__c</fullName>
        <label>Bill To Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Building_Number__c</fullName>
        <description>SAP Sold To Building Number</description>
        <label>Building Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Account_Name__c</fullName>
        <label>ERP Account Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsNotValid__c</fullName>
        <defaultValue>false</defaultValue>
        <description>record modified today but not eligible in batch process to update account</description>
        <label>IsNotValid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Named_Account_Type__c</fullName>
        <formula>text( Account__r.Named_Account_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Named Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Named_Account__c</fullName>
        <formula>Account__r.Named_Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Named Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>PostalCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Account_Name__c</fullName>
        <label>Ship To Account Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_City__c</fullName>
        <label>Ship To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Contact_Name__c</fullName>
        <label>Ship To Contact Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Country__c</fullName>
        <label>Ship To Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Fax__c</fullName>
        <label>Ship_To_Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ship_To_Partner_Number__c</fullName>
        <label>Ship_To_Partner_Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Phone__c</fullName>
        <label>Ship_To_Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ship_To_State__c</fullName>
        <label>Ship To State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Street_Line_1__c</fullName>
        <label>Ship To Street Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Street_Line_2__c</fullName>
        <label>Ship To Street Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Zip_Postal_Code__c</fullName>
        <label>Ship To Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street_Address</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Account X-Reference</label>
    <nameField>
        <label>Account X-Reference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account X-Reference</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/QueryServiceClass.cls
/**
@Author: HCL Technologies Pvt Ltd.
@Description: QueryServiceClass class will contain the strings which will be called this org wise.
*/
public with sharing class QueryServiceClass {
    /*
    @Variable: updateAccountAddressStr is String varible.
    @           It is used in UpdateAccountAddressBatchScheduler to query the data for start 
    @           method of UpdateAccountAddressBatch.
    */
    public static String updateAccountAddressStr = 'Select Street_Address__c, State__c, Ship_To_Zip_Postal_Code__c, Ship_To_Street_Line_2__c,'+
                                                    'Ship_To_Street_Line_1__c, Ship_To_State__c, Ship_To_Phone__c, Ship_To_Partner_Number__c,'+ 
                                                    'Ship_To_Fax__c, Ship_To_Country__c, Ship_To_Contact_Name__c, Ship_To_City__c,'+ 'IsNotValid__c,'+
                                                    'Ship_To_Account_Name__c, PostalCode__c, Phone__c, Email__c, ERP_Account_Name__c,'+ 
                                                    'Country__c, City__c, Building_Number__c, Bill_To_Zip_Postal_Code__c, Bill_To_Street_Line_2__c,'+ 
                                                    'Bill_To_Street_Line_1__c, Bill_To_State__c, Bill_To_Phone__c, Bill_To_Partner_Number__c,'+ 
                                                    'Bill_To_Fax__c, Bill_To_Country__c, Bill_To_Contact_Name__c, Bill_To_City__c, Bill_To_Account_Name__c,'+ 
                                                    'Application__c, ApplicationID__c, Account__c,Account__r.RecordTypeId'+
                                                    ' '+ 
                                                    'From Account_X_Reference__c'+
                                                    ' '+
                                                    'where LastModifiedDate=TODAY';
    /*
    @Variable: massUpdateAccountStr is String varible.
    @           It is used in MassUpdateAccountBatchScheduler to query the data for start 
    @           method of MassUpdateAccountBatch.
    */
    public static String massUpdateAccountStr = 'Select '+
                                                'Name,'+
                                                'BillingPostalCode,'+
                                                'Sic,'+ 
                                                'Service_Source__c,'+ 
                                                'SW_ASR__c,'+
                                                'R_L_FSR__c,'+
                                                'R_L_ASR__c,'+ 
                                                'QP__c,'+ 
                                                'Pro_SW_FSR__c,'+ 
                                                'Named_Account__c,'+ 
                                                'Named_Account_Type__c,'+ 
                                                'NAM_SAM_CNAM__c,'+ 
                                                'Market_Sub_Segment__c,'+ 
                                                'Market_Segment__c,'+ 
                                                'IsMassUpdated__c,'+ 
                                                'Inside_Sales__c,'+ 
                                                'Id,'+ 
                                                'DTN_Makeup__c,'+ 
                                                'Corp_Indirect__c,'+ 
                                                'Corp_Direct__c,'+ 
                                                'ARM_National_Account__c,'+ 
                                                'AISR__c,'+
                                                'RecordTypeId,'+
                                                'Inactive__c,'+
                                                'Exclude_Account_Automation__c,'+
                                                'ISR_Indirect__c'+
                                                ' '+
                                                'From Account'+
                                                ' '+
                                                'Where Exclude_Account_Automation__c=false and '+
                                                '(IsMassUpdated__c=true';
    
    /*
    @   Variable: queryToFindAffectedAccounts is String varible.
    @   It is used in ATA_AccountTeamUpdateBatch to query the data for start 
    */
    public static String queryToFindAffectedAccounts = 'SELECT '+
			                                                'Id,'+
			                                                'Name,'+
			                                                'BillingPostalCode,'+
			                                                'RecordTypeId,'+
			                                                'Exclude_Account_Automation__c'+
			                                                ' '+
			                                                'FROM Account'+
			                                                ' '+
			                                                'WHERE Exclude_Account_Automation__c = false AND IsMassUpdated__c = true';
    
    
    public static String dirtyDTNAccounts(set<String>setDirtyZipcodeDTN){
        return 'Select '+
            'BillingPostalCode,'+
            'Sic,'+ 
            'Service_Source__c,'+ 
            'SW_ASR__c,'+
            'R_L_FSR__c,'+
            'R_L_ASR__c,'+ 
            'QP__c,'+ 
            'Pro_SW_FSR__c,'+ 
            'Named_Account__c,'+ 
            'Named_Account_Type__c,'+ 
            'NAM_SAM_CNAM__c,'+ 
            'Market_Sub_Segment__c,'+ 
            'Market_Segment__c,'+ 
            'IsDirty__c,'+ 
            'Inside_Sales__c,'+ 
            'Id,'+ 
            'DTN_Makeup__c,'+ 
            'Corp_Indirect__c,'+ 
            'Corp_Direct__c,'+ 
            'ARM_National_Account__c,'+ 
            'AISR__c'+
            ' '+
            'From Account'+
            ' '+
            'Where IsDirty__c=true OR'+
            ' '+
            'BillingPostalCode in:'+
            setDirtyZipcodeDTN;
    }
    
     /* Added By Usha*/
     
  
   public static String getAccountXReferenceHistory(String accountXrefDate){ 
     return 'Select '+
                       'parentId,'+
                       'oldvalue,'+
                       'newvalue,'+ 
                       'Isdeleted,'+ 
                       'Id,'+
                       'field,'+
                       'createddate,'+ 
                        'createdbyId'+
                           '  '+ 
                        'From Account_X_Reference__History'+
                         '  '+
                         'where createddate >='+
                         accountXrefDate+' '+'AND Field In ('+'\''+'SHIP_TO_STREET_LINE_1__C'+'\''+','+'\''+'SHIP_TO_STREET_LINE_2__C'+'\''+','+'\''+
                         'SHIP_TO_CITY__C'+'\''+','+'\''+'SHIP_TO_STATE__C'+'\''+','+'\''+'Ship_To_Country__c'+'\''+','+'\''+'STREET_ADDRESS__C'+'\''+','+
                         +'\''+'CITY__C'+'\''+','+'\''+'STATE__C'+'\''+','+'\''+'CITY__C'+'\''+','+'\''+'SHIP_TO_ZIP_POSTAL_CODE__C'+'\''+','+'\''+'POSTALCODE__C'+'\''+','+'\''+'Country__c' +'\''+','+'\''+'Created'+'\''+')';
      }
      
      public static String getAccountXReferenceHistoryCount(String accountXrefDate){ 
     return 'Select '+
                       'Count()'+
                       
                        'From Account_X_Reference__History'+
                         '  '+
                         'where createddate >='+
                         accountXrefDate+' '+'AND Field In ('+'\''+'SHIP_TO_STREET_LINE_1__C'+'\''+','+'\''+'SHIP_TO_STREET_LINE_2__C'+'\''+','+'\''+
                         'SHIP_TO_CITY__C'+'\''+','+'\''+'SHIP_TO_STATE__C'+'\''+','+'\''+'Ship_To_Country__c'+'\''+','+'\''+'STREET_ADDRESS__C'+'\''+','+
                         +'\''+'CITY__C'+'\''+','+'\''+'STATE__C'+'\''+','+'\''+'CITY__C'+'\''+','+'\''+'SHIP_TO_ZIP_POSTAL_CODE__C'+'\''+','+'\''+'POSTALCODE__C'+'\''+','+'\''+'Country__c' +'\''+','+'\''+'Created'+'\''+')'+'limit 40000';
      }

    public static String getReplicationMonitorLogQuery(){
        return 'SELECT Id, ObjectID__c, PartnerNetworkRecord_StartDate__c FROM ReplicationMonitoringLog__c WHERE PartnerNetworkRecord_StartDate__c = NULL';
    }
}