wk_taa_taaqa/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting Firms</fullName>
                </value>
                <value>
                    <fullName>Banks and Financial Institutions</fullName>
                </value>
                <value>
                    <fullName>Consultants</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Financial and Estate Planners</fullName>
                </value>
                <value>
                    <fullName>General Corporate</fullName>
                </value>
                <value>
                    <fullName>Hospital and Payers</fullName>
                </value>
                <value>
                    <fullName>Insurance Companies</fullName>
                </value>
                <value>
                    <fullName>Legal Professionals</fullName>
                </value>
                <value>
                    <fullName>Retail Tax Preparers</fullName>
                </value>
                <value>
                    <fullName>Schools and Libraries</fullName>
                </value>
                <value>
                    <fullName>State and Local Government</fullName>
                </value>
                <value>
                    <fullName>Tax Exempt and Membership Organizations</fullName>
                </value>
                <value>
                    <fullName>Agriculture &amp; Mining</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Banks and Financial</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Business Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Computers &amp; Electronics</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Consumer Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Education</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Fin</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Financial Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Government</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Healthcare, Pharmaceuticals, &amp; Biotech</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Hospital &amp; Payers</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Law Schools</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Legal Professional</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Media &amp; Entertainment</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Sub_Segment__c</fullName>
        <label>SubSegment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market_Segment__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sole Proprietor</fullName>
                </value>
                <value>
                    <fullName>2-4 Total Employees</fullName>
                </value>
                <value>
                    <fullName>5-9 Total Employees</fullName>
                </value>
                <value>
                    <fullName>10-19 Total Employees</fullName>
                </value>
                <value>
                    <fullName>20-49 Total Employees</fullName>
                </value>
                <value>
                    <fullName>50-99 Total Employees</fullName>
                </value>
                <value>
                    <fullName>100+ Total Employees</fullName>
                </value>
                <value>
                    <fullName>Top 100 Firms</fullName>
                </value>
                <value>
                    <fullName>Global Enterprise</fullName>
                </value>
                <value>
                    <fullName>Large Enterprise</fullName>
                </value>
                <value>
                    <fullName>Mid Enterprise</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                </value>
                <value>
                    <fullName>Small</fullName>
                </value>
                <value>
                    <fullName>Dept of Agriculture</fullName>
                </value>
                <value>
                    <fullName>Dept of Commerce</fullName>
                </value>
                <value>
                    <fullName>Dept of Defense</fullName>
                </value>
                <value>
                    <fullName>Dept of Energy</fullName>
                </value>
                <value>
                    <fullName>Dept of Health and Human Services</fullName>
                </value>
                <value>
                    <fullName>Dept of Homeland Security</fullName>
                </value>
                <value>
                    <fullName>Dept of Housing and Urban Development</fullName>
                </value>
                <value>
                    <fullName>Dept of Interior</fullName>
                </value>
                <value>
                    <fullName>Dept of Justice</fullName>
                </value>
                <value>
                    <fullName>Dept of Labor</fullName>
                </value>
                <value>
                    <fullName>Dept of State</fullName>
                </value>
                <value>
                    <fullName>Dept of Treasury (not IRS)</fullName>
                </value>
                <value>
                    <fullName>Dept of Vet Affairs</fullName>
                </value>
                <value>
                    <fullName>EEOC</fullName>
                </value>
                <value>
                    <fullName>Exec Branch (White House)</fullName>
                </value>
                <value>
                    <fullName>FCC</fullName>
                </value>
                <value>
                    <fullName>FDIC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Market_Sub_Segment__c</fullName>
        <label>SubSegment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Segment__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sole Proprietor</fullName>
                </value>
                <value>
                    <fullName>2-4 Total Employees</fullName>
                </value>
                <value>
                    <fullName>5-9 Total Employees</fullName>
                </value>
                <value>
                    <fullName>10-19 Total Employees</fullName>
                </value>
                <value>
                    <fullName>20-49 Total Employees</fullName>
                </value>
                <value>
                    <fullName>50-99 Total Employees</fullName>
                </value>
                <value>
                    <fullName>100+ Total Employees</fullName>
                </value>
                <value>
                    <fullName>Top 100 Firms</fullName>
                </value>
                <value>
                    <fullName>Global Enterprise</fullName>
                </value>
                <value>
                    <fullName>Large Enterprise</fullName>
                </value>
                <value>
                    <fullName>Mid Enterprise</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                </value>
                <value>
                    <fullName>Small</fullName>
                </value>
                <value>
                    <fullName>Dept of Agriculture</fullName>
                </value>
                <value>
                    <fullName>Dept of Commerce</fullName>
                </value>
                <value>
                    <fullName>Dept of Defense</fullName>
                </value>
                <value>
                    <fullName>Dept of Energy</fullName>
                </value>
                <value>
                    <fullName>Dept of Health and Human Services</fullName>
                </value>
                <value>
                    <fullName>Dept of Homeland Security</fullName>
                </value>
                <value>
                    <fullName>Dept of Housing and Urban Development</fullName>
                </value>
                <value>
                    <fullName>Dept of Interior</fullName>
                </value>
                <value>
                    <fullName>Dept of Justice</fullName>
                </value>
                <value>
                    <fullName>Dept of Labor</fullName>
                </value>
                <value>
                    <fullName>Dept of State</fullName>
                </value>
                <value>
                    <fullName>Dept of Treasury (not IRS)</fullName>
                </value>
                <value>
                    <fullName>Dept of Vet Affairs</fullName>
                </value>
                <value>
                    <fullName>EEOC</fullName>
                </value>
                <value>
                    <fullName>Exec Branch (White House)</fullName>
                </value>
                <value>
                    <fullName>FCC</fullName>
                </value>
                <value>
                    <fullName>FDIC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact_for_Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact(for Proposal)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Software</fullName>
                </value>
                <value>
                    <fullName>Med/Large Software</fullName>
                </value>
                <value>
                    <fullName>Small Firm Software</fullName>
                </value>
                <value>
                    <fullName>Research &amp; Learning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/S2S_Opp_syncTest.cls
/*
    **************************************************************************
    Name    :   S2S_Opp_syncTest
    
    Used for  :   Test class for S2S_Opp_sync.
    
    Version    |    Name            |    Date           
    1.0             Rajesh Gonola          05-Sep-2017  
    
   
    
    ***************************************************************************
*/
@isTest
public class S2S_Opp_syncTest
{
  static testMethod void postest()
  {
      
        Account a = new Account( Name = 'pfxtest',BillingStreet='25 fake street',BillingPostalCode='30062',Market_Segment__c='Accounting Firms',Market_Sub_Segment__c='Sole Proprietor',BillingCountry='United States',BillingCity='Kennesaw' );
        insert a;
        
       Contact c =new Contact(FirstName='testFName',LastName='testLName', email='emailFormat@gmail.com', AccountId = a.id);
       insert c;
       
       Opportunity Opp = new Opportunity( Name = 'TestOpp',Primary_Contact_for_Proposal__c=c.id,AccountId = a.Id,type = 'New to Existing',Closedate = Date.today().addYears(1),stagename = '6. Closed Won',product_category__c = 'Med/Large Software',Amount = 1.00, product_Sub_Category__c = 'Tax');
        insert Opp;
        
    
        Test.startTest();

            RestResponse res = new RestResponse();
            RestRequest req = new RestRequest(); 

                      
         String Body= '{\"opps\":[{\"Type\":\"New to Existing\",\"TAAPrimaryContact\":\"0030S0000073vfNQAQ\",\"TAAOppRecordId\":\"0030S0000073vfNQAQ\",\"TAAAccountID\":\"0010S000008H6s1QAC\",\"StageName\":\"5. Time to Buy\",\"SFSPrimaryContact\":\"0030j00000BYUaRAAX\",\"SFSPID\":null,\"SFSOppRecordId\":\"0060j000009DssnAAC\",\"SFSCID\":null,\"SFSAccountID\":\"0010j00000BRS8YAAX\",\"quoteNumber\":\"Q-165685\",\"quoteId\":\"a1w0j000000BtmeAAC\",\"ProductSubCategory\":\"Tax\",\"ProductCategory\":\"Small Firm Software\",\"OtherCompetitor\":null,\"OtherCloseReason\":null,\"OppOwner\":\"Rajesh Gonola\",\"oneforceCon\":\"0000838367\",\"oneforceAcc\":\"0000446962\",\"Name\":\"fgh\",\"ForecastType\":\"Medium (50-90%)\",\"Competitor\":\"AICPA\",\"CloseReason\":\"Adding to Suite\",\"CloseDate\":\"2017-09-25\",\"Amount\":\"669.00\"}]}';
        
        
            req.requestBody = Blob.valueOf(Body);

            req.httpMethod = 'post';
            req.addHeader('Content-Type', 'application/json'); // Add a JSON Header as it is validated 
            req.requestURI = '/services/apexrest/Opportunitysync' ;  
            RestContext.request = req;
            RestContext.response = res;

            //List<Wrapper> lstWrapper = myController.getMeListOfProducts(); // Use this line if wrapper class is outside
            Id result= S2S_Opp_sync.doPost(); 
            
        Test.stopTest();   
  }
  
  static testMethod void Negativepostest()
  {
      
       
        
    
        Test.startTest();

            RestResponse res = new RestResponse();
            RestRequest req = new RestRequest(); 

                      
         String Body= '{\"opps\":[{\"Type\":\"New to Existing\",\"TAAPrimaryContact\":\"0030S0000073vfNQAQ\",\"TAAOppRecordId\":\"0030S0000073vfNQAQ\",\"TAAAccountID\":\"0010S000008H6s1QAC\",\"StageName\":\"5. Time to Buy\",\"SFSPrimaryContact\":\"0030j00000BYUaRAAX\",\"SFSPID\":null,\"SFSOppRecordId\":\"0060j000009DssnAAC\",\"SFSCID\":null,\"SFSAccountID\":\"0010j00000BRS8YAAX\",\"quoteNumber\":\"Q-165685\",\"quoteId\":\"a1w0j000000BtmeAAC\",\"ProductSubCategory\":\"Tax\",\"ProductCategory\":\"Small Firm Software\",\"OtherCompetitor\":null,\"OtherCloseReason\":null,\"OppOwner\":\"Rajesh Gonola\",\"oneforceCon\":\"0000838367\",\"oneforceAcc\":\"0000446962\",\"Name\":\"fgh\",\"ForecastType\":\"Medium (50-90%)\",\"Competitor\":\"AICPA\",\"CloseReason\":\"Adding to Suite\",\"CloseDate\":\"2017-09-25\",\"Amount\":\"669.00\"}]}';
        
        
            req.requestBody = Blob.valueOf(Body);

            req.httpMethod = 'post';
            req.addHeader('Content-Type', 'application/json'); // Add a JSON Header as it is validated 
            req.requestURI = '/services/apexrest/Opportunitysync' ;  
            RestContext.request = req;
            RestContext.response = res;

            //List<Wrapper> lstWrapper = myController.getMeListOfProducts(); // Use this line if wrapper class is outside
            Id result= S2S_Opp_sync.doPost(); 
            
        Test.stopTest();   
  }
  
}