wk_taa_taaqa/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AMS_Credit_Hold__c</fullName>
        <formula>IF( AMS_Credit_Hold_Rollup__c &gt;0,true,false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AMS Credit Hold</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Account_X_Reference__c.object
<CustomObject>
    <fields>
        <fullName>AMS_Credit_Hold__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AMS Credit Hold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account X-Reference</relationshipLabel>
        <relationshipName>Account_X_Reference</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ApplicationID__c</fullName>
        <externalId>true</externalId>
        <label>Application ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS</fullName>
                </value>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>SFS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account X-Reference</label>
    <nameField>
        <label>Account X-Reference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account X-Reference</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/TestAMSCreditHoldFlag.cls
@isTest 
private class TestAMSCreditHoldFlag {

    static testMethod void insertAccountXReference() {
         Account acc = new Account(
            Name = 'myAcct', 
            BillingStreet='25 Upland Drive',
            BillingPostalCode='94127',
            BillingCountry='United States',
            BillingCity='San Francisco' );
        insert acc;
        user u = [select Id from user where lastname = 'Arno'];
Account_x_Reference__c M = new Account_X_Reference__c(account__c =acc.Id, name= '990026',application__c = 'AMS', applicationid__c = '990026',ams_credit_hold__c = true);
 

       
       insert M;
   
          
     
         }
}