wk_taa_taaqa/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting Firms</fullName>
                </value>
                <value>
                    <fullName>Banks and Financial Institutions</fullName>
                </value>
                <value>
                    <fullName>Consultants</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Financial and Estate Planners</fullName>
                </value>
                <value>
                    <fullName>General Corporate</fullName>
                </value>
                <value>
                    <fullName>Hospital and Payers</fullName>
                </value>
                <value>
                    <fullName>Insurance Companies</fullName>
                </value>
                <value>
                    <fullName>Legal Professionals</fullName>
                </value>
                <value>
                    <fullName>Retail Tax Preparers</fullName>
                </value>
                <value>
                    <fullName>Schools and Libraries</fullName>
                </value>
                <value>
                    <fullName>State and Local Government</fullName>
                </value>
                <value>
                    <fullName>Tax Exempt and Membership Organizations</fullName>
                </value>
                <value>
                    <fullName>Agriculture &amp; Mining</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Banks and Financial</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Business Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Computers &amp; Electronics</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Consumer Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Education</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Fin</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Financial Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Government</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Healthcare, Pharmaceuticals, &amp; Biotech</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Hospital &amp; Payers</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Law Schools</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Legal Professional</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Media &amp; Entertainment</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Sub_Segment__c</fullName>
        <label>SubSegment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market_Segment__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sole Proprietor</fullName>
                </value>
                <value>
                    <fullName>2-4 Total Employees</fullName>
                </value>
                <value>
                    <fullName>5-9 Total Employees</fullName>
                </value>
                <value>
                    <fullName>10-19 Total Employees</fullName>
                </value>
                <value>
                    <fullName>20-49 Total Employees</fullName>
                </value>
                <value>
                    <fullName>50-99 Total Employees</fullName>
                </value>
                <value>
                    <fullName>100+ Total Employees</fullName>
                </value>
                <value>
                    <fullName>Top 100 Firms</fullName>
                </value>
                <value>
                    <fullName>Global Enterprise</fullName>
                </value>
                <value>
                    <fullName>Large Enterprise</fullName>
                </value>
                <value>
                    <fullName>Mid Enterprise</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                </value>
                <value>
                    <fullName>Small</fullName>
                </value>
                <value>
                    <fullName>Dept of Agriculture</fullName>
                </value>
                <value>
                    <fullName>Dept of Commerce</fullName>
                </value>
                <value>
                    <fullName>Dept of Defense</fullName>
                </value>
                <value>
                    <fullName>Dept of Energy</fullName>
                </value>
                <value>
                    <fullName>Dept of Health and Human Services</fullName>
                </value>
                <value>
                    <fullName>Dept of Homeland Security</fullName>
                </value>
                <value>
                    <fullName>Dept of Housing and Urban Development</fullName>
                </value>
                <value>
                    <fullName>Dept of Interior</fullName>
                </value>
                <value>
                    <fullName>Dept of Justice</fullName>
                </value>
                <value>
                    <fullName>Dept of Labor</fullName>
                </value>
                <value>
                    <fullName>Dept of State</fullName>
                </value>
                <value>
                    <fullName>Dept of Treasury (not IRS)</fullName>
                </value>
                <value>
                    <fullName>Dept of Vet Affairs</fullName>
                </value>
                <value>
                    <fullName>EEOC</fullName>
                </value>
                <value>
                    <fullName>Exec Branch (White House)</fullName>
                </value>
                <value>
                    <fullName>FCC</fullName>
                </value>
                <value>
                    <fullName>FDIC</fullName>
                </value>
                <value>
                    <fullName>Size TBD</fullName>
                </value>
                <value>
                    <fullName>Law Firm 1-3 Attorneys</fullName>
                </value>
                <value>
                    <fullName>Law Firms (Size TBD)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFS_Account_Record_ID__c</fullName>
        <externalId>true</externalId>
        <label>SFS Account Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/TSM_Custom_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>TSM custom settings for configuration</description>
    <fields>
        <fullName>ConnectionName__c</fullName>
        <label>ConnectionName</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>TSM_Custom_Settings</label>
</CustomObject>

wk_taa_taaqa/src/classes/TSM_AccountTriggerHandler.cls
/*
 * trigger handler class to perform the S2S records replication from TAA org to SFS org  
*/
/*--------------------------------------------------------------------------
 * Date       Author            Version      Description
 * -------------------------------------------------------------------------
 * 11/29/2016 Raj				1.0			Initial draft
 * ------------------------------------------------------------------------- */
public class TSM_AccountTriggerHandler {
	// for after insert operation
    public static void onAfterInsert(List<Account> newRecords) {
    	TSM_Custom_Settings__c tsmCS = TSM_Custom_Settings__c.getInstance();		
        Id networkId = TSM_Util.getNetworkId(tsmCS.ConnectionName__c);        
        List<PartnerNetworkRecordConnection> newAcctShrList = new List<PartnerNetworkRecordConnection>();
		Map<Id, PartnerNetworkRecordConnection> acctShrMap = new Map<Id, PartnerNetworkRecordConnection>();                
        Map<Id, Account> acctMap = new Map<Id, Account>();
        Map<String, String> segmentMap = TSM_Util.getAccountSegments();
		// identify the accounts by using segment and sub segment for SFS sharing        
        for(Account acct: newRecords) {
            if(acct.ConnectionReceivedId == null && acct.SFS_Account_Record_Id__c == null &&
               acct.Market_Segment__c != null &&
              	segmentMap.containsKey(acct.Market_Segment__c)) {
                    // for segment=legal professional 
                    if(acct.Market_Segment__c == 'Legal Professionals' && acct.Market_Sub_Segment__c != null &&
                      (acct.Market_Sub_Segment__c == 'Law Firm 1-3 Attorneys' || acct.Market_Sub_Segment__c == 'Law Firms (Size TBD)')) {
                    	acctMap.put(acct.Id, acct);   
                    } else if (acct.Market_Segment__c != 'Legal Professionals' && acct.Market_Sub_Segment__c != null && 
                               // for segment = other 3 types
                               (acct.Market_Sub_Segment__c == 'Sole Proprietor' || 
                                acct.Market_Sub_Segment__c == '2-4 Total Employees' || 
                                acct.Market_Sub_Segment__c == 'Size TBD')) {
                        acctMap.put(acct.Id, acct);
                    }            	
            }
        }
        // fetch the existing shares
        acctShrMap = TSM_Util.fetchExistingShares(acctMap.keySet(), networkId);  
        // compare them with the existing shares for preparing new shares
        for(Account a: acctMap.values()) {
            if(!acctShrMap.containsKey(a.Id)) {
                newAcctShrList.add(TSM_Util.prepareShare(a.Id, networkId, null));                
            }
        }
        
   
        // #Deprecated :SMS - 752 This method is replaced by insertSharesObject which allows replication Logging
        //TSM_Util.insertShares(newAcctShrList,'TSM_AccountTrigger','Trigger');
        
        // insert the new shares bulk
        // SMS - 752 :InsertShares method is replaced by insertSharesObject which is Returning IDs of pertnerNetworkRecordConnection.
        List<String> accountShareObjectListIds = TSM_Util.insertSharesObject(newAcctShrList,'TSM_AccountTrigger','Trigger');
        if(accountShareObjectListIds.size()>0){
        	TSM_Util.insertReplicationMonitoringLog(accountShareObjectListIds,'Account');
        } 
       
        
        // below logic to unshare the record after successful completion of sharing.
        //updateAccountShares(acctMap.keySet(), networkId);
    }
    
}