wk_taa_taaqa/src/objects/AccountAutomationSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ATA_ExcludeAccountRecordType__c</fullName>
        <description>Exclude Account Record Type in Account Team Automation</description>
        <inlineHelpText>Exclude Account Record Type in Account Team Automation</inlineHelpText>
        <label>ATA_ExcludeAccountRecordType</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchJobAdmin__c</fullName>
        <label>BatchJobAdmin</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GeneralDataSizeInBatchJob__c</fullName>
        <label>GeneralDataSizeInBatchJob</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsTriggerOff__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Trigger Off</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Terminate_Account_Team_Role_Names__c</fullName>
        <description>Collection of role name strings for which if no assignment is found then prevents the account team creation.</description>
        <inlineHelpText>Collection of role name strings for which if no assignment is found then prevents the account team creation.</inlineHelpText>
        <label>Terminate Account Team Role Names</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AccountAutomationSetting</label>
</CustomObject>

wk_taa_taaqa/src/objects/ATA_AssignmentType_Map__c.object
<CustomObject>
    <description>This holds the map of distinct assignment types to Account Field API Names and the values that drive the 
assignment: This is used in conjunction with the ATA_Rule object and the ATA_Role_Assignment object to obtain the list of Account Team Roles for a given combination of fields values that uniquely determine the Role Assignment.</description>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Assignment Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldSet__c</fullName>
        <label>FieldSet</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Type__c</fullName>
        <label>Rule Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ATA AssignmentType Map</label>
    <nameField>
        <displayFormat>ATA-TypeMap-{0000}</displayFormat>
        <label>ATA AssignmentType Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATA AssignmentType Map</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/ATA_Geographic_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>DTN__c</fullName>
        <label>DTN</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ATA Geographic Assignment</label>
    <nameField>
        <displayFormat>ATAGA-{00000}</displayFormat>
        <label>ATA Geographic Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATA Geographic Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/ATA_Non_Geographic_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>DTN__c</fullName>
        <label>DTN</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Functional type, this rule is used for, either AccountTeam / LeadOwnership</description>
        <inlineHelpText>Functional type, this rule is used for, either AccountTeam / LeadOwnership</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AccountTeam</fullName>
                </value>
                <value>
                    <fullName>LeadOwnership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ATA Non Geographic Assignment</label>
    <nameField>
        <displayFormat>ATANGA-{00000}</displayFormat>
        <label>ATA Non-Geographic Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATA Non Geographic Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/ATA_Role_Assignment__c.object
<CustomObject>
    <description>List of Role Assignments by RoleAssignmentType with attributes to distinguish mechanism of assignment to territory numbers</description>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Assignment Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ATA Role Assignment</label>
    <nameField>
        <displayFormat>ATARA-{0000}</displayFormat>
        <label>Role Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATA Role Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/ATA_Rule__c.object
<CustomObject>
    <description>Defines collection of field driving a rule.</description>
    <fields>
        <fullName>FieldSet__c</fullName>
        <description>FieldSet Name</description>
        <label>FieldSet</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rule Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rule_Type__c</fullName>
        <label>Rule Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ATA</fullName>
                </value>
                <value>
                    <fullName>LeadOwnership</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sobject__c</fullName>
        <description>Object to which we apply the rule</description>
        <label>Sobject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ATA Rule</label>
    <nameField>
        <displayFormat>ATARULE-{00000}</displayFormat>
        <label>ATA Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATA Rule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CostCenter__c</fullName>
        <label>Cost Center</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DTN__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>External Id for User</inlineHelpText>
        <label>DTN</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>High_Level_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Executives</fullName>
                    <color>#AFCADF</color>
                </value>
                <value>
                    <fullName>A&amp;A Solution Architects</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Admin</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Alliance</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Billing</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Books &amp; Journal Sales</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Central</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Central Division</fullName>
                    <color>#66E9BD</color>
                </value>
                <value>
                    <fullName>Corp. Solution Architects</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Corp National</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Corporate Business Development</fullName>
                    <color>#641CCF</color>
                </value>
                <value>
                    <fullName>Corporate Direct</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Corporate - SA</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Corporate Software</fullName>
                    <color>#F96FB7</color>
                </value>
                <value>
                    <fullName>Corp SW Energy &amp; Telco</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Corp SW Microsoft</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Corp SW SAP &amp; NetSuite</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>East - SA</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                    <color>#8F6429</color>
                </value>
                <value>
                    <fullName>Global Accounts</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                    <color>#EFAE73</color>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Mid-Atlantic</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Mountain Division</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>N2E Small Firm</fullName>
                </value>
                <value>
                    <fullName>N2N (GW) Small Firm</fullName>
                </value>
                <value>
                    <fullName>N2N (JA) Small Firm</fullName>
                </value>
                <value>
                    <fullName>N2N (LF) Small Firm</fullName>
                </value>
                <value>
                    <fullName>Northeast</fullName>
                    <color>#0B24BE</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>High_Level_Division__c</fullName>
        <label>High Level Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Software</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>National &amp; Strategic Accounts</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Research &amp; Learning</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Software</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>US Small Firms</fullName>
                    <color>#2F5D85</color>
                </value>
                <value>
                    <fullName>Executives</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Sales Operations</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Service Source</fullName>
                </value>
                <value>
                    <fullName>Solution Design</fullName>
                    <color>#66E9BD</color>
                </value>
                <value>
                    <fullName>Training &amp; Consulting</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Cap Gemini</fullName>
                </value>
                <value>
                    <fullName>Mid-Market</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Charge_To__c</fullName>
        <label>License Charge To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Product Development</fullName>
                </value>
                <value>
                    <fullName>Product Management</fullName>
                </value>
                <value>
                    <fullName>R&amp;L</fullName>
                </value>
                <value>
                    <fullName>R&amp;L Marketing</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>SVE</fullName>
                </value>
                <value>
                    <fullName>Training &amp; Consulting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/ATA_TestDateFactory.cls
/*--------------------------------------------------------------------------
 * Date       Author            Version      Description
 * -------------------------------------------------------------------------
 * 12/27/2017 SHIVAJI           1.0          ATA 2.0
 * ------------------------------------------------------------------------- */
@isTest
public class ATA_TestDateFactory 
{
	// *** test data factory class for ATA
	
    public static Account create_Account() 
    {
        // create Account
        Account acctObj = new Account(
            Name = 'ATA_TEST_ACCOUNT', 
            BillingStreet = '25 Upland Drive',
            BillingPostalCode = '94127-1007',
            BillingCountry = 'USA',
            BillingCity = 'San Francisco');
            
        return acctObj;
    }
   
    public static User create_NewUser(String dtn, Integer i)
    {
        //create user
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
         
        User u = new User();
        u.Alias = 'standt' + i;
        u.Email = i + 'standarduser@test.com'; 
        u.EmailEncodingKey = 'UTF-8'; 
        u.LastName = 'Testing'+i; 
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US'; 
        u.ProfileId = p.Id; 
        u.TimeZoneSidKey = 'America/Los_Angeles'; 
        u.UserName = i + 'standarduser@testorg.com';
        u.DTN__c = dtn; 
        u.High_Level_Division__c = 'Research and Learning';
        u.Division__c = 'Northeast';
        u.License_Charge_To__c = 'Sales';
        u.CostCenter__c = '1110';
        insert u;
        
        return u;
    }
	
   	public static AccountAutomationSetting__c create_ATACustomSetting()
    {
        // create ATA custom setting
        AccountAutomationSetting__c t = new AccountAutomationSetting__c( 
	        ATA_RuleType__c = 'ATA',
	        BatchJobAdmin__c = 'test@example.com',
	        ATA_ExcludeAccountRecordType__c = 'Partner Account',
	        GeneralDataSizeInBatchJob__c = 200,
	        Terminate_Account_Team_Role_Names__c = '["National Solution Consultant","Strategic Solution Consultant"]',
	        IsTriggerOff__c = false);
        
        insert t;
        
        return t;
    }
    
    public static ATA_Rule__c create_ATARule(String fieldAPIName) 
    {
        // create ATA Rule 
        ATA_Rule__c ruleObj = new ATA_Rule__c(
        	Rule_Type__c = 'ATA',
            FieldSet__c = fieldAPIName.replace('__c', ''), 
            Field_API_Name__c = fieldAPIName,
            Sobject__c = 'Account',
            Rule_Enabled__c = true);
            
        insert ruleObj;
        
        return ruleObj;
    }
    
    public static ATA_AssignmentType_Map__c create_ATAAssignmentType(String assignmentType, String ruleType, String fieldSet, String fieldAPIName, String fieldValue) 
    {
        // create ATA AssignmentType Map
        ATA_AssignmentType_Map__c objAssignmentType = new ATA_AssignmentType_Map__c(
        	Assignment_Type__c = assignmentType,
            Rule_Type__c = ruleType,
            FieldSet__c = fieldSet,
            Field_API_Name__c = fieldAPIName,
            Field_Value__c = fieldValue);
            
        insert objAssignmentType;
        
        return objAssignmentType;
    }
    
    public static ATA_Role_Assignment__c create_ATARoleAssignment(String assignmentType, String roleAssignmentType, String roleName, String assignmentMechanism) 
    {
        // create ATA Role Assignment
        ATA_Role_Assignment__c objRoleAssignment = new ATA_Role_Assignment__c(
        	Assignment_Type__c = assignmentType,
            Role_Assignment_Type__c = roleAssignmentType,
            Role_Name__c = roleName,
            Assignment_Mechanism__c = assignmentMechanism);
            
        insert objRoleAssignment;
        
        return objRoleAssignment;
    }
    
    public static ATA_Geographic_Assignment__c create_ATAGeographicAssignment(String postalCode, String roleName, String dtn) 
    {
        // create ATA Geo Assignment
        ATA_Geographic_Assignment__c objGeoAssignment = new ATA_Geographic_Assignment__c(
        	PostalCode__c = postalCode,
            Role_Name__c = roleName,
            DTN__c = dtn);
            
        insert objGeoAssignment;
        
        return objGeoAssignment;
    }
    
    public static ATA_Non_Geographic_Assignment__c create_ATANongeographicAssignment(String assignmentType, String fieldAPIName, String fieldValue, String roleName, String dtn, String roleAssignmentType) 
    {
        // create ATA Non geo Assignment
        ATA_Non_Geographic_Assignment__c objNongeoAssignment = new ATA_Non_Geographic_Assignment__c(
        	Type__c = assignmentType,
        	FieldName__c = fieldAPIName,
        	FieldValue__c = fieldValue,
        	RoleName__c = roleName,
        	DTN__c = dtn,
        	Role_Assignment_Type__c = roleAssignmentType);
            
        insert objNongeoAssignment;
        
        return objNongeoAssignment;
    }
}