wk_taa_taaqa/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Corp_Direct__c</fullName>
        <label>Corp Direct DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_Indirect__c</fullName>
        <label>Corp Indirect DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISR_Indirect__c</fullName>
        <label>ISR Indirect</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAM_SAM_CNAM__c</fullName>
        <label>NAM/SAM/CNAM DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_SW_FSR__c</fullName>
        <label>Pro SW RSC DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_ASR__c</fullName>
        <label>R&amp;L RC DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_FSR__c</fullName>
        <label>R&amp;L RSC DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SW_ASR__c</fullName>
        <label>SW RC DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Source__c</fullName>
        <label>Service Source DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Assignment_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>ASR_Indirect_Corp_Software__c</fullName>
        <description>ASR Indirect (Corp Software)</description>
        <inlineHelpText>ASR Indirect (Corp Software)</inlineHelpText>
        <label>ASR Indirect (Corp Software)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_Direct__c</fullName>
        <inlineHelpText>FSR - Direct (Corp Software)</inlineHelpText>
        <label>Corp Direct</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_Indirect__c</fullName>
        <inlineHelpText>FSR - Indirect (Corp Sotware)</inlineHelpText>
        <label>Corp Indirect</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISR_Indirect__c</fullName>
        <inlineHelpText>ISR - Indirect (Corp Software)</inlineHelpText>
        <label>ISR Indirect</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAM_SAM_CNAM__c</fullName>
        <inlineHelpText>NAM- National Account Manager, SAM-Strategic Account Manager, CNAM-Corporate Account Manager</inlineHelpText>
        <label>NAM/SAM/CNAM</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NAM - National Accounts</fullName>
                </value>
                <value>
                    <fullName>SAM - Strategic Account Manager</fullName>
                </value>
                <value>
                    <fullName>CAM - Corporate Account Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pro_SW_FSR__c</fullName>
        <inlineHelpText>FSR- Professional Sotware</inlineHelpText>
        <label>Pro SW FSR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_SW_ISR__c</fullName>
        <inlineHelpText>ISR - Professional Software</inlineHelpText>
        <label>Pro SW ISR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_ASR__c</fullName>
        <inlineHelpText>ASR - Research and Learning</inlineHelpText>
        <label>R&amp;L ASR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_FSR__c</fullName>
        <inlineHelpText>FSR - Research and Learning</inlineHelpText>
        <label>R&amp;L FSR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_ISR__c</fullName>
        <inlineHelpText>ISR Research and learning</inlineHelpText>
        <label>R&amp;L ISR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SW_ASR__c</fullName>
        <inlineHelpText>ASR - Professional Software</inlineHelpText>
        <label>SW ASR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Source__c</fullName>
        <inlineHelpText>ASR - R&amp;L - Service Source</inlineHelpText>
        <label>Service Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assignment Matrix</label>
    <nameField>
        <label>Assignment Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Matrixs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Corporate_National_Role_DTN__c.object
<CustomObject>
    <description>Corporate National Accounts Named Account Type Corporate National</description>
    <fields>
        <fullName>DTN__c</fullName>
        <description>Division Territory Number</description>
        <label>DTN</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>Corporate National Role-DTN</label>
    <nameField>
        <displayFormat>CNA-{000}</displayFormat>
        <label>Corp National Role-DTN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corporate National Role-DTN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/National_Account_Management__c.object
<CustomObject>
    <description>Defines the National Account Management Role for Named Accounts with Named Account Type = National</description>
    <fields>
        <fullName>DTN__c</fullName>
        <label>DTN</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>National Account Management</label>
    <nameField>
        <displayFormat>NAM-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Account Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/ServiceSource_Role_DTN__c.object
<CustomObject>
    <fields>
        <fullName>DTN__c</fullName>
        <label>DTN</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>ServiceSource Role DTN</label>
    <nameField>
        <displayFormat>SS-{000}</displayFormat>
        <label>ServiceSource Role DTN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ServiceSource Role DTNs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Strategic_Account_RoleDTN__c.object
<CustomObject>
    <description>Defines the Strategic Account Roles of Strategic Account Manager (SAM) and Solution Architect (SA) Per DTN</description>
    <fields>
        <fullName>DTN__c</fullName>
        <label>DTN</label>
        <length>7</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Strategic Account Role-DTN</label>
    <nameField>
        <displayFormat>SAM-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Account RoleDTN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>DTN__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>External Id for User</inlineHelpText>
        <label>DTN</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/ZipCodeDTN__c.object
<CustomObject>
    <fields>
        <fullName>ASR_Indirect_Corp_Software__c</fullName>
        <description>ASR Indirect (Corp Software)</description>
        <inlineHelpText>ASR Indirect (Corp Software)</inlineHelpText>
        <label>ASR Indirect (Corp Software)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_Direct__c</fullName>
        <inlineHelpText>FSR - Direct (Corp Software)</inlineHelpText>
        <label>Corp Direct</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_Indirect__c</fullName>
        <inlineHelpText>FSR - Indirect (Corp Sotware)</inlineHelpText>
        <label>Corp Indirect</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISR_Indirect__c</fullName>
        <inlineHelpText>ISR - Indirect (Corp Software)</inlineHelpText>
        <label>ISR Indirect</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAM_SAM_CNAM__c</fullName>
        <inlineHelpText>CNAM-Corporate Account Manager, SAM-Strategic Account Manager, CNAM-Corporate Account Manager</inlineHelpText>
        <label>NAM/SAM/CNAM</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_SW_FSR__c</fullName>
        <inlineHelpText>FSR- Professional Sotware</inlineHelpText>
        <label>Pro SW FSR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_SW_ISR__c</fullName>
        <inlineHelpText>ISR - Professional Software</inlineHelpText>
        <label>Pro SW ISR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_ASR__c</fullName>
        <inlineHelpText>ASR - Research and Learning</inlineHelpText>
        <label>R&amp;L ASR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_FSR__c</fullName>
        <inlineHelpText>FSR - Research and Learning</inlineHelpText>
        <label>R&amp;L FSR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_ISR__c</fullName>
        <label>R&amp;L ISR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SW_ASR__c</fullName>
        <inlineHelpText>ASR - Professional Software</inlineHelpText>
        <label>SW ASR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Source__c</fullName>
        <inlineHelpText>ASR - R&amp;L - Service Source</inlineHelpText>
        <label>Service Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Zip Code DTN</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes DTN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/TestDTNMakeupFieldAssignment.cls
@isTest(SeeAllData= false)
private class TestDTNMakeupFieldAssignment{
    //setup for test to be executed
   static void setup(){
        list<Market_Segment_Mapping__c> msmList = TestDataFactory.marketSegmetMappings();
        list<Market_Segment_Rules__c> msrList = TestDataFactory.marketSegmentRules();
        list<Market_Sub_Segment_Mapping__c> mssmList = TestDataFactory.marketSubSegmentMappings();
        User u1 = TestDataFactory.newUser('211a',1);
        User u2 = TestDataFactory.newUser('211b',2);
        User u3 = TestDataFactory.newUser('211c',3);
        User u4 = TestDataFactory.newUser('211d',4);
        User u5 = TestDataFactory.newUser('211e',5);
        User u6 = TestDataFactory.newUser('211f',6);
        User u7 = TestDataFactory.newUser('211g',7);
        User u8 = TestDataFactory.newUser('211h',8);
        User u9 = TestDataFactory.newUser('211i',9);
        User u10 = TestDataFactory.newUser('211j',10);
        User u11 = TestDataFactory.newUser('211k',11);
        User u12= TestDataFactory.newUser('211l',12);
        User u13 = TestDataFactory.newUser('211m',13);
        User u14 = TestDataFactory.newUser('211n',14);
        ZipCodeDTN__c z=TestDataFactory.zipCodeDtn('55555', '211a', '211b');
        z.ASR_Indirect_Corp_Software__c='211c';
        z.Corp_Direct__c = '211d';
        z.Corp_Indirect__c = '211e';
        z.ISR_Indirect__c = '211f';
        z.NAM_SAM_CNAM__c = '211g';
        z.Pro_SW_FSR__c = '211h';
        z.Pro_SW_ISR__c = '211i';
        z.R_L_ASR__c = '211j';
        z.R_L_FSR__c = '211k';
        z.SW_ASR__c='211l';
        z.Service_Source__c = '211m';
        z.R_L_ISR__c='211n';
        update z;
        List<Assignment_Matrix__c>assignmentMatrix = new List<Assignment_Matrix__c>();
        assignmentMatrix.add(TestDataFactory.assignmentMatrixWithAF('Accounting Firms','5-9 Total Employees'));
        assignmentMatrix.add(TestDataFactory.assignmentMatrixForNamedAccount('Named Accounts','National','National','National Solution Consultant'));
        String username = [Select id,Name,DTN__c from user where DTN__c='211a'].Name;
        AccountAutomationSetting__c taa = TestDataFactory.newTaaCustomSetting(username);
        Strategic_Account_RoleDTN__c sam = TestDataFactory.newSAR('DemoSAM','211j',u10,u10);
        Corporate_National_Role_DTN__c cnr = TestDataFactory.newCNR('DemoCNR', u11, '211k');
        National_Account_Management__c nam = TestDataFactory.newNAM('DemoNAM', '211g', u12);
        ServiceSource_Role_DTN__c ss= TestDataFactory.newSS('DemoSS','211m',u13);
    }
    static testMethod void testTNMakeupFieldAssignment1() {
        setup();
        Account acct1 = new Account(Name='myAccount', billingPostalCode='55555',Market_Segment__c='Accounting Firms', Market_Sub_Segment__c='5-9 Total Employees',Named_Account__c=false);
        
        insert acct1;
        Account a=[Select Name,billingPostalCode, Market_SegMEnt__c,Market_Sub_Segment__c,Named_Account__c,AISR__c,Corp_Direct__c,Corp_Indirect__c,Inside_Sales__c,NAM_SAM_CNAM__c,Pro_SW_FSR__c,QP__c,R_L_ASR__c,R_L_FSR__c,R_L_ISC__c,SW_ASR__c,Service_Source__c from Account where name='myAccount' Limit 1];
        a.AISR__c='';
        a.Corp_Direct__c='';
        a.Corp_Indirect__c='';
        a.Inside_Sales__c='';
        a.NAM_SAM_CNAM__c='';
        a.Pro_SW_FSR__c='';
        a.QP__c='';
        a.R_L_ASR__c='';
        a.R_L_FSR__c='';
        a.R_L_ISC__c='';
        a.SW_ASR__c='';
        a.Service_Source__c='';
        update a;
        Test.startTest();
        DTNMakeupFieldAssignment dmf= new DTNMakeupFieldAssignment();
        Database.executebatch(dmf);
        Test.stopTest();
        Account ac=[Select Name,billingPostalCode, Market_SegMEnt__c,Market_Sub_Segment__c,Named_Account__c,AISR__c,Corp_Direct__c,Corp_Indirect__c,Inside_Sales__c,NAM_SAM_CNAM__c,Pro_SW_FSR__c,QP__c,R_L_ASR__c,R_L_FSR__c,R_L_ISC__c,SW_ASR__c,Service_Source__c from Account where name='myAccount' Limit 1];
       // system.assertEquals('211a',ac.AISR__c);
        //system.assertEquals('211b',ac.QP__c);'
        //system.assertEquals('211m',ac.Service_Source__c);
    }
    static testMethod void testTNMakeupFieldAssignmentforNamedAccount() {
        setup();
        Account acct1 = new Account(Name='DemoNAM', billingPostalCode='55555',Market_Segment__c='Accounting Firms', Market_Sub_Segment__c='5-9 Total Employees',Named_Account__c=true,Named_Account_Type__c='National');
        
        insert acct1;
        Account a=[Select Name,billingPostalCode, Market_SegMEnt__c,Market_Sub_Segment__c,Named_Account__c,AISR__c,Corp_Direct__c,Corp_Indirect__c,Inside_Sales__c,NAM_SAM_CNAM__c,Pro_SW_FSR__c,QP__c,R_L_ASR__c,R_L_FSR__c,R_L_ISC__c,SW_ASR__c,Service_Source__c from Account where name='DemoNAM' Limit 1];
        a.AISR__c='';
        a.Corp_Direct__c='';
        a.Corp_Indirect__c='';
        a.Inside_Sales__c='';
        a.NAM_SAM_CNAM__c='';
        a.Pro_SW_FSR__c='';
        a.QP__c='';
        a.R_L_ASR__c='';
        a.R_L_FSR__c='';
        a.R_L_ISC__c='';
        a.SW_ASR__c='';
        a.Service_Source__c='';
        update a;
        Test.startTest();
        DTNMakeupFieldAssignment dmf= new DTNMakeupFieldAssignment();
        Database.executebatch(dmf);
        Test.stopTest();
        Account ac=[Select Name,billingPostalCode, Market_SegMEnt__c,Market_Sub_Segment__c,Named_Account__c,AISR__c,Corp_Direct__c,Corp_Indirect__c,Inside_Sales__c,NAM_SAM_CNAM__c,Pro_SW_FSR__c,QP__c,R_L_ASR__c,R_L_FSR__c,R_L_ISC__c,SW_ASR__c,Service_Source__c from Account where name='DemoNAM' Limit 1];
       // system.assertEquals('211a',ac.AISR__c);
        //system.assertEquals('211b',ac.QP__c);
        System.assertEquals('211g',ac.NAM_SAM_CNAM__c);
    }
      static testMethod void testTNMakeupFieldAssignmentServiceSource() {
        setup();
        Account acct1 = new Account(Name='DemoSS', billingPostalCode='55555',Market_Segment__c='Accounting Firms', Market_Sub_Segment__c='5-9 Total Employees',Named_Account__c=true,Named_Account_Type__c='Service Source');
        
        insert acct1;
        Account a=[Select Name,billingPostalCode, Market_SegMEnt__c,Market_Sub_Segment__c,Named_Account__c,AISR__c,Corp_Direct__c,Corp_Indirect__c,Inside_Sales__c,NAM_SAM_CNAM__c,Pro_SW_FSR__c,QP__c,R_L_ASR__c,R_L_FSR__c,R_L_ISC__c,SW_ASR__c,Service_Source__c from Account where name='DemoSS' Limit 1];
        a.AISR__c='';
        a.Corp_Direct__c='';
        a.Corp_Indirect__c='';
        a.Inside_Sales__c='';
        a.NAM_SAM_CNAM__c='';
        a.Pro_SW_FSR__c='';
        a.QP__c='';
        a.R_L_ASR__c='';
        a.R_L_FSR__c='';
        a.R_L_ISC__c='';
        a.SW_ASR__c='';
       // a.Service_Source__c='';
        update a;
        Test.startTest();
        DTNMakeupFieldAssignment dmf= new DTNMakeupFieldAssignment();
        Database.executebatch(dmf);
        Test.stopTest();
        Account ac=[Select Name,billingPostalCode, Market_SegMEnt__c,Market_Sub_Segment__c,Named_Account__c,AISR__c,Corp_Direct__c,Corp_Indirect__c,Inside_Sales__c,NAM_SAM_CNAM__c,Pro_SW_FSR__c,QP__c,R_L_ASR__c,R_L_FSR__c,R_L_ISC__c,SW_ASR__c,Service_Source__c from Account where name='DemoSS' Limit 1];
       // system.assertEquals('211a',ac.AISR__c);
        system.assertEquals('211b',ac.QP__c);
        system.assertEquals('211m',ac.Service_Source__c);
    }
}