wk_taa_taaqa/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SFDC_Account__c</fullName>
        <displayFormat>{0000000000}</displayFormat>
        <externalId>true</externalId>
        <label>SFDC Account #</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Reason__c</fullName>
        <label>Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Adding to Suite</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Add-on Sale</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Better Price</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>CCH Experience</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Competition - Content / Software issue</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Competition - Platform</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Competition - Price</fullName>
                    <color>#66E9BD</color>
                </value>
                <value>
                    <fullName>Competitive Conversion</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Combining contracts</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Conversion to Better Solution</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Converted By Mistake</fullName>
                    <color>#641CCF</color>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                    <color>#F96FB7</color>
                </value>
                <value>
                    <fullName>Features / Functionality</fullName>
                    <color>#2F5D85</color>
                </value>
                <value>
                    <fullName>Merger with non WK Firm</fullName>
                    <color>#AFCADF</color>
                </value>
                <value>
                    <fullName>Merger with WK Firm</fullName>
                    <color>#8F6429</color>
                </value>
                <value>
                    <fullName>No Decision</fullName>
                    <color>#EFAE73</color>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <color>#57F17C</color>
                </value>
                <value>
                    <fullName>Strong References</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Change effective dates</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Change in business - Bankrupt</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Change in business - Budget cuts</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Change in business - Business focus change</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Change in business - Personnel change</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Change in business - Went out of business</fullName>
                    <color>#66E9BD</color>
                </value>
                <value>
                    <fullName>Conversion - Step Down</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Conversion - Step Over</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Conversion - Step Up</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Correct order entry error</fullName>
                    <color>#641CCF</color>
                </value>
                <value>
                    <fullName>Credit dept cancel</fullName>
                    <color>#F96FB7</color>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                    <color>#2F5D85</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Competitor__c</fullName>
        <label>Competitor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AICPA</fullName>
                </value>
                <value>
                    <fullName>ATX</fullName>
                </value>
                <value>
                    <fullName>Avalara</fullName>
                </value>
                <value>
                    <fullName>BNA</fullName>
                </value>
                <value>
                    <fullName>Cambridge</fullName>
                </value>
                <value>
                    <fullName>Caseware</fullName>
                </value>
                <value>
                    <fullName>Cengage Learning</fullName>
                </value>
                <value>
                    <fullName>Corptax</fullName>
                </value>
                <value>
                    <fullName>Crosslink</fullName>
                </value>
                <value>
                    <fullName>Drake</fullName>
                </value>
                <value>
                    <fullName>Ichannel</fullName>
                </value>
                <value>
                    <fullName>Intuit - Lacerte</fullName>
                </value>
                <value>
                    <fullName>Intuit - Proseries</fullName>
                </value>
                <value>
                    <fullName>Intuit - Tax Online</fullName>
                </value>
                <value>
                    <fullName>McGraw-Hill</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pearson Educational (Formerly PH)</fullName>
                </value>
                <value>
                    <fullName>PFX Merger</fullName>
                </value>
                <value>
                    <fullName>SurePrep</fullName>
                </value>
                <value>
                    <fullName>TaxSlayer</fullName>
                </value>
                <value>
                    <fullName>Taxware</fullName>
                </value>
                <value>
                    <fullName>Thomson</fullName>
                </value>
                <value>
                    <fullName>Thomson - GoSystem</fullName>
                </value>
                <value>
                    <fullName>Thomson – Ultratax</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Vertex</fullName>
                </value>
                <value>
                    <fullName>Wiley Publishing</fullName>
                </value>
                <value>
                    <fullName>XCM Solution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Forecast_Type__c</fullName>
        <label>Forecast Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Low (&lt;50%)</fullName>
                    <color>#DDDDDD</color>
                </value>
                <value>
                    <fullName>Medium (50-90%)</fullName>
                    <color>#FF9900</color>
                </value>
                <value>
                    <fullName>High (&gt;90%)</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Omitted</fullName>
                    <color>#A53711</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Software</fullName>
                </value>
                <value>
                    <fullName>Med/Large Software</fullName>
                </value>
                <value>
                    <fullName>Small Firm Software</fullName>
                </value>
                <value>
                    <fullName>Research &amp; Learning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFDC_Account__c</fullName>
        <formula>Account.SFDC_Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SFDC Account #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Contact__c</fullName>
        <formula>Primary_Contact_for_Proposal__r.SFDC_Contact__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SFDC Contact #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFS_Opp_Stage__c</fullName>
        <formula>IF(Text(StageName)==&apos;6. Closed Won&apos;,&apos;Onboard&apos;, 
 IF(Text(StageName)==&apos;7. Closed Lost&apos;,&apos;Lost Opportunity&apos;,
IF(Text(StageName)==&apos;2. Recognize Need&apos;,&apos;Recognize Needs&apos;,       

TRIM(
RIGHT(
    Text(StageName) ,  (LEN(Text(StageName)) - 2 )
        
    )
) )))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SFS Opp Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFS_Opp_Type__c</fullName>
        <formula>IF( ( Text(Type)==&apos;New to New&apos;  ) , &apos;New Sale To New Customer&apos;, 
IF( ( Text(Type)==&apos;Non-Subscription&apos;  ) , &apos;New Sale To New Customer&apos;,
IF(( Text(Type)==&apos;New to Existing&apos;  ) , &apos;New Sale To Existing Customer&apos;, 
IF(( Text(Type)==&apos;Renewal&apos;  ) , &apos;Renewal&apos;, &apos;&apos;) ) ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SFS Opp Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFS_Opportunity_ID__c</fullName>
        <externalId>true</externalId>
        <label>SFS Opportunity Record ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TAA_Opportunity_Owner_Id__c</fullName>
        <label>TAA Opportunity Owner Id</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TAA_Opportunity_Owner__c</fullName>
        <description>Email for the Opportunity Owner</description>
        <formula>Owner.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TAA Opportunity Owner</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/S2S_OpportunityTriggerHandler.cls
/*
 * apex class to perform the S2S records replication for TAA <-> SFS orgs  
 * This class  is used for replicating opp chnages from SFS --> TAA.
*/
/*--------------------------------------------------------------------------
 * Date       Author            Version      Description
 * -------------------------------------------------------------------------
 * 09/13/2017 Raj Gonola       1.0      Initial draft
 * ------------------------------------------------------------------------- */
public class S2S_OpportunityTriggerHandler {
  
       // for recursion control
    public static boolean alreadyProcessed = false;
    
    
     // processing logic for before update operation
    public static void opponBeforeupdate(Map<Id,Opportunity> newRecordsMap, Map<Id,Opportunity> oldRecordsMap) {
    
        Set<String> ownerEmails = new Set<String>();
        Map<String, Id> userEmailMap = new Map<String, Id>();
        
          for(Opportunity opp: newRecordsMap.values()) {
            
            // this is to prepare the set of email address of the owners
            if(opp.SFS_Opportunity_ID__c != null && opp.TAA_Opportunity_Owner_ID__c != oldRecordsMap.get(opp.Id).TAA_Opportunity_Owner_ID__c ) {
              ownerEmails.add(opp.TAA_Opportunity_Owner_Id__c);
            }
            system.debug('email here'+opp.Owner.Email);
            if(opp.SFS_Opportunity_ID__c  != null && opp.OwnerId != oldRecordsMap.get(opp.Id).OwnerId) {
            system.debug('email here'+opp.Owner.Email);
              opp.TAA_Opportunity_Owner_ID__c= opp.TAA_Opportunity_Owner__c;
            }
            
            if(!String.isblank(oldRecordsMap.get(opp.Id).SFS_Opportunity_ID__c)&& String.isblank(opp.SFS_Opportunity_ID__c)) opp.SFS_Opportunity_ID__c=oldRecordsMap.get(opp.Id).SFS_Opportunity_ID__c;
           }
       
           // map the owner ids to respective owners in SFS 
        for(User usr : [SELECT Id, Email, FederationIdentifier FROM User WHERE Email IN :ownerEmails AND
                IsActive = true AND UserType ='Standard']) {
                  userEmailMap.put(usr.Email, usr.Id);
        }
        
        for(Opportunity opp: newRecordsMap.values()) {
           
           // set the owner ids to respective TAA opportunity owners
           if(opp.SFS_Opportunity_ID__c  != null && opp.TAA_Opportunity_Owner_ID__c != null && userEmailMap.containsKey(opp.TAA_Opportunity_Owner_ID__c)) {
               opp.OwnerId = userEmailMap.get(opp.TAA_Opportunity_Owner_ID__c);
           }
           
        }
    
    }
    
    
    
    
     // processing logic for update operation
    public static void opponAfterupdate(Map<Id,Opportunity> newRecordsMap, Map<Id,Opportunity> oldRecordsMap) {
          
          S2S_OppUtil oput = new S2S_OppUtil();
          List<S2S_OppUtil.opps> setopps = new List<S2S_OppUtil.opps>();
          List<Account> accountToupdate= new List<Account>();
          Map<ID,Opportunity> actpid = new Map<ID,Opportunity>();
          
          Datetime stsrttime;
       stsrttime = Datetime.now();
      Integer seconds = stsrttime.second();
      
        // List of SFDC Account #
        for(Opportunity opp: newRecordsMap.values()) {
            
            // this is to prepare the set of email address of the owners
            if(( opp.OwnerId != oldRecordsMap.get(opp.Id).OwnerId || opp.Name!= oldRecordsMap.get(opp.Id).Name || opp.Amount!= oldRecordsMap.get(opp.Id).Amount || opp.CloseDate!= oldRecordsMap.get(opp.Id).CloseDate || opp.Closed_Reason__c!= oldRecordsMap.get(opp.Id).Closed_Reason__c|| opp.StageName!= oldRecordsMap.get(opp.Id).StageName
                 || opp.Forecast_Type__c!= oldRecordsMap.get(opp.Id).Forecast_Type__c || opp.Competitor__c!= oldRecordsMap.get(opp.Id).Competitor__c ) 
                   && !String.isblank(opp.SFS_Opportunity_ID__c) ) {
            
                 S2S_OppUtil.opps  opplines   = new  S2S_OppUtil.opps();
                 
                 opplines.oneforceAcc=opp.SFDC_Account__c;
                 opplines.oneforceCon=opp.SFDC_Contact__c;
                   
                 opplines.SFSOppRecordId=opp.SFS_Opportunity_ID__c;
                
                 
                 opplines.TAAOppRecordId=opp.Id;
                 
                 
                 opplines.Type=opp.SFS_Opp_Type__c;
                 opplines.Amount=string.valueof(opp.Amount);
                 opplines.StageName=opp.SFS_Opp_Stage__c;
                 
                 opplines.ProductCategory=opp.Product_Category__c;
                 opplines.ProductSubCategory=opp.Product_Sub_Category__c;
                 
                 opplines.ForecastType=opp.Forecast_Type__c;
                 opplines.CloseDate=String.valueof(opp.CloseDate);
                 
                 opplines.CloseReason=opp.Closed_Reason__c;
                 opplines.OtherCloseReason=opp.Reason_Details_Other_Reason__c;
                 
                 opplines.Competitor=opp.Competitor__c;
                 opplines.OtherCompetitor=opp.Other_Competitor__c;
                 opplines.OppOwner=opp.TAA_Opportunity_Owner_Id__c ;
                 opplines.Name=opp.Name;
                 
                 
            
              setopps.add(opplines);
             
             }
             
             if(opp.SFS_PID__c!= oldRecordsMap.get(opp.Id).SFS_PID__c || opp.SFS_CID__c!= oldRecordsMap.get(opp.Id).SFS_CID__c){
             
                actpid.put(opp.AccountId,opp);
                 
             
             }
            
        }
       
       
         oput.opps =setopps;
         
         String strRequestParam = JSON.serialize(oput);
                
         system.debug('request json'+strRequestParam);
        
        try{         
        
          if(actpid.size()>0){
             
             for(Id aid : actpid.keyset()){
             
               Account a = new Account();
               a.id =aid;
               a.SFS_PID__c =actpid.get(aid).SFS_PID__c ;
               a.SFS_CID__c = actpid.get(aid).SFS_CID__c ;
               
               accountToupdate.add(a);
             }
          
          }
         try{ 
         if(accountToupdate.size()>0) Database.update(accountToupdate,false);
          }catch(Exception  ex){ }
         if(setopps.size()>0) SendInfo(strRequestParam,stsrttime,seconds);  
         S2S_OpportunityTriggerHandler.alreadyProcessed = true;
          }catch(Exception  ex){
          S2S_OpportunityTriggerHandler.alreadyProcessed = true;
          }
    } 
    
    
    
     @future(callout=true)
    public static void SendInfo(String Jsons,DateTime stsrttime,Integer seconds) {
    
        String Result;
        
        HttpResponse authres =OauthUtil.Authenticate('');
        HttpResponse res = new HttpResponse();
        HttpRequest req = new HttpRequest();
         try{
         
        system.debug('Auth request response'+authres.getStatusCode());
        
        
        
        if(authres.getStatusCode()==200){ 
            
        OauthUtil.OAuth2 objAuthenticationInfo = (OauthUtil.OAuth2)JSON.deserialize(authres.getbody(), OauthUtil.OAuth2.class);
       
        
        if(objAuthenticationInfo.access_token!=null){
        
        
          Http h = new Http();
          
          req.setHeader('Authorization','Bearer '+objAuthenticationInfo.access_token);
          req.setHeader('Content-Type','application/json');
          req.setHeader('accept','application/json');
          req.setTimeout(120000);
        
          req.setBody(Jsons);//Send JSON body
          req.setMethod('POST');
          if(!Test.isRunningTest()) { req.setEndpoint(objAuthenticationInfo.instance_url+'/services/apexrest/Opportunitysync'); } else {req.setEndpoint('http://fakeurl.com/services/oauth2/token');}
          res = h.send(req);
          system.debug('RESPONSE_BODY'+res.getStatusCode());
          String Error_message;
                       if(res.getStatusCode()==200){ 
                       
                       List<S2S_LogFile__c> logList = new List<S2S_LogFile__c>();   
              
             logList.add(S2S_Util.prepareLogEntry('Opp Sync',Jsons ,null,null,'TAA',res.getStatus(),res.getStatusCode(),stsrttime,seconds));
             
             if(!logList.isEmpty())
              Database.insert(logList, false);

                       }else{
                       
                       List<S2S_LogFile__c> logList = new List<S2S_LogFile__c>();   
              
             logList.add(S2S_Util.prepareLogEntry('Opp Sync',Jsons ,null,null,'TAA',res.getStatus(),res.getStatusCode(),stsrttime,seconds));
             
             if(!logList.isEmpty())
              Database.insert(logList, false);
                       }
               }else{
               
               List<S2S_LogFile__c> logList = new List<S2S_LogFile__c>();   
              
             logList.add(S2S_Util.prepareLogEntry('Opp Sync',Jsons ,null,null,'TAA',authres.getStatus(),authres.getStatusCode(),stsrttime,seconds));
             
             if(!logList.isEmpty())
              Database.insert(logList, false);
               
               
               }
           
           }else{
           
           List<S2S_LogFile__c> logList = new List<S2S_LogFile__c>();   
              
              logList.add(S2S_Util.prepareLogEntry('Opp Sync',Jsons ,null,null,'TAA',authres.getStatus(),authres.getStatusCode(),stsrttime,seconds));
              
             if(!logList.isEmpty())
              Database.insert(logList, false);
              
           
           
           }
     }catch(Exception ex){
   
           Result='Something Went wrong'+ex.getMessage()+ex.getLineNumber();
           system.debug('Resp String'+Result);
           
           List<S2S_LogFile__c> logList = new List<S2S_LogFile__c>();   
             
              logList.add(S2S_Util.prepareLogEntry('Opp Sync',Jsons ,null,null,'TAA',Result,500,stsrttime,seconds));
               
             
             if(!logList.isEmpty())
              Database.insert(logList, false);
            
              
           }
            
            
        }     
}