wk_taa_taaqa/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting Firms</fullName>
                </value>
                <value>
                    <fullName>Banks and Financial Institutions</fullName>
                </value>
                <value>
                    <fullName>Consultants</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Financial and Estate Planners</fullName>
                </value>
                <value>
                    <fullName>General Corporate</fullName>
                </value>
                <value>
                    <fullName>Hospital and Payers</fullName>
                </value>
                <value>
                    <fullName>Insurance Companies</fullName>
                </value>
                <value>
                    <fullName>Legal Professionals</fullName>
                </value>
                <value>
                    <fullName>Retail Tax Preparers</fullName>
                </value>
                <value>
                    <fullName>Schools and Libraries</fullName>
                </value>
                <value>
                    <fullName>State and Local Government</fullName>
                </value>
                <value>
                    <fullName>Tax Exempt and Membership Organizations</fullName>
                </value>
                <value>
                    <fullName>Agriculture &amp; Mining</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Banks and Financial</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Business Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Computers &amp; Electronics</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Consumer Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Education</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Fin</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Financial Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Government</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Healthcare, Pharmaceuticals, &amp; Biotech</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Hospital &amp; Payers</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Law Schools</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Legal Professional</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Media &amp; Entertainment</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/AccountAutomationSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AccountAutomationSetting</label>
</CustomObject>

wk_taa_taaqa/src/objects/Email_Preferences__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Email Preferences</relationshipLabel>
        <relationshipName>Email_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GOO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GOO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Email Preferences</relationshipLabel>
        <relationshipName>Email_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Email Preferences</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Email Preferences Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DTN__c</fullName>
        <formula>IF( Custodian__c , DTN_Text__c , Owner:User.DTN__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DTN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting Firms</fullName>
                </value>
                <value>
                    <fullName>Banks and Financial Institutions</fullName>
                </value>
                <value>
                    <fullName>Consultants</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Financial and Estate Planners</fullName>
                </value>
                <value>
                    <fullName>General Corporate</fullName>
                </value>
                <value>
                    <fullName>Hospital and Payers</fullName>
                </value>
                <value>
                    <fullName>Insurance Companies</fullName>
                </value>
                <value>
                    <fullName>Legal Professionals</fullName>
                </value>
                <value>
                    <fullName>Retail Tax Preparers</fullName>
                </value>
                <value>
                    <fullName>Schools and Libraries</fullName>
                </value>
                <value>
                    <fullName>State and Local Government</fullName>
                </value>
                <value>
                    <fullName>Tax Exempt and Membership Organizations</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>DTN__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>External Id for User</inlineHelpText>
        <label>DTN</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/Test_PreferenceCenter.cls
/*
    ###########################################################################
    # File..................: Class - Test_PreferenceCenter
    # Created by............: The Hunley Group
    # Created Date..........: 1/1/2016
    # Description...........: Class used to test both the class PreferenceCenterController
                                and the trigger EmailPrefInsertUpdateRelated.
    ########################################################################### */
@isTest(seeAllData=false)
private class Test_PreferenceCenter {
    static testMethod void Test_PreferenceCenter(){
        Account a = new Account(Name='testaccount');
        insert a;
        Contact c = new Contact(LastName='testcontact',AccountId=a.Id,HasOptedOutOfEmail=false);
        insert c;
        /*User u1 = TestDataFactory.newUser('2221',1);
        String  = [Select id,Name,DTN__c from user where DTN__c='222a'].Name;
        AccountAutomationSetting__c taa = TestDataFactory.newTaaCustomSetting(username);*/
        Lead l = new Lead(LastName='testlead',Company='test company',Status='Not Started',Market_Segment__c='General Corporate',HasOptedOutOfEmail=false);
        insert l;
        List<Email_Preferences__c> emailprefsList = new List<Email_Preferences__c>();
        List<Contact> contactsList = new List<Contact>();
        List<Lead> leadsList = new List<Lead>();
        
        test.startTest();
        
        PageReference wk_pref_page = Page.WK_Pref_Center;
        Test.setCurrentPage( wk_pref_page );
        
        //test contact scenario
        ApexPages.currentPage().getParameters().put( 'Id', c.id );
        PreferenceCenterController controller = new PreferenceCenterController();
        controller.getRandom();
        controller.LastName = 'testcontact';
        controller.GOO = true;
        controller.quickSave();
        
        //test to make sure email preference record is created
        emailprefslist = [
        SELECT Id, LastName__c, Contact__c, GOO__c
        FROM Email_Preferences__c
        WHERE Contact__c = :c.Id
        ];
        System.assertEquals(emailprefsList[0].Contact__c, c.Id);
        System.assertEquals(emailprefsList[0].LastName__c, controller.LastName);
        System.assertEquals(emailprefsList[0].GOO__c, controller.GOO);

        //test to make sure contact record is updated
        contactslist = [
        SELECT Id, LastName, HasOptedOutOfEmail
        FROM Contact
        WHERE Id = :c.Id
        ];
        System.assertEquals(contactslist[0].LastName, controller.LastName);
        //test lead scenario
        ApexPages.currentPage().getParameters().put( 'Id', l.id );
        controller = new PreferenceCenterController();
        controller.LastName = 'testlead';
        controller.GOO = true;
        controller.quickSave();
        
        //test to make sure email preference record is created
        emailprefslist = [
        SELECT Id, LastName__c, Lead__c, GOO__c
        FROM Email_Preferences__c
        WHERE Lead__c = :l.Id
        ];
        System.assertEquals(emailprefsList[0].Lead__c, l.Id);
        System.assertEquals(emailprefsList[0].LastName__c, controller.LastName);
        System.assertEquals(emailprefsList[0].GOO__c, true);

        //test to make sure lead record is updated
        leadslist = [
        SELECT Id, LastName, HasOptedOutOfEmail
        FROM Lead
        WHERE Id = :l.Id
        ];
        System.assertEquals(leadslist[0].LastName,'testlead');
        System.assertEquals(leadslist[0].HasOptedOutOfEmail,true);

        test.stopTest();
    }
}