wk_taa_taaqa/src/objects/AccountAutomationSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AccountAutomationSetting</label>
</CustomObject>

wk_taa_taaqa/src/objects/Custodial__c.object
<CustomObject>
    <description>Custody of Accounts if already existing representatives are switching.</description>
    <fields>
        <fullName>DTN_Current_Rep__c</fullName>
        <inlineHelpText>Current Rep DTN</inlineHelpText>
        <label>DTN Current Rep</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DTN_Custodial_Rep__c</fullName>
        <inlineHelpText>Dtns of Custodial representative</inlineHelpText>
        <label>DTN Custodial Rep</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DTN_new_Rep__c</fullName>
        <inlineHelpText>Dtn of New representative</inlineHelpText>
        <label>DTN new Rep</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Custodial</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Custodial Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custodials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Custodian__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Custodian</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DTN__c</fullName>
        <formula>IF( Custodian__c , DTN_Text__c , Owner:User.DTN__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DTN</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/TAACustomSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>TAA Hierarchical custom setting</description>
    <label>TAA CustomSetting</label>
</CustomObject>

wk_taa_taaqa/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>DTN__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>External Id for User</inlineHelpText>
        <label>DTN</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/TestCustodialLeadBatch.cls
/**
 * This class contains unit tests for validating the behavior of
 *Apex class : CustodialLeadBatch
 */
@isTest(SeeAllData=false)
private class TestCustodialLeadBatch {
   
    
      static testmethod void testleadnewRep(){
        User u1 = TestDataFactory.newUser('111a',1);
        User u2 = TestDataFactory.newUser('111b',2);
        String username = [Select id,Name,DTN__c from user where DTN__c='111a'].Name;
     // TAACustomSetting__c taa = TestDataFactory.newTaaCustomSetting(username);
        AccountAutomationSetting__c taa = TestDataFactory.newTaaCustomSetting(username);
        list<Lead>leads = new list<Lead>();
        leads.add(TestDataFactory.newLead('Test1'));
        leads.add(TestDataFactory.newLead('Test2'));
        leads.add(TestDataFactory.newLead('Test3'));
        for(Lead l : leads){
           //Lead l= leads[0];
            l.ownerId= u1.id;
          }  
        update leads;
        System.debug('>>>>>>>Lead List<<<<<<<<'+leads);
        System.debug('>>>>>>User Info<<<<<<'+u1 + u2);
        String DTN_Current_Rep=u1.DTN__c;
        String DTN_new_Rep=u2.DTN__c;
        String q = 'Select id,Name,OwnerID,IsConverted from Lead' /*where OwnerId like'+'\'%'+u1.id+'%'+'\' Limit 200'*/;
        System.debug('<<<<Query Called>>>>>>'+q);
        Custodial__c cust= new Custodial__c();
        cust.DTN_Current_Rep__c=DTN_Current_Rep;
        cust.DTN_new_Rep__c=DTN_new_Rep;
        insert cust;
        
        Test.starttest();
        CustodialLeadBatch clb= new CustodialLeadBatch(cust.id,DTN_Current_Rep,DTN_new_Rep,q,null);
        Database.executebatch(clb,200);
        Test.stoptest();
        List<Lead>leadlist= [Select Id,Name,custodian__C,OwnerId from Lead where OwnerID=:u2.Id];
        //System.assert(leadlist.size()>0);
        //System.assertequals(leadlist[0].custodian__C ,false);
        //System.assertequals(leadlist[0].OwnerId,u2.Id);
        List<Lead>leadlist2= [Select Id,Name,custodian__C,OwnerId from Lead where OwnerID=:u1.Id];
        System.assert(leadlist2.size()==0);
      }
      static testmethod void testleadcustodialRep(){
    
           User u1 = TestDataFactory.newUser('111a',1);
        User u2 = TestDataFactory.newUser('111b',2);
        String username = [Select id,Name,DTN__c from user where DTN__c='111a'].Name;
        //TAACustomSetting__c taa = TestDataFactory.newTaaCustomSetting(username );
        AccountAutomationSetting__c taa = TestDataFactory.newTaaCustomSetting(username);
        list<Lead>leads = new list<Lead>();
        leads.add(TestDataFactory.newLead('Test1'));
        leads.add(TestDataFactory.newLead('Test2'));
        leads.add(TestDataFactory.newLead('Test3'));
        for(Lead l : leads){
           //Lead l= leads[0];
            l.ownerId= u1.id;
          }  
        update leads;
        String DTN_Current_Rep=u1.DTN__c;
        String DTN_custodial_Rep=u2.DTN__c;
         String q = 'Select id,Name,OwnerID,IsConverted from Lead' /*where OwnerId like'+'\'%'+u1.id+'%'+'\' Limit 200'*/;
        Custodial__c cust= new Custodial__c();
        cust.DTN_Current_Rep__c=DTN_Current_Rep;
        cust.DTN_custodial_Rep__c=DTN_custodial_Rep;
        insert cust;
        CustodialLeadBatch clb= new CustodialLeadBatch(cust.id,DTN_Current_Rep,null,q,DTN_custodial_Rep);
        Test.starttest();
        Database.executebatch(clb,200);
        Test.stoptest();
        List<Lead>leadlist= [Select Id,Name,custodian__C,OwnerId from Lead where OwnerID=:u2.Id];
        //System.assert(leadlist.size()>0);
        //System.assertequals(leadlist[0].custodian__C ,true);
        //System.assertequals(leadlist[0].OwnerId,u2.Id);
        List<Lead>leadlist2= [Select Id,Name,custodian__C,OwnerId from Lead where OwnerID=:u1.Id];
        System.assert(leadlist2.size()==0);
      }
       static testmethod void testException(){
        
        User u1 = TestDataFactory.newUser('111a',1);
        User u2 = TestDataFactory.newUser('111b',2);
        String username = [Select id,Name,DTN__c from user where DTN__c='111a'].Name;
        //TAACustomSetting__c taa = TestDataFactory.newTaaCustomSetting(username );
         AccountAutomationSetting__c taa = TestDataFactory.newTaaCustomSetting(username);
        list<Lead>leads = new list<Lead>();
        //List<sObject> ls = Test.loadData(Lead.sObjectType, 'testdatalead');
        leads.add(TestDataFactory.newLead('Test1'));
        leads.add(TestDataFactory.newLead('Test2'));
        leads.add(TestDataFactory.newLead('Test3'));
        for(Lead l : leads){
           //Lead l= leads[0];
            l.ownerId= u1.id;
          }  
        update leads;
        String DTN_Current_Rep=u1.DTN__c;
        String DTN_custodial_Rep=u2.DTN__c;
         String q = 'Select id,Name,OwnerID,IsConverted from Lead' /*where OwnerId like'+'\'%'+u1.id+'%'+'\' Limit 200'*/;
        Custodial__c cust= new Custodial__c();
        cust.DTN_Current_Rep__c=DTN_Current_Rep;
        cust.DTN_custodial_Rep__c=DTN_custodial_Rep;
        insert cust;
        CustodialLeadBatch clb= new CustodialLeadBatch(cust.id,'7777',null,q,'6666');
        Test.starttest();
        Database.executebatch(clb,200);
        Test.stoptest();
        List<Lead>leadlist= [Select Id,Name,custodian__C,OwnerId from Lead where OwnerID=:u2.Id];
        System.assert(leadlist.size()==0);
        //System.assertequals(leadlist[0].custodian__C ,false);
       // System.assertequals(leadlist[0].OwnerId,u1.Id);
        List<Lead>leadlist2= [Select Id,Name,custodian__C,OwnerId from Lead where OwnerID=:u1.Id];
        //System.assert(leadlist2.size()>0);
      }
      
   }