wk_taa_taaqa/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Professional_Software_Revenue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Professional Software Revenue</label>
        <referenceTo>Professional_Software_Revenue__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Professional_Software_Revenue__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Professional_Software_Revenues</relationshipLabel>
        <relationshipName>Professional_Software_Revenues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SFDC_ACCTID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SFDC ACCTID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>X2016_Tax_Software__c</fullName>
        <label>2016 Tax Software</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Professional Software Revenue</label>
    <nameField>
        <label>Professional Software Revenue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Professional_Software_Revenues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/ProSoftRevControllerTest.cls
@isTest 
public class ProSoftRevControllerTest{
 
     Public static  testMethod void ProSoftRevControllerTest()
          {
       
Account acc = new Account(
            Name = 'myAcct', 
            BillingStreet='25 Upland Drive',
            BillingPostalCode='94127',
            BillingCountry='United States',
            BillingCity='San Francisco' );
        insert acc;

professional_software_revenue__c PR = new professional_software_revenue__c(
account__c = acc.Id,sfdc_acctid__c = acc.Id, x2016_tax_software__c = 2500.00);
insert PR;
     

    
                 PageReference pageRef = Page.ProfessionalSoftwareRevenue;
                                                                             
                 pageRef.getParameters().put('Id',acc.Id);
                 Test.setCurrentPage(pageRef);
                 
                  ProSoftRevController  ps = new ProSoftRevController();
            ps.GetRevenue();
             
             

            
          
                 

        
     }
}