wk_taa_taaqa/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting Firms</fullName>
                </value>
                <value>
                    <fullName>Banks and Financial Institutions</fullName>
                </value>
                <value>
                    <fullName>Consultants</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Financial and Estate Planners</fullName>
                </value>
                <value>
                    <fullName>General Corporate</fullName>
                </value>
                <value>
                    <fullName>Hospital and Payers</fullName>
                </value>
                <value>
                    <fullName>Insurance Companies</fullName>
                </value>
                <value>
                    <fullName>Legal Professionals</fullName>
                </value>
                <value>
                    <fullName>Retail Tax Preparers</fullName>
                </value>
                <value>
                    <fullName>Schools and Libraries</fullName>
                </value>
                <value>
                    <fullName>State and Local Government</fullName>
                </value>
                <value>
                    <fullName>Tax Exempt and Membership Organizations</fullName>
                </value>
                <value>
                    <fullName>Agriculture &amp; Mining</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Banks and Financial</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Business Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Computers &amp; Electronics</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Consumer Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Education</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Fin</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Financial Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Government</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Healthcare, Pharmaceuticals, &amp; Biotech</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Hospital &amp; Payers</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Law Schools</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Legal Professional</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Media &amp; Entertainment</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Sub_Segment__c</fullName>
        <label>SubSegment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market_Segment__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sole Proprietor</fullName>
                </value>
                <value>
                    <fullName>2-4 Total Employees</fullName>
                </value>
                <value>
                    <fullName>5-9 Total Employees</fullName>
                </value>
                <value>
                    <fullName>10-19 Total Employees</fullName>
                </value>
                <value>
                    <fullName>20-49 Total Employees</fullName>
                </value>
                <value>
                    <fullName>50-99 Total Employees</fullName>
                </value>
                <value>
                    <fullName>100+ Total Employees</fullName>
                </value>
                <value>
                    <fullName>Top 100 Firms</fullName>
                </value>
                <value>
                    <fullName>Global Enterprise</fullName>
                </value>
                <value>
                    <fullName>Large Enterprise</fullName>
                </value>
                <value>
                    <fullName>Mid Enterprise</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                </value>
                <value>
                    <fullName>Small</fullName>
                </value>
                <value>
                    <fullName>Dept of Agriculture</fullName>
                </value>
                <value>
                    <fullName>Dept of Commerce</fullName>
                </value>
                <value>
                    <fullName>Dept of Defense</fullName>
                </value>
                <value>
                    <fullName>Dept of Energy</fullName>
                </value>
                <value>
                    <fullName>Dept of Health and Human Services</fullName>
                </value>
                <value>
                    <fullName>Dept of Homeland Security</fullName>
                </value>
                <value>
                    <fullName>Dept of Housing and Urban Development</fullName>
                </value>
                <value>
                    <fullName>Dept of Interior</fullName>
                </value>
                <value>
                    <fullName>Dept of Justice</fullName>
                </value>
                <value>
                    <fullName>Dept of Labor</fullName>
                </value>
                <value>
                    <fullName>Dept of State</fullName>
                </value>
                <value>
                    <fullName>Dept of Treasury (not IRS)</fullName>
                </value>
                <value>
                    <fullName>Dept of Vet Affairs</fullName>
                </value>
                <value>
                    <fullName>EEOC</fullName>
                </value>
                <value>
                    <fullName>Exec Branch (White House)</fullName>
                </value>
                <value>
                    <fullName>FCC</fullName>
                </value>
                <value>
                    <fullName>FDIC</fullName>
                </value>
                <value>
                    <fullName>Size TBD</fullName>
                </value>
                <value>
                    <fullName>Law Firm 1-3 Attorneys</fullName>
                </value>
                <value>
                    <fullName>Law Firms (Size TBD)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Market_Sub_Segment__c</fullName>
        <label>SubSegment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Segment__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sole Proprietor</fullName>
                </value>
                <value>
                    <fullName>2-4 Total Employees</fullName>
                </value>
                <value>
                    <fullName>5-9 Total Employees</fullName>
                </value>
                <value>
                    <fullName>10-19 Total Employees</fullName>
                </value>
                <value>
                    <fullName>20-49 Total Employees</fullName>
                </value>
                <value>
                    <fullName>50-99 Total Employees</fullName>
                </value>
                <value>
                    <fullName>100+ Total Employees</fullName>
                </value>
                <value>
                    <fullName>Top 100 Firms</fullName>
                </value>
                <value>
                    <fullName>Global Enterprise</fullName>
                </value>
                <value>
                    <fullName>Large Enterprise</fullName>
                </value>
                <value>
                    <fullName>Mid Enterprise</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                </value>
                <value>
                    <fullName>Small</fullName>
                </value>
                <value>
                    <fullName>Dept of Agriculture</fullName>
                </value>
                <value>
                    <fullName>Dept of Commerce</fullName>
                </value>
                <value>
                    <fullName>Dept of Defense</fullName>
                </value>
                <value>
                    <fullName>Dept of Energy</fullName>
                </value>
                <value>
                    <fullName>Dept of Health and Human Services</fullName>
                </value>
                <value>
                    <fullName>Dept of Homeland Security</fullName>
                </value>
                <value>
                    <fullName>Dept of Housing and Urban Development</fullName>
                </value>
                <value>
                    <fullName>Dept of Interior</fullName>
                </value>
                <value>
                    <fullName>Dept of Justice</fullName>
                </value>
                <value>
                    <fullName>Dept of Labor</fullName>
                </value>
                <value>
                    <fullName>Dept of State</fullName>
                </value>
                <value>
                    <fullName>Dept of Treasury (not IRS)</fullName>
                </value>
                <value>
                    <fullName>Dept of Vet Affairs</fullName>
                </value>
                <value>
                    <fullName>EEOC</fullName>
                </value>
                <value>
                    <fullName>Exec Branch (White House)</fullName>
                </value>
                <value>
                    <fullName>FCC</fullName>
                </value>
                <value>
                    <fullName>FDIC</fullName>
                </value>
                <value>
                    <fullName>Size TBD</fullName>
                </value>
                <value>
                    <fullName>Law Firm 1-3 Attorneys</fullName>
                </value>
                <value>
                    <fullName>Law Firms (Size TBD)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFS_Contact_Record_ID__c</fullName>
        <externalId>true</externalId>
        <label>SFS Contact Record ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/TSM_Custom_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>TSM custom settings for configuration</description>
    <fields>
        <fullName>ConnectionName__c</fullName>
        <label>ConnectionName</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>TSM_Custom_Settings</label>
</CustomObject>

wk_taa_taaqa/src/classes/TSM_ContactTriggerHandler.cls
/*
 * trigger handler class to perform the S2S records replication from TAA org to SFS org  
*/
/*--------------------------------------------------------------------------
 * Date       Author            Version      Description
 * -------------------------------------------------------------------------
 * 11/29/2016 Raj				1.0			Initial draft
 * ------------------------------------------------------------------------- */
public class TSM_ContactTriggerHandler {
    public static void onAfterInsert(List<Contact> newRecords) {
        TSM_Custom_Settings__c tsmCS = TSM_Custom_Settings__c.getInstance();		
        Id networkId = TSM_Util.getNetworkId(tsmCS.ConnectionName__c);        
        List<PartnerNetworkRecordConnection> newContShrList = new List<PartnerNetworkRecordConnection>();
		Map<Id, PartnerNetworkRecordConnection> acctShrMap = new Map<Id, PartnerNetworkRecordConnection>();                
        Map<Id, PartnerNetworkRecordConnection> contShrMap = new Map<Id, PartnerNetworkRecordConnection>();                
        Map<Id, Contact> contactMap = new Map<Id, Contact>();
        Set<Id> acctIds = new Set<Id>();
        Map<Id, Account> acctMap = new Map<Id, Account>();
        // preparing the list of account ids
        for(Contact con: newRecords) {
            if(con.ConnectionReceivedId == null && con.SFS_Contact_Record_Id__c == null && con.AccountId != null) {
            	acctIds.add(con.AccountId);
            }
        }
        // fetch the parent accounts of SFS by using account segment and subsegment attributes
        for(Account acct: [SELECT Id, Market_Segment__c, Market_Sub_Segment__c FROM Account WHERE Id IN :acctIds
                          AND Market_Segment__c IN :TSM_Util.getAccountSegments().keySet()]) {
            if(acct.Market_Segment__c == 'Legal Professionals' && acct.Market_Sub_Segment__c != null &&
                      (acct.Market_Sub_Segment__c == 'Law Firm 1-3 Attorneys' || acct.Market_Sub_Segment__c == 'Law Firms (Size TBD)')) {
                    	acctMap.put(acct.Id, acct);   
            } else if (acct.Market_Segment__c != 'Legal Professionals' && acct.Market_Sub_Segment__c != null && 
                       // for segment = other 3 types
                       (acct.Market_Sub_Segment__c == 'Sole Proprietor' || 
                        acct.Market_Sub_Segment__c == '2-4 Total Employees' || 
                        acct.Market_Sub_Segment__c == 'Size TBD')) {
                        acctMap.put(acct.Id, acct);
            }
        }
        // for identifying the contacts which must be replicated thru SFS
        for(Contact con: newRecords) {
            if(con.ConnectionReceivedId == null && con.SFS_Contact_Record_Id__c == null &&
               con.AccountId != null && acctMap.containsKey(con.AccountId)) {
            	contactMap.put(con.Id, con);
            }
        }
        // for fetching the existing shares of respective contacts
        contShrMap = TSM_Util.fetchExistingShares(contactMap.keySet(), networkId); 
        // for fetching the existing shares of respective accounts
        //acctShrMap = TSM_Util.fetchExistingShares(acctMap.keySet(), networkId);
        // for comparing the share entries with new contacts
        for(Contact con: contactMap.values()) {
            if(!contShrMap.containsKey(con.Id)) {
                newContShrList.add(TSM_Util.prepareShare(con.Id, networkId, null));
                /*
                if(con.AccountId != null  && acctShrMap.containsKey(con.AccountId)) 
                    // for respective account PNRC entries are active
                	newContShrList.add(TSM_Util.prepareShare(con.Id, networkId, con.AccountId)); 
                else 
                    // for respective account PNRC entries are inactive
                    newContShrList.add(TSM_Util.prepareShare(con.Id, networkId, null));
				*/
            } 
        }
        
        // #Deprecated :SMS - 752 This method is replaced by insertSharesObject which allows replication Logging
        //TSM_Util.insertShares(newContShrList, 'TSM_ContactTrigger','Trigger');
        
        // insert the new shares bulk
        // SMS - 752 :InsertShares method is replaced by insertSharesObject which is Returning IDs of pertnerNetworkRecordConnection.
        List<String> contactShareObjectListIds = TSM_Util.insertSharesObject(newContShrList, 'TSM_OpportunityTrigger', 'Trigger');
        if(contactShareObjectListIds.size()>0){
        	TSM_Util.insertReplicationMonitoringLog(contactShareObjectListIds,'Contact');
        } 
        //SMS -752 :End
    }
}