wk_taa_taaqa/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Corp_Direct__c</fullName>
        <label>Corp Direct DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_Indirect__c</fullName>
        <label>Corp Indirect DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISR_Indirect__c</fullName>
        <label>ISR Indirect</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting Firms</fullName>
                </value>
                <value>
                    <fullName>Banks and Financial Institutions</fullName>
                </value>
                <value>
                    <fullName>Consultants</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Financial and Estate Planners</fullName>
                </value>
                <value>
                    <fullName>General Corporate</fullName>
                </value>
                <value>
                    <fullName>Hospital and Payers</fullName>
                </value>
                <value>
                    <fullName>Insurance Companies</fullName>
                </value>
                <value>
                    <fullName>Legal Professionals</fullName>
                </value>
                <value>
                    <fullName>Retail Tax Preparers</fullName>
                </value>
                <value>
                    <fullName>Schools and Libraries</fullName>
                </value>
                <value>
                    <fullName>State and Local Government</fullName>
                </value>
                <value>
                    <fullName>Tax Exempt and Membership Organizations</fullName>
                </value>
                <value>
                    <fullName>Agriculture &amp; Mining</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Banks and Financial</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Business Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Computers &amp; Electronics</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Consumer Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Education</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Fin</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Financial Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Government</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Healthcare, Pharmaceuticals, &amp; Biotech</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Hospital &amp; Payers</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Law Schools</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Legal Professional</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Media &amp; Entertainment</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NAM_SAM_CNAM__c</fullName>
        <label>NAM/SAM/CNAM DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_SW_FSR__c</fullName>
        <label>Pro SW RSC DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_ASR__c</fullName>
        <label>R&amp;L RC DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_FSR__c</fullName>
        <label>R&amp;L RSC DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SW_ASR__c</fullName>
        <label>SW RC DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Source__c</fullName>
        <label>Service Source DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Assignment_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>ASR_Indirect_Corp_Software__c</fullName>
        <description>ASR Indirect (Corp Software)</description>
        <inlineHelpText>ASR Indirect (Corp Software)</inlineHelpText>
        <label>ASR Indirect (Corp Software)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_Direct__c</fullName>
        <inlineHelpText>FSR - Direct (Corp Software)</inlineHelpText>
        <label>Corp Direct</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_Indirect__c</fullName>
        <inlineHelpText>FSR - Indirect (Corp Sotware)</inlineHelpText>
        <label>Corp Indirect</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISR_Indirect__c</fullName>
        <inlineHelpText>ISR - Indirect (Corp Software)</inlineHelpText>
        <label>ISR Indirect</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <inlineHelpText>Market Sub-Segment</inlineHelpText>
        <label>Market Segment</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAM_SAM_CNAM__c</fullName>
        <inlineHelpText>NAM- National Account Manager, SAM-Strategic Account Manager, CNAM-Corporate Account Manager</inlineHelpText>
        <label>NAM/SAM/CNAM</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NAM - National Accounts</fullName>
                </value>
                <value>
                    <fullName>SAM - Strategic Account Manager</fullName>
                </value>
                <value>
                    <fullName>CAM - Corporate Account Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pro_SW_FSR__c</fullName>
        <inlineHelpText>FSR- Professional Sotware</inlineHelpText>
        <label>Pro SW FSR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_SW_ISR__c</fullName>
        <inlineHelpText>ISR - Professional Software</inlineHelpText>
        <label>Pro SW ISR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_ASR__c</fullName>
        <inlineHelpText>ASR - Research and Learning</inlineHelpText>
        <label>R&amp;L ASR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_FSR__c</fullName>
        <inlineHelpText>FSR - Research and Learning</inlineHelpText>
        <label>R&amp;L FSR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SW_ASR__c</fullName>
        <inlineHelpText>ASR - Professional Software</inlineHelpText>
        <label>SW ASR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Source__c</fullName>
        <inlineHelpText>ASR - R&amp;L - Service Source</inlineHelpText>
        <label>Service Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assignment Matrix</label>
    <nameField>
        <label>Assignment Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Matrixs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Corporate_National_Role_DTN__c.object
<CustomObject>
    <description>Corporate National Accounts Named Account Type Corporate National</description>
    <fields>
        <fullName>DTN__c</fullName>
        <description>Division Territory Number</description>
        <label>DTN</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>Corporate National Role-DTN</label>
    <nameField>
        <displayFormat>CNA-{000}</displayFormat>
        <label>Corp National Role-DTN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corporate National Role-DTN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/National_Account_Management__c.object
<CustomObject>
    <description>Defines the National Account Management Role for Named Accounts with Named Account Type = National</description>
    <fields>
        <fullName>DTN__c</fullName>
        <label>DTN</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>National Account Management</label>
    <nameField>
        <displayFormat>NAM-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Account Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/ServiceSource_Role_DTN__c.object
<CustomObject>
    <fields>
        <fullName>DTN__c</fullName>
        <label>DTN</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>ServiceSource Role DTN</label>
    <nameField>
        <displayFormat>SS-{000}</displayFormat>
        <label>ServiceSource Role DTN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ServiceSource Role DTNs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Strategic_Account_RoleDTN__c.object
<CustomObject>
    <description>Defines the Strategic Account Roles of Strategic Account Manager (SAM) and Solution Architect (SA) Per DTN</description>
    <fields>
        <fullName>DTN__c</fullName>
        <label>DTN</label>
        <length>7</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Strategic Account Role-DTN</label>
    <nameField>
        <displayFormat>SAM-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Account RoleDTN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>DTN__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>External Id for User</inlineHelpText>
        <label>DTN</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/ZipCodeDTN__c.object
<CustomObject>
    <fields>
        <fullName>ASR_Indirect_Corp_Software__c</fullName>
        <description>ASR Indirect (Corp Software)</description>
        <inlineHelpText>ASR Indirect (Corp Software)</inlineHelpText>
        <label>ASR Indirect (Corp Software)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_Direct__c</fullName>
        <inlineHelpText>FSR - Direct (Corp Software)</inlineHelpText>
        <label>Corp Direct</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_Indirect__c</fullName>
        <inlineHelpText>FSR - Indirect (Corp Sotware)</inlineHelpText>
        <label>Corp Indirect</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISR_Indirect__c</fullName>
        <inlineHelpText>ISR - Indirect (Corp Software)</inlineHelpText>
        <label>ISR Indirect</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAM_SAM_CNAM__c</fullName>
        <inlineHelpText>CNAM-Corporate Account Manager, SAM-Strategic Account Manager, CNAM-Corporate Account Manager</inlineHelpText>
        <label>NAM/SAM/CNAM</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_SW_FSR__c</fullName>
        <inlineHelpText>FSR- Professional Sotware</inlineHelpText>
        <label>Pro SW FSR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_SW_ISR__c</fullName>
        <inlineHelpText>ISR - Professional Software</inlineHelpText>
        <label>Pro SW ISR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_ASR__c</fullName>
        <inlineHelpText>ASR - Research and Learning</inlineHelpText>
        <label>R&amp;L ASR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_FSR__c</fullName>
        <inlineHelpText>FSR - Research and Learning</inlineHelpText>
        <label>R&amp;L FSR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SW_ASR__c</fullName>
        <inlineHelpText>ASR - Professional Software</inlineHelpText>
        <label>SW ASR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Source__c</fullName>
        <inlineHelpText>ASR - R&amp;L - Service Source</inlineHelpText>
        <label>Service Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Zip Code DTN</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes DTN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/TestAccountTrigger.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
 
//@isTest(SeeAllData = false)
public class TestAccountTrigger {/*
    static void setup(){
        list<ZipCodeDTN__c>zipCodeDTNlist = new list<ZipCodeDTN__c>();
        list<Assignment_Matrix__c>assignmentMatrix = new list<Assignment_Matrix__c>();
        
        zipCodeDTNlist.add(TestDataFactory.zipCodeDtn('55555', '2111', '2112'));
        zipCodeDTNlist.add(TestDataFactory.zipCodeDtn('66666', '2113', '2114'));
        zipCodeDTNlist.add(TestDataFactory.zipCodeDtn('wrongDTN', '2220', '2221'));
        ZipCodeDTN__c z = TestDataFactory.zipCodeDtn('77777', '2220', '2221');
        
        z.ASR_Indirect_Corp_Software__c='2111';
        z.Corp_Direct__c = '2112';
        z.Corp_Indirect__c = '2113';
        z.ISR_Indirect__c = '2114';
        z.NAM_SAM_CNAM__c = '2115';
        z.Pro_SW_FSR__c = '2116';
        z.Pro_SW_ISR__c = '2117';
        z.R_L_ASR__c = '2118';
        z.R_L_FSR__c = '2119';
        z.Service_Source__c = '2110';
        //z.SW_ASR__c = '2222';
        update z;
        zipCodeDTNlist.add(z);
        
        //Assignment Matrixes
        assignmentMatrix.add(TestDataFactory.assignmentMatrixWithAF('Accounting Firms','5-9 Total Employees'));
        assignmentMatrix.add(TestDataFactory.assignmentMatrixWithLessRolls('Legal Professionals','Law Firm 1-3 Attorneys'));
        assignmentMatrix.add(TestDataFactory.assignmentMatrixWithAF('Schools and Libraries','All'));
        assignmentMatrix.add(TestDataFactory.assignmentMatrixWithAF('Banks and Financial Institutions','All'));
        assignmentMatrix.add(TestDataFactory.assignmentMatrixForNamedAccount('Named Corp Nat','Corp','Corporate National','CAM - Corporate Account Manager'));
        assignmentMatrix.add(TestDataFactory.assignmentMatrixForNamedAccount('Named Accounts','National','National','NAM - National Accounts'));
        assignmentMatrix.add(TestDataFactory.assignmentMatrixForNamedAccount('Named Accounts','Strategic','Strategic','SAM - Strategic Account Manager'));
        
        //Users
        User u1 = TestDataFactory.newUser('2111',1);
        User u2 = TestDataFactory.newUser('2112',2);
        User u3 = TestDataFactory.newUser('2113',3);
        User u4 = TestDataFactory.newUser('2114',4);
        User u5 = TestDataFactory.newUser('2115',5);
        User uSAM = TestDataFactory.newUser('2116',6);
        User uSA = TestDataFactory.newUser('2117',7);
        User uCNAM = TestDataFactory.newUser('2118',8);
        User uNAM = TestDataFactory.newUser('2119',9);
        
        //Custom Settings
        String username = [Select id,Name,DTN__c from user where DTN__c='2115'].Name;
        AccountAutomationSetting__c taa = TestDataFactory.newTaaCustomSetting(username);
        
        //Named Accounts
        Strategic_Account_RoleDTN__c sam = TestDataFactory.newSAR('DemoSAM','2116',uSA,uSAM);
        Corporate_National_Role_DTN__c cnr = TestDataFactory.newCNR('DemoCNR', uCNAM, '2118');
        National_Account_Management__c nam = TestDataFactory.newNAM('DemoNAM', '2119', uNAM);
        ServiceSource_Role_DTN__c ss= TestDataFactory.newSS('DemoSS','2117',uSA);
        
    }
    static testMethod void CreateAccountTeamMembersTest() {
        setup();
        list<Account> toInsertAccounts = new list<Account>();
        for(Integer i=0 ; i<5000 ;i++){
            Account a = new Account();
            a.Name = 'TestAccount'+ '-'+i;
            a.BillingPostalCode = 'wrongDTN';
            a.Market_Segment__c = 'Accounting Firms';
            a.Market_Sub_Segment__c = '5-9 Total Employees';
            
            toInsertAccounts.add(a);
        }
        insert toInsertAccounts;
    }
    */
}