wk_taa_taaqa/src/objects/Account_X_Reference__c.object
<CustomObject>
    <fields>
        <fullName>AMS_Renewal_Email__c</fullName>
        <label>AMS Renewal Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AMS_renewal_Contact__c</fullName>
        <label>AMS renewal Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account X-Reference</relationshipLabel>
        <relationshipName>Account_X_Reference</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ApplicationID__c</fullName>
        <externalId>true</externalId>
        <label>Application ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS</fullName>
                </value>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>SFS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X2017_AMS_Additional_Discount__c</fullName>
        <label>2017 AMS Additional Discount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account X-Reference</label>
    <nameField>
        <label>Account X-Reference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account X-Reference</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AMS_Renewal_Contact__c</fullName>
        <label>AMS Renewal Contact Override</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AMS_Renewal_Email__c</fullName>
        <label>AMS Renewal Email Override</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Account_X_Reference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account X-Reference</label>
        <referenceTo>Account_X_Reference__c</referenceTo>
        <relationshipLabel>Opportunities (Account X-Reference)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_AMS_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is AMS Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Software</fullName>
                </value>
                <value>
                    <fullName>Med/Large Software</fullName>
                </value>
                <value>
                    <fullName>Small Firm Software</fullName>
                </value>
                <value>
                    <fullName>Research &amp; Learning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <label>Product Sub-Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Product_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Specialty</fullName>
                </value>
                <value>
                    <fullName>iFirm</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Autoflow</fullName>
                </value>
                <value>
                    <fullName>Refunds Today</fullName>
                </value>
                <value>
                    <fullName>SFS Research &amp; Learning</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>AnswerConnect</fullName>
                </value>
                <value>
                    <fullName>Core Library - Corporate Tax</fullName>
                </value>
                <value>
                    <fullName>Core Library - CPA Professional</fullName>
                </value>
                <value>
                    <fullName>Federal Add On</fullName>
                </value>
                <value>
                    <fullName>State Add On</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Certificate Programs</fullName>
                </value>
                <value>
                    <fullName>Seminars</fullName>
                </value>
                <value>
                    <fullName>Books</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Database/Lookups/RADAR</fullName>
                </value>
                <value>
                    <fullName>POS Portal</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Sales Tax Load Utilities</fullName>
                </value>
                <value>
                    <fullName>Sales Tax Returns</fullName>
                </value>
                <value>
                    <fullName>Sales Tax SaaS Core</fullName>
                </value>
                <value>
                    <fullName>STO</fullName>
                </value>
                <value>
                    <fullName>SureTax - General</fullName>
                </value>
                <value>
                    <fullName>SureTax Professional Services</fullName>
                </value>
                <value>
                    <fullName>SureTax - Telco/Energy</fullName>
                </value>
                <value>
                    <fullName>Tax Interchange for Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X2017_AMS_Additional_Discount__c</fullName>
        <label>2017 AMS Additional Discount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/TestUpdate_X_Reference.cls
@isTest 
private class TestUpdate_X_Reference {

    static testMethod void Update_X_Reference() {
      
      Account acc = new Account(
            Name = 'myAcct', 
            BillingStreet='25 Upland Drive',
            BillingPostalCode='94127',
            BillingCountry='United States',
            BillingCity='San Francisco' );
        insert acc;
        
        Account_x_reference__c xref = new account_x_reference__c(
name = '990026',
applicationid__c = '990026', 
application__c = 'AMS',
account__c = acc.id);
insert xref;

 Opportunity O = new Opportunity(
        Name = 'TestOpp',
        accountId = acc.Id,
        type = 'New to Existing',
        Closedate = Date.today().addYears(1),
        stagename = '1. Gain Access',
        product_category__c = 'Med/Large Software',
        Amount = 1.00,
        product_Sub_Category__c = 'Tax',
        is_ams_renewal__c = true,
        account_x_reference__C = xref.Id,
        AMS_renewal_email__c = '',
        ams_renewal_contact__c = '',
        X2017_AMS_Additional_Discount__c = ''
        );
        insert O;




o.X2017_AMS_Additional_Discount__C = '5% SALY';
o.AMS_renewal_email__c = 'joe@test.com';
o.ams_renewal_contact__c = 'Joe Test';

 

       Update o;
       
   
          
     
         }
}