wk_taa_taaqa/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting Firms</fullName>
                </value>
                <value>
                    <fullName>Banks and Financial Institutions</fullName>
                </value>
                <value>
                    <fullName>Consultants</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Financial and Estate Planners</fullName>
                </value>
                <value>
                    <fullName>General Corporate</fullName>
                </value>
                <value>
                    <fullName>Hospital and Payers</fullName>
                </value>
                <value>
                    <fullName>Insurance Companies</fullName>
                </value>
                <value>
                    <fullName>Legal Professionals</fullName>
                </value>
                <value>
                    <fullName>Retail Tax Preparers</fullName>
                </value>
                <value>
                    <fullName>Schools and Libraries</fullName>
                </value>
                <value>
                    <fullName>State and Local Government</fullName>
                </value>
                <value>
                    <fullName>Tax Exempt and Membership Organizations</fullName>
                </value>
                <value>
                    <fullName>Agriculture &amp; Mining</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Banks and Financial</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Business Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Computers &amp; Electronics</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Consumer Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Education</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Fin</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Financial Services</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Government</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Healthcare, Pharmaceuticals, &amp; Biotech</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Hospital &amp; Payers</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Law Schools</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Legal Professional</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Media &amp; Entertainment</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Sub_Segment__c</fullName>
        <label>SubSegment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market_Segment__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sole Proprietor</fullName>
                </value>
                <value>
                    <fullName>2-4 Total Employees</fullName>
                </value>
                <value>
                    <fullName>5-9 Total Employees</fullName>
                </value>
                <value>
                    <fullName>10-19 Total Employees</fullName>
                </value>
                <value>
                    <fullName>20-49 Total Employees</fullName>
                </value>
                <value>
                    <fullName>50-99 Total Employees</fullName>
                </value>
                <value>
                    <fullName>100+ Total Employees</fullName>
                </value>
                <value>
                    <fullName>Top 100 Firms</fullName>
                </value>
                <value>
                    <fullName>Global Enterprise</fullName>
                </value>
                <value>
                    <fullName>Large Enterprise</fullName>
                </value>
                <value>
                    <fullName>Mid Enterprise</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                </value>
                <value>
                    <fullName>Small</fullName>
                </value>
                <value>
                    <fullName>Dept of Agriculture</fullName>
                </value>
                <value>
                    <fullName>Dept of Commerce</fullName>
                </value>
                <value>
                    <fullName>Dept of Defense</fullName>
                </value>
                <value>
                    <fullName>Dept of Energy</fullName>
                </value>
                <value>
                    <fullName>Dept of Health and Human Services</fullName>
                </value>
                <value>
                    <fullName>Dept of Homeland Security</fullName>
                </value>
                <value>
                    <fullName>Dept of Housing and Urban Development</fullName>
                </value>
                <value>
                    <fullName>Dept of Interior</fullName>
                </value>
                <value>
                    <fullName>Dept of Justice</fullName>
                </value>
                <value>
                    <fullName>Dept of Labor</fullName>
                </value>
                <value>
                    <fullName>Dept of State</fullName>
                </value>
                <value>
                    <fullName>Dept of Treasury (not IRS)</fullName>
                </value>
                <value>
                    <fullName>Dept of Vet Affairs</fullName>
                </value>
                <value>
                    <fullName>EEOC</fullName>
                </value>
                <value>
                    <fullName>Exec Branch (White House)</fullName>
                </value>
                <value>
                    <fullName>FCC</fullName>
                </value>
                <value>
                    <fullName>FDIC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Market_Segment_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>SIC_Code__c</fullName>
        <externalId>true</externalId>
        <label>SIC Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market Segment Mapping</label>
</CustomObject>

wk_taa_taaqa/src/objects/market_segment_rules__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Is used to determine Revenue based or Employee count based to stamp sub segment on Account</description>
    <fields>
        <fullName>IsSubSegmentBasedOnAnnualRevenue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsSubSegmentBasedOnAnnualRevenue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <externalId>true</externalId>
        <label>Segment</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Market Segment Rules</label>
</CustomObject>

wk_taa_taaqa/src/objects/Market_Sub_Segment_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Market Sub Segment Mapping</description>
    <fields>
        <fullName>GTE_AnnualRevenue__c</fullName>
        <description>GTE - greater than or equal</description>
        <label>GTE_AnnualRevenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GTE_NumberOfEmployees__c</fullName>
        <description>GTE - greater than or equal</description>
        <label>GTE_NumberOfEmployees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LTE_AnnualRevenue__c</fullName>
        <description>LTE - less than or equall</description>
        <label>LTE_AnnualRevenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LTE_NumberOfEmployees__c</fullName>
        <description>LTE - less than or equal</description>
        <label>LTE_NumberOfEmployees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Segment__c</fullName>
        <label>Sub Segment</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market Sub Segment Mapping</label>
</CustomObject>

wk_taa_taaqa/src/classes/AccountTriggerHandler.cls
/*
    **************************************************************************
    Name    :   AccountTriggerHandler 
    Usage   :   This class is invoked in trigger AccountTrigger and used to populate Market Segment and Sub Segment on Account based on SIC code for Prospect accounts exported from        Data.com 
                
    Version    |    Name            |    Date           
    1.0             Rajesh Meti          09-June-2015  
    
    Trigger : AccountTrigger on Account (before insert, before update)   
    ***************************************************************************
*/

public class AccountTriggerHandler {  

    //for before insert event    
    public void onBeforeInsert(List<Account> newAccountList) {  
        Map<String, Market_Segment_Mapping__c> marketSegmentMap = new Map<String, Market_Segment_Mapping__c>();
        Map<String, Market_Segment_Rules__c> marketSegmentRuleMap = new Map<String, Market_Segment_Rules__c>();
        List<Market_Sub_Segment_Mapping__c> allMarketSubSegmentList = Market_Sub_Segment_Mapping__c.getAll().values();
        
        for(Market_Segment_Mapping__c ms : Market_Segment_Mapping__c.getAll().values()) {
            marketSegmentMap.put(ms.SIC_Code__c, ms);
        }
        
        for(Market_Segment_Rules__c msr : Market_Segment_Rules__c.getAll().values()) {
            marketSegmentRuleMap.put(msr.Segment__c, msr);
        }        
        
        for(Account acc : newAccountList) {  
        	
            if(/*acc.AccountSource == 'Data.com' &&*/acc.id ==null && String.isNotBlank(acc.Sic) && marketSegmentMap.containsKey(acc.Sic) && String.isBlank(acc.Market_Segment__c)) {
            	system.debug(loggingLevel.Error,'-------Checking if I am inside onBeforeInsert------');
                system.debug(marketSegmentMap.get(acc.Sic).Segment__c);
                acc.Market_Segment__c = marketSegmentMap.get(acc.Sic).Segment__c;   
                
                for(Market_Sub_Segment_Mapping__c mss : allMarketSubSegmentList) {
                    if(marketSegmentRuleMap.get(acc.Market_Segment__c).IsSubSegmentBasedOnAnnualRevenue__c == True) {
                        
                        if(acc.AnnualRevenue > 0 && acc.AnnualRevenue != null) {
                            if(acc.AnnualRevenue >= mss.GTE_AnnualRevenue__c && acc.AnnualRevenue <= mss.LTE_AnnualRevenue__c && marketSegmentMap.get(acc.Sic).Segment__c == mss.Segment__c) {
                                acc.Market_Sub_Segment__c = mss.Sub_Segment__c;
                                //break;
                            }
                            else if(acc.AnnualRevenue >= mss.GTE_AnnualRevenue__c && mss.LTE_AnnualRevenue__c == null && marketSegmentMap.get(acc.Sic).Segment__c == mss.Segment__c) {
                                acc.Market_Sub_Segment__c = mss.Sub_Segment__c;
                                //break;
                            }
                        }                       
                        else if(acc.NumberOfEmployees > 0 && acc.NumberOfEmployees != null) {
                            if(acc.NumberOfEmployees >= mss.GTE_NumberOfEmployees__c && acc.NumberOfEmployees <= mss.LTE_NumberOfEmployees__c && marketSegmentMap.get(acc.Sic).Segment__c == mss.Segment__c) {
                                acc.Market_Sub_Segment__c = mss.Sub_Segment__c;
                                //break;
                            }
                            else if(acc.NumberOfEmployees >= mss.GTE_NumberOfEmployees__c && mss.LTE_NumberOfEmployees__c == null && marketSegmentMap.get(acc.Sic).Segment__c == mss.Segment__c) {
                                acc.Market_Sub_Segment__c = mss.Sub_Segment__c;
                                //break;
                            }
                        }
                        else if((acc.AnnualRevenue == null || acc.AnnualRevenue == 0) && (acc.NumberOfEmployees == null || acc.NumberOfEmployees == 0 )) {
                            if((acc.AnnualRevenue == mss.GTE_AnnualRevenue__c || acc.AnnualRevenue == mss.LTE_AnnualRevenue__c) && 
                               (acc.NumberOfEmployees == mss.GTE_NumberOfEmployees__c || acc.NumberOfEmployees == mss.LTE_NumberOfEmployees__c)
                               && marketSegmentMap.get(acc.Sic).Segment__c == mss.Segment__c) {
                                acc.Market_Sub_Segment__c = mss.Sub_Segment__c;
                                //break;
                            }
                        }
                    }
                    
                    if(marketSegmentRuleMap.get(acc.Market_Segment__c).IsSubSegmentBasedOnAnnualRevenue__c == False) {
                        
                        if(acc.NumberOfEmployees > 0 && acc.NumberOfEmployees != null) {
                            if(acc.NumberOfEmployees >= mss.GTE_NumberOfEmployees__c && acc.NumberOfEmployees <= mss.LTE_NumberOfEmployees__c && marketSegmentMap.get(acc.Sic).Segment__c == mss.Segment__c) {
                                acc.Market_Sub_Segment__c = mss.Sub_Segment__c;
                                //break;
                            }
                            else if(acc.NumberOfEmployees >= mss.GTE_NumberOfEmployees__c && mss.LTE_NumberOfEmployees__c == null && marketSegmentMap.get(acc.Sic).Segment__c == mss.Segment__c) {
                                acc.Market_Sub_Segment__c = mss.Sub_Segment__c;
                                //break;
                            }
                        }
                        else if(acc.NumberOfEmployees == null || acc.NumberOfEmployees == 0 ) {
                            if(acc.NumberOfEmployees == mss.GTE_NumberOfEmployees__c || acc.NumberOfEmployees == mss.LTE_NumberOfEmployees__c && marketSegmentMap.get(acc.Sic).Segment__c == mss.Segment__c) {
                                acc.Market_Sub_Segment__c = mss.Sub_Segment__c;
                                //break;
                            }
                        }
                    }   
                }                  
            }
            
        }                
    }    
    
    //to assign updated segments    
    /*public void assignUpdatedVlaues(List<Account> newAccountList, Map<Id, Account> oldAccountMap) {  
        Map<String, Market_Segment_Mapping__c> marketSegmentMap = new Map<String, Market_Segment_Mapping__c>();
        Map<String, Market_Segment_Rules__c> marketSegmentRuleMap = new Map<String, Market_Segment_Rules__c>();
        List<Market_Sub_Segment_Mapping__c> allMarketSubSegmentList = Market_Sub_Segment_Mapping__c.getAll().values();
        
        for(Market_Segment_Mapping__c ms : Market_Segment_Mapping__c.getAll().values()) {
            marketSegmentMap.put(ms.SIC_Code__c, ms);
        }
        
        for(Market_Segment_Rules__c msr : Market_Segment_Rules__c.getAll().values()) {
            marketSegmentRuleMap.put(msr.Segment__c, msr);
        }        
        
        for(Account acc : newAccountList) {  
        	if(String.isNotBlank(acc.sic) &&
        		(acc.sic != oldAccountMap.get(acc.id).sic 
        			|| acc.AnnualRevenue != oldAccountMap.get(acc.id).AnnualRevenue
        			|| acc.NumberOfEmployees != oldAccountMap.get(acc.id).NumberOfEmployees)){
        				system.debug(loggingLevel.Error,'-------Checking if I am inside assignUpdatedVlaues------');
	            if(marketSegmentMap.containsKey(acc.Sic) ) {
	                system.debug(marketSegmentMap.get(acc.Sic).Segment__c);
	                acc.Market_Segment__c = marketSegmentMap.get(acc.Sic).Segment__c;   
	                
	                for(Market_Sub_Segment_Mapping__c mss : allMarketSubSegmentList) {
	                    if(marketSegmentRuleMap.get(acc.Market_Segment__c).IsSubSegmentBasedOnAnnualRevenue__c == True) {
	                        
	                        if(acc.AnnualRevenue > 0 && acc.AnnualRevenue != null) {
	                            if(acc.AnnualRevenue >= mss.GTE_AnnualRevenue__c && acc.AnnualRevenue <= mss.LTE_AnnualRevenue__c && marketSegmentMap.get(acc.Sic).Segment__c == mss.Segment__c) {
	                                acc.Market_Sub_Segment__c = mss.Sub_Segment__c;
	                                //break;
	                            }
	                            else if(acc.AnnualRevenue >= mss.GTE_AnnualRevenue__c && mss.LTE_AnnualRevenue__c == null && marketSegmentMap.get(acc.Sic).Segment__c == mss.Segment__c) {
	                                acc.Market_Sub_Segment__c = mss.Sub_Segment__c;
	                                //break;
	                            }
	                        }                       
	                        else if(acc.NumberOfEmployees > 0 && acc.NumberOfEmployees != null) {
	                            if(acc.NumberOfEmployees >= mss.GTE_NumberOfEmployees__c && acc.NumberOfEmployees <= mss.LTE_NumberOfEmployees__c && marketSegmentMap.get(acc.Sic).Segment__c == mss.Segment__c) {
	                                acc.Market_Sub_Segment__c = mss.Sub_Segment__c;
	                                //break;
	                            }
	                            else if(acc.NumberOfEmployees >= mss.GTE_NumberOfEmployees__c && mss.LTE_NumberOfEmployees__c == null && marketSegmentMap.get(acc.Sic).Segment__c == mss.Segment__c) {
	                                acc.Market_Sub_Segment__c = mss.Sub_Segment__c;
	                                //break;
	                            }
	                        }
	                        else if((acc.AnnualRevenue == null || acc.AnnualRevenue == 0) && (acc.NumberOfEmployees == null || acc.NumberOfEmployees == 0 )) {
	                            if((acc.AnnualRevenue == mss.GTE_AnnualRevenue__c || acc.AnnualRevenue == mss.LTE_AnnualRevenue__c) && 
	                               (acc.NumberOfEmployees == mss.GTE_NumberOfEmployees__c || acc.NumberOfEmployees == mss.LTE_NumberOfEmployees__c)
	                               && marketSegmentMap.get(acc.Sic).Segment__c == mss.Segment__c) {
	                                acc.Market_Sub_Segment__c = mss.Sub_Segment__c;
	                                //break;
	                            }
	                        }
	                    }
	                    
	                    if(marketSegmentRuleMap.get(acc.Market_Segment__c).IsSubSegmentBasedOnAnnualRevenue__c == False) {
	                        
	                        if(acc.NumberOfEmployees > 0 && acc.NumberOfEmployees != null) {
	                            if(acc.NumberOfEmployees >= mss.GTE_NumberOfEmployees__c && acc.NumberOfEmployees <= mss.LTE_NumberOfEmployees__c && marketSegmentMap.get(acc.Sic).Segment__c == mss.Segment__c) {
	                                acc.Market_Sub_Segment__c = mss.Sub_Segment__c;
	                                //break;
	                            }
	                            else if(acc.NumberOfEmployees >= mss.GTE_NumberOfEmployees__c && mss.LTE_NumberOfEmployees__c == null && marketSegmentMap.get(acc.Sic).Segment__c == mss.Segment__c) {
	                                acc.Market_Sub_Segment__c = mss.Sub_Segment__c;
	                                //break;
	                            }
	                        }
	                        else if(acc.NumberOfEmployees == null || acc.NumberOfEmployees == 0 ) {
	                            if(acc.NumberOfEmployees == mss.GTE_NumberOfEmployees__c || acc.NumberOfEmployees == mss.LTE_NumberOfEmployees__c && marketSegmentMap.get(acc.Sic).Segment__c == mss.Segment__c) {
	                                acc.Market_Sub_Segment__c = mss.Sub_Segment__c;
	                                //break;
	                            }
	                        }
	                    }   
	                }                  
	            }
        	}  
        }                
    }*/    
}