wk_taa_taaqa/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SFDC_Account__c</fullName>
        <displayFormat>{0000000000}</displayFormat>
        <externalId>true</externalId>
        <label>SFDC Account #</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Reason__c</fullName>
        <label>Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Adding to Suite</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Add-on Sale</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Better Price</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>CCH Experience</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Competition - Content / Software issue</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Competition - Platform</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Competition - Price</fullName>
                    <color>#66E9BD</color>
                </value>
                <value>
                    <fullName>Competitive Conversion</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Combining contracts</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Conversion to Better Solution</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Converted By Mistake</fullName>
                    <color>#641CCF</color>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                    <color>#F96FB7</color>
                </value>
                <value>
                    <fullName>Features / Functionality</fullName>
                    <color>#2F5D85</color>
                </value>
                <value>
                    <fullName>Merger with non WK Firm</fullName>
                    <color>#AFCADF</color>
                </value>
                <value>
                    <fullName>Merger with WK Firm</fullName>
                    <color>#8F6429</color>
                </value>
                <value>
                    <fullName>No Decision</fullName>
                    <color>#EFAE73</color>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <color>#57F17C</color>
                </value>
                <value>
                    <fullName>Strong References</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Change effective dates</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Change in business - Bankrupt</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Change in business - Budget cuts</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Change in business - Business focus change</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Change in business - Personnel change</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Change in business - Went out of business</fullName>
                    <color>#66E9BD</color>
                </value>
                <value>
                    <fullName>Conversion - Step Down</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Conversion - Step Over</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Conversion - Step Up</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Correct order entry error</fullName>
                    <color>#641CCF</color>
                </value>
                <value>
                    <fullName>Credit dept cancel</fullName>
                    <color>#F96FB7</color>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                    <color>#2F5D85</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Forecast_Type__c</fullName>
        <label>Forecast Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Low (&lt;50%)</fullName>
                    <color>#DDDDDD</color>
                </value>
                <value>
                    <fullName>Medium (50-90%)</fullName>
                    <color>#FF9900</color>
                </value>
                <value>
                    <fullName>High (&gt;90%)</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Omitted</fullName>
                    <color>#A53711</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Software</fullName>
                </value>
                <value>
                    <fullName>Med/Large Software</fullName>
                </value>
                <value>
                    <fullName>Small Firm Software</fullName>
                </value>
                <value>
                    <fullName>Research &amp; Learning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <label>Product Sub-Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Product_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Specialty</fullName>
                </value>
                <value>
                    <fullName>iFirm</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Autoflow</fullName>
                </value>
                <value>
                    <fullName>Refunds Today</fullName>
                </value>
                <value>
                    <fullName>SFS Research &amp; Learning</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>AnswerConnect</fullName>
                </value>
                <value>
                    <fullName>Core Library - Corporate Tax</fullName>
                </value>
                <value>
                    <fullName>Core Library - CPA Professional</fullName>
                </value>
                <value>
                    <fullName>Federal Add On</fullName>
                </value>
                <value>
                    <fullName>State Add On</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Certificate Programs</fullName>
                </value>
                <value>
                    <fullName>Seminars</fullName>
                </value>
                <value>
                    <fullName>Books</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Database/Lookups/RADAR</fullName>
                </value>
                <value>
                    <fullName>POS Portal</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Sales Tax Load Utilities</fullName>
                </value>
                <value>
                    <fullName>Sales Tax Returns</fullName>
                </value>
                <value>
                    <fullName>Sales Tax SaaS Core</fullName>
                </value>
                <value>
                    <fullName>STO</fullName>
                </value>
                <value>
                    <fullName>SureTax - General</fullName>
                </value>
                <value>
                    <fullName>SureTax Professional Services</fullName>
                </value>
                <value>
                    <fullName>SureTax - Telco/Energy</fullName>
                </value>
                <value>
                    <fullName>Tax Interchange for Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_Details_Other_Reason__c</fullName>
        <inlineHelpText>Required when deal is Closed Lost and Closed Reason = Other. Can also be used to track additional details of why the deal was lost.</inlineHelpText>
        <label>Reason Details/Other Reason</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Account__c</fullName>
        <formula>Account.SFDC_Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SFDC Account #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Contact__c</fullName>
        <formula>Primary_Contact_for_Proposal__r.SFDC_Contact__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SFDC Contact #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFS_Opp_Stage__c</fullName>
        <formula>IF(Text(StageName)==&apos;6. Closed Won&apos;,&apos;Onboard&apos;, 
 IF(Text(StageName)==&apos;7. Closed Lost&apos;,&apos;Lost Opportunity&apos;,
IF(Text(StageName)==&apos;2. Recognize Need&apos;,&apos;Recognize Needs&apos;,       

TRIM(
RIGHT(
    Text(StageName) ,  (LEN(Text(StageName)) - 2 )
        
    )
) )))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SFS Opp Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFS_Opp_Type__c</fullName>
        <formula>IF( ( Text(Type)==&apos;New to New&apos;  ) , &apos;New Sale To New Customer&apos;, 
IF( ( Text(Type)==&apos;Non-Subscription&apos;  ) , &apos;New Sale To New Customer&apos;,
IF(( Text(Type)==&apos;New to Existing&apos;  ) , &apos;New Sale To Existing Customer&apos;, 
IF(( Text(Type)==&apos;Renewal&apos;  ) , &apos;Renewal&apos;, &apos;&apos;) ) ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SFS Opp Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFS_Opportunity_ID__c</fullName>
        <externalId>true</externalId>
        <label>SFS Opportunity Record ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/S2S_OpportunityDeletionTriggerHandler.cls
/*
 * apex class to perform the S2S records replication for TAA <-> SFS orgs  
 * This class  is used for replicating opp chnages from SFS --> TAA.
*/
/*--------------------------------------------------------------------------
 * Date       Author            Version      Description
 * -------------------------------------------------------------------------
 * 09/13/2017 Raj Gonola       1.0      Initial draft
 * ------------------------------------------------------------------------- */
public class S2S_OpportunityDeletionTriggerHandler{
  
    
     // processing logic for update operation
    public static void onAfterDelete(List<Opportunity> oldRecords) {
          
          S2S_OppUtil oput = new S2S_OppUtil();
          List<S2S_OppUtil.opps> setopps = new List<S2S_OppUtil.opps>();
          List<Account> accountToupdate= new List<Account>();
          Map<ID,Opportunity> actpid = new Map<ID,Opportunity>();
          
          Datetime stsrttime;
       stsrttime = Datetime.now();
      Integer seconds = stsrttime.second();
      
        // List of SFDC Account #
        for(Opportunity opp: oldRecords) {
            
            // this is to prepare the set of email address of the owners
            if(  !String.isblank(opp.SFS_Opportunity_ID__c) ) {
            
                 S2S_OppUtil.opps  opplines   = new  S2S_OppUtil.opps();
                 
                 opplines.oneforceAcc=opp.SFDC_Account__c;
                 opplines.oneforceCon=opp.SFDC_Contact__c;
                   
                 opplines.SFSOppRecordId=opp.SFS_Opportunity_ID__c;
                
                 
                 opplines.TAAOppRecordId=opp.Id;
                 
                 
                 opplines.Type=opp.SFS_Opp_Type__c;
                 opplines.Amount=string.valueof(opp.Amount);
                 opplines.StageName=opp.SFS_Opp_Stage__c;
                 
                 opplines.ProductCategory=opp.Product_Category__c;
                 opplines.ProductSubCategory=opp.Product_Sub_Category__c;
                 
                 opplines.ForecastType=opp.Forecast_Type__c;
                 opplines.CloseDate=String.valueof(opp.CloseDate);
                 
                 opplines.CloseReason=opp.Closed_Reason__c;
                 opplines.OtherCloseReason=opp.Reason_Details_Other_Reason__c;
                 
                 opplines.Competitor=opp.Competitor__c;
                 opplines.OtherCompetitor=opp.Other_Competitor__c;
                 opplines.OppOwner=opp.TAA_Opportunity_Owner_Id__c ;
                 opplines.Name=opp.Name;
                 
                 
            
              setopps.add(opplines);
             
             }
             
             
            
        }
       
       
         oput.opps =setopps;
         
         String strRequestParam = JSON.serialize(oput);
                
         system.debug('request json'+strRequestParam);
        
        try{         
        
         
         if(setopps.size()>0) SendInfo(strRequestParam,stsrttime,seconds);  
         
          }catch(Exception  ex){
          
          }
    } 
    
    
    
     @future(callout=true)
    public static void SendInfo(String Jsons,DateTime stsrttime,Integer seconds) {
    
        String Result;
        
        HttpResponse authres =OauthUtil.Authenticate('');
        HttpResponse res = new HttpResponse();
        HttpRequest req = new HttpRequest();
         try{
         
        system.debug('Auth request response'+authres.getStatusCode());
        
        
        
        if(authres.getStatusCode()==200){ 
            
        OauthUtil.OAuth2 objAuthenticationInfo = (OauthUtil.OAuth2)JSON.deserialize(authres.getbody(), OauthUtil.OAuth2.class);
       
        
        if(objAuthenticationInfo.access_token!=null){
        
        
          Http h = new Http();
          
          req.setHeader('Authorization','Bearer '+objAuthenticationInfo.access_token);
          req.setHeader('Content-Type','application/json');
          req.setHeader('accept','application/json');
          req.setTimeout(120000);
        
          req.setBody(Jsons);//Send JSON body
          req.setMethod('POST');
          if(!Test.isRunningTest()) { req.setEndpoint(objAuthenticationInfo.instance_url+'/services/apexrest/OpportunityDeletion'); } else {req.setEndpoint('http://fakeurl.com/services/oauth2/token');}
          res = h.send(req);
          system.debug('RESPONSE_BODY'+res.getStatusCode());
          String Error_message;
                       if(res.getStatusCode()==200){ 
                       
                       List<S2S_LogFile__c> logList = new List<S2S_LogFile__c>();   
              
             logList.add(S2S_Util.prepareLogEntry('Opp Del',Jsons ,null,null,'TAA',res.getStatus(),res.getStatusCode(),stsrttime,seconds));
             
             if(!logList.isEmpty())
              Database.insert(logList, false);

                       }else{
                       
                       List<S2S_LogFile__c> logList = new List<S2S_LogFile__c>();   
              
             logList.add(S2S_Util.prepareLogEntry('Opp Del',Jsons ,null,null,'TAA',res.getStatus(),res.getStatusCode(),stsrttime,seconds));
             
             if(!logList.isEmpty())
              Database.insert(logList, false);
                       }
               }else{
               
               List<S2S_LogFile__c> logList = new List<S2S_LogFile__c>();   
              
             logList.add(S2S_Util.prepareLogEntry('Opp Del',Jsons ,null,null,'TAA',authres.getStatus(),authres.getStatusCode(),stsrttime,seconds));
             
             if(!logList.isEmpty())
              Database.insert(logList, false);
               
               
               }
           
           }else{
           
           List<S2S_LogFile__c> logList = new List<S2S_LogFile__c>();   
              
              logList.add(S2S_Util.prepareLogEntry('Opp Del',Jsons ,null,null,'TAA',authres.getStatus(),authres.getStatusCode(),stsrttime,seconds));
              
             if(!logList.isEmpty())
              Database.insert(logList, false);
              
           
           
           }
     }catch(Exception ex){
   
           Result='Something Went wrong'+ex.getMessage()+ex.getLineNumber();
           system.debug('Resp String'+Result);
           
           List<S2S_LogFile__c> logList = new List<S2S_LogFile__c>();   
             
              logList.add(S2S_Util.prepareLogEntry('Opp Del',Jsons ,null,null,'TAA',Result,500,stsrttime,seconds));
               
             
             if(!logList.isEmpty())
              Database.insert(logList, false);
            
              
           }
            
            
        }     
}