wk_taa_taaqa/src/objects/Account_X_Reference__c.object
<CustomObject>
    <fields>
        <fullName>AMS_Account_Grouping__c</fullName>
        <label>AMS Account Grouping</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AMS_Special_Agreement__c</fullName>
        <label>AMS Special Agreement</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account X-Reference</relationshipLabel>
        <relationshipName>Account_X_Reference</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ApplicationID__c</fullName>
        <externalId>true</externalId>
        <label>Application ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMS</fullName>
                </value>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>SFS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Authentication_Type__c</fullName>
        <label>Authentication_Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_City__c</fullName>
        <label>Bill To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Contact_Name__c</fullName>
        <label>Bill To Contact Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Country__c</fullName>
        <label>Bill To Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Partner_Number__c</fullName>
        <label>Bill_To_Partner_Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_State__c</fullName>
        <label>Bill To State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Street_Line_1__c</fullName>
        <label>Bill To Street Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Street_Line_2__c</fullName>
        <label>Bill To Street Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Zip_Postal_Code__c</fullName>
        <label>Bill To Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Account_Name__c</fullName>
        <label>ERP Account Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IDs_Issued__c</fullName>
        <label>IDs_Issued</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_IDs_Allowed__c</fullName>
        <label>Max_IDs_Allowed</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>PostalCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_City__c</fullName>
        <label>Ship To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Contact_Name__c</fullName>
        <label>Ship To Contact Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Country__c</fullName>
        <label>Ship To Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Partner_Number__c</fullName>
        <label>Ship_To_Partner_Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_State__c</fullName>
        <label>Ship To State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Street_Line_1__c</fullName>
        <label>Ship To Street Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Street_Line_2__c</fullName>
        <label>Ship To Street Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Zip_Postal_Code__c</fullName>
        <label>Ship To Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street_Address</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Account X-Reference</label>
    <nameField>
        <label>Account X-Reference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account X-Reference</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AMS_Account_Grouping__c</fullName>
        <formula>CASE( Account_X_Reference__r.AMS_Account_Grouping__c ,&quot;0&quot;,&quot;Non-OFX User&quot;,&quot;2&quot;,&quot;WAN&quot;,&quot;5&quot;,&quot;New OFX Account&quot;,&quot;6&quot;,&quot;OFX Account&quot;,&quot;7&quot;,&quot;PUP&quot;,&quot;8&quot;,&quot;LIB&quot;,&quot;4&quot;,&quot;PUP WAN&quot;,&quot;3&quot;,&quot;LIB WAN&quot;,&quot;9&quot;,&quot;1040 Conversion&quot;,&quot;A&quot;,&quot;Corp Tax Lib&quot;,&quot;B&quot;,&quot;Universities&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AMS Account Grouping</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AMS_Special_Agreement__c</fullName>
        <formula>CASE( Account_X_Reference__r.AMS_Special_Agreement__c ,&quot;Y&quot;, &quot;Corp Suite - Cal&quot;, &quot;Z&quot;,&quot;Corp Suite - FY&quot;,&quot;C&quot;, &quot;Corporate Filer&quot;, &quot;M&quot;, &quot;Multi_Site Main&quot;, &quot;N&quot;, &quot;Multi-Site Sub&quot;, &quot;R&quot;, &quot;RFX(OFXII Remote)&quot;, &quot;S&quot;, &quot;SFX&quot;, &quot;A&quot;, &quot;Standalone Accuplanner&quot;, &quot;V&quot;, &quot;Standalone Auditvision&quot;, &quot;L&quot;,&quot;Sub License&quot;, &quot;W&quot;, &quot;WAN Main&quot;, &quot;X&quot;, &quot;WAN Satellite&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AMS Special Agreement</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_X_Reference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account X-Reference</label>
        <referenceTo>Account_X_Reference__c</referenceTo>
        <relationshipLabel>Opportunities (Account X-Reference)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Forecast_Type__c</fullName>
        <label>Forecast Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Low (&lt;50%)</fullName>
                    <color>#DDDDDD</color>
                </value>
                <value>
                    <fullName>Medium (50-90%)</fullName>
                    <color>#FF9900</color>
                </value>
                <value>
                    <fullName>High (&gt;90%)</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Omitted</fullName>
                    <color>#A53711</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/TestClassForQuoteProposalTriggers.cls
/*
    **************************************************************************
    Name    :   TestClassForQuoteProposalTriggers 
    Usage   :   Class is used to cover the code coverage of the trigger 'QuoteProposalTrigger'
    
    Version    |    Name            |    Date           
    1.0             Rajesh Meti          01-Dec-2014  
    2.0             Rajesh Meti          27-Jan-2015
    
    Trigger : QuoteProposalTrigger on Apttus_Proposal__Proposal__c (before insert, before update)
    
    ***************************************************************************
*/

@isTest(seeAlldata=false)
public class TestClassForQuoteProposalTriggers 
{
    @testsetup static void testQuoteProposalTriggerHandler() 
    {
        Map<String, RecordType> quoteProposalRecordTypeMap = new Map<String,RecordType>();
        for(RecordType rt : [SELECT Id, Name FROM RecordType WHERE SobjectType='Apttus_Proposal__Proposal__c']) {
            quoteProposalRecordTypeMap.put(rt.Name, rt);
        }
        
        Account AcctObj = new Account(  Name = 'myAcct', 
                                BillingStreet='25 Upland Drive',
                                BillingPostalCode='94127',
                                BillingCountry='United States',
                                BillingCity='San Francisco',
                                BillingState='CA',
                                Phone = '555555555');
        insert AcctObj;        
        
        Opportunity OpptyObj = new Opportunity( Name = 'CPQ Test Oppty', AccountId = AcctObj.Id, 
                                                CloseDate = date.today()+30, StageName = '5. Time to Buy',
                                                Forecast_Type__c = 'Low (<50%)' );
        insert OpptyObj;
        
        Account AcctObj1 = new Account(  Name = 'myAcct1', 
                                BillingStreet='25 Upland Drive',
                                BillingPostalCode='94127',
                                BillingCountry='United States',
                                BillingCity='San Francisco',
                                BillingState='CA',
                                Phone = '555555555');
        insert AcctObj1;
        
         Opportunity OpptyObj1 = new Opportunity( Name = 'CPQ Test Oppty1', AccountId = AcctObj1.Id, 
                                                CloseDate = date.today()+30, StageName = '5. Time to Buy',
                                                Forecast_Type__c = 'Low (<50%)' );
        insert OpptyObj1;

        Apttus_Config2__PriceList__c pricelistforAMSProposal = new Apttus_Config2__PriceList__c(Name ='Professional Software Price List', Apttus_Config2__Active__c = true);
        insert pricelistforAMSProposal;
        
        Apttus_Config2__PriceList__c pricelistforSAPProposal = new Apttus_Config2__PriceList__c(Name ='R&L Price List', Apttus_Config2__Active__c = true);
        insert pricelistforSAPProposal;
        
        Account_X_Reference__c SAPXRefAccObj = new Account_X_Reference__c( Name = '4441026029', Account__c = AcctObj.Id, ApplicationID__c = '4441026029', 
                                                                            Application__c = 'SAP', ERP_Account_Name__c = 'WEISER MAZARS', Bill_To_Street_Line_1__c = '135 W 50TH ST',
                                                                            Bill_To_Contact_Name__c = 'WENDY STEVENS', Bill_To_City__c = 'NEW YORK', Bill_To_State__c = 'NY', 
                                                                            Bill_To_Zip_Postal_Code__c = '10020-1201', Bill_To_Country__c = 'US', Ship_To_Contact_Name__c = 'VICTORIA PITKIN', 
                                                                            Ship_To_City__c = 'NEW YORK', Ship_To_Street_Line_1__c = '135 W 50TH ST', Ship_To_State__c = 'NY', 
                                                                            Ship_To_Zip_Postal_Code__c = '10020-1201', Ship_To_Country__c = 'US', AMS_Special_Agreement__c = 'Test', 
                                                                            AMS_Account_Grouping__c = 'Test', Bill_To_Street_Line_2__c = '135 W 50TH STREET', Ship_To_Street_Line_2__c = '135 W 50TH STREET',
                                                                            Ship_To_Partner_Number__c = '4441320673', Bill_To_Partner_Number__c = '4441320694', Street_Address__c = '135 W 50TH ST', 
                                                                            City__c = 'NEW YORK', State__c = 'NY', PostalCode__c = '10020-1201', Country__c = 'US');
        insert SAPXRefAccObj;

        Account_X_Reference__c AMSXRefAccObj = new Account_X_Reference__c( Name = '999999', Account__c = AcctObj.Id, ApplicationID__c = '999999',
                                                                            Application__c = 'AMS', ERP_Account_Name__c = 'WEISERMAZARS LLP', Bill_To_Street_Line_1__c = '12TH FLOOR',
                                                                            Bill_To_Contact_Name__c = 'JONATHAN GOLD', Bill_To_City__c = 'NEW YORK', Bill_To_State__c = 'NY',
                                                                            Bill_To_Zip_Postal_Code__c = '10020-1201', Bill_To_Country__c = 'US', Ship_To_Contact_Name__c = 'JONATHAN GOLD',
                                                                            Ship_To_City__c = 'NEW YORK', Ship_To_Street_Line_1__c = '12TH FLOOR', Ship_To_State__c = 'NY',
                                                                            Ship_To_Zip_Postal_Code__c = '10020-1201', Ship_To_Country__c = 'US', AMS_Special_Agreement__c = 'M',
                                                                            AMS_Account_Grouping__c = 'N', Bill_To_Street_Line_2__c = '135 W 50TH STREET', Ship_To_Street_Line_2__c = '135 W 50TH STREET',
                                                                            Ship_To_Partner_Number__c = '999999', Bill_To_Partner_Number__c = '999999', Street_Address__c = '135 W 50TH ST',
                                                                            City__c = 'NEW YORK', State__c = 'NY', PostalCode__c = '10020-1201', Country__c = 'US', Email__c ='test@test.com',
                                                                            Phone__c = '55555555', Authentication_Type__c = 'Standard', Max_IDs_Allowed__c = 999, IDs_Issued__c = 100);
        insert AMSXRefAccObj;       

                                
        Apttus_Proposal__Proposal__c SAPQuotePropObj = new Apttus_Proposal__Proposal__c( Apttus_Proposal__Proposal_Name__c = 'myProposal',SAP_Contact_Channel__c= 'Field Sales Rep',SAP_Sales_Channel__c ='Field Sales rep',  Apttus_Proposal__Opportunity__c = OpptyObj.Id, 
                                                                                        Apttus_Proposal__Primary__c = false, Apttus_QPConfig__ConfigurationFinalizedDate__c = null, 
                                                                                        ERP_Account__c = SAPXRefAccObj.Id, Apttus_Proposal__Account__c = AcctObj.Id, RecordTypeId = quoteProposalRecordTypeMap.get('SAP Subscription').Id, 
                                                                                        Apttus_QPConfig__PriceListId__c = pricelistforSAPProposal.Id
                                                                                    );
        insert SAPQuotePropObj; 
        
        Apttus_Proposal__Proposal__c SAPQuotePropObj1 = new Apttus_Proposal__Proposal__c( Apttus_Proposal__Proposal_Name__c = 'myProposal',SAP_Contact_Channel__c= 'Field Sales Rep',SAP_Sales_Channel__c ='Field Sales rep', Apttus_Proposal__Opportunity__c = OpptyObj1.Id, 
                                                                                        Apttus_Proposal__Primary__c = false, Apttus_QPConfig__ConfigurationFinalizedDate__c = null, 
                                                                                        Apttus_Proposal__Account__c = AcctObj1.Id, RecordTypeId = quoteProposalRecordTypeMap.get('SAP Subscription').Id, 
                                                                                        Apttus_QPConfig__PriceListId__c = pricelistforSAPProposal.Id
                                                                                    );
        insert SAPQuotePropObj1; 
        

        Apttus_Proposal__Proposal__c AMSQuotePropObj = new Apttus_Proposal__Proposal__c( Apttus_Proposal__Proposal_Name__c = 'myProposal', Apttus_Proposal__Opportunity__c = OpptyObj.Id, 
                                                                                        Apttus_Proposal__Primary__c = false, Apttus_QPConfig__ConfigurationFinalizedDate__c = null, 
                                                                                        ERP_Account__c = AMSXRefAccObj.Id, Apttus_Proposal__Account__c = AcctObj.Id, RecordTypeId = quoteProposalRecordTypeMap.get('AMS Proposal').Id, 
                                                                                        Apttus_QPConfig__PriceListId__c = pricelistforAMSProposal.Id
                                                                                    );
        insert AMSQuotePropObj;      
              
        Account_X_Reference__c SAPXRefAccObj1 = new Account_X_Reference__c( Name = '4441026030', Account__c = AcctObj.Id, ApplicationID__c = '4441026030', 
                                                                            Application__c = 'SAP', ERP_Account_Name__c = 'WEISER MAZARS1', Bill_To_Street_Line_1__c = '135 W 50TH ST',
                                                                            Bill_To_Contact_Name__c = 'WENDY STEVENS1', Bill_To_City__c = 'NEW YORK', Bill_To_State__c = 'NY', 
                                                                            Bill_To_Zip_Postal_Code__c = '10020-1201', Bill_To_Country__c = 'US', Ship_To_Contact_Name__c = 'VICTORIA PITKIN1', 
                                                                            Ship_To_City__c = 'NEW YORK', Ship_To_Street_Line_1__c = '135 W 50TH ST', Ship_To_State__c = 'NY', 
                                                                            Ship_To_Zip_Postal_Code__c = '10020-1201', Ship_To_Country__c = 'US', AMS_Special_Agreement__c = 'Test', 
                                                                            AMS_Account_Grouping__c = 'Test', Bill_To_Street_Line_2__c = '135 W 50TH STREET', Ship_To_Street_Line_2__c = '135 W 50TH STREET',
                                                                            Ship_To_Partner_Number__c = '4441320674', Bill_To_Partner_Number__c = '4441320695', Street_Address__c = '135 W 50TH ST', 
                                                                            City__c = 'NEW YORK', State__c = 'NY', PostalCode__c = '10020-1201', Country__c = 'US', Email__c ='test@test.com',
                                                                            Phone__c = '55555555', Authentication_Type__c = 'Standard', Max_IDs_Allowed__c = 999, IDs_Issued__c = 100);
        insert SAPXRefAccObj1;     
    }
    
    static testmethod void testBeforeUpdate()
    {
    	Map<String, RecordType> quoteProposalRecordTypeMap = new Map<String,RecordType>();
        for(RecordType rt : [SELECT Id, Name FROM RecordType WHERE SobjectType='Apttus_Proposal__Proposal__c']) {
            quoteProposalRecordTypeMap.put(rt.Name, rt);
        }
    	
    	Account AcctObj1 = [SELECT Id FROM Account WHERE Name = 'myAcct1'];	
		Account_X_Reference__c SAPXRefAccObj1 = [SELECT Id FROM Account_X_Reference__c WHERE Name =: '4441026030'];
    	Apttus_Proposal__Proposal__c SAPQuotePropObj = [SELECT Id FROM Apttus_Proposal__Proposal__c WHERE RecordTypeId =: quoteProposalRecordTypeMap.get('SAP Subscription').Id LIMIT 1];
    	Account_X_Reference__c SAPXRefAccObj = [SELECT Id FROM Account_X_Reference__c WHERE Name =: '4441026029'];
    	
    	Test.startTest();
    	SAPQuotePropObj.Apttus_Proposal__Account__c = AcctObj1.Id;
        SAPQuotePropObj.ERP_Account__c = SAPXRefAccObj1.Id;
        update SAPQuotePropObj;
        
        SAPQuotePropObj.ERP_Account__c = SAPXRefAccObj.Id;
        SAPQuotePropObj.Ship_To_ERP_Account__c = null;
        update SAPQuotePropObj;
        
        Apttus_Proposal__Proposal__c AMSQuotePropObj = [SELECT Id FROM Apttus_Proposal__Proposal__c WHERE RecordTypeId =: quoteProposalRecordTypeMap.get('AMS Proposal').Id LIMIT 1];
        Account_X_Reference__c AMSXRefAccObj = [SELECT Id FROM Account_X_Reference__c WHERE Name =: '999999'];
        AMSQuotePropObj.ERP_Account__c = AMSXRefAccObj.Id;
        update AMSQuotePropObj;
        Test.stopTest();          
    }
}