wk_taa_taaqa/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Corp_Direct__c</fullName>
        <label>Corp Direct DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_Indirect__c</fullName>
        <label>Corp Indirect DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISR_Indirect__c</fullName>
        <label>ISR Indirect</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAM_SAM_CNAM__c</fullName>
        <label>NAM/SAM/CNAM DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_SW_FSR__c</fullName>
        <label>Pro SW RSC DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_ASR__c</fullName>
        <label>R&amp;L RC DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_FSR__c</fullName>
        <label>R&amp;L RSC DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SW_ASR__c</fullName>
        <label>SW RC DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Source__c</fullName>
        <label>Service Source DTN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Assignment_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>ASR_Indirect_Corp_Software__c</fullName>
        <description>ASR Indirect (Corp Software)</description>
        <inlineHelpText>ASR Indirect (Corp Software)</inlineHelpText>
        <label>ASR Indirect (Corp Software)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_Direct__c</fullName>
        <inlineHelpText>FSR - Direct (Corp Software)</inlineHelpText>
        <label>Corp Direct</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_Indirect__c</fullName>
        <inlineHelpText>FSR - Indirect (Corp Sotware)</inlineHelpText>
        <label>Corp Indirect</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISR_Indirect__c</fullName>
        <inlineHelpText>ISR - Indirect (Corp Software)</inlineHelpText>
        <label>ISR Indirect</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAM_SAM_CNAM__c</fullName>
        <inlineHelpText>NAM- National Account Manager, SAM-Strategic Account Manager, CNAM-Corporate Account Manager</inlineHelpText>
        <label>NAM/SAM/CNAM</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NAM - National Accounts</fullName>
                </value>
                <value>
                    <fullName>SAM - Strategic Account Manager</fullName>
                </value>
                <value>
                    <fullName>CAM - Corporate Account Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pro_SW_FSR__c</fullName>
        <inlineHelpText>FSR- Professional Sotware</inlineHelpText>
        <label>Pro SW FSR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_SW_ISR__c</fullName>
        <inlineHelpText>ISR - Professional Software</inlineHelpText>
        <label>Pro SW ISR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_ASR__c</fullName>
        <inlineHelpText>ASR - Research and Learning</inlineHelpText>
        <label>R&amp;L ASR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_FSR__c</fullName>
        <inlineHelpText>FSR - Research and Learning</inlineHelpText>
        <label>R&amp;L FSR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SW_ASR__c</fullName>
        <inlineHelpText>ASR - Professional Software</inlineHelpText>
        <label>SW ASR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Source__c</fullName>
        <inlineHelpText>ASR - R&amp;L - Service Source</inlineHelpText>
        <label>Service Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assignment Matrix</label>
    <nameField>
        <label>Assignment Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Matrixs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Corporate_National_Role_DTN__c.object
<CustomObject>
    <description>Corporate National Accounts Named Account Type Corporate National</description>
    <fields>
        <fullName>DTN__c</fullName>
        <description>Division Territory Number</description>
        <label>DTN</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>Corporate National Role-DTN</label>
    <nameField>
        <displayFormat>CNA-{000}</displayFormat>
        <label>Corp National Role-DTN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corporate National Role-DTN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Market_Segment_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>SIC_Code__c</fullName>
        <externalId>true</externalId>
        <label>SIC Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market Segment Mapping</label>
</CustomObject>

wk_taa_taaqa/src/objects/market_segment_rules__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Is used to determine Revenue based or Employee count based to stamp sub segment on Account</description>
    <fields>
        <fullName>IsSubSegmentBasedOnAnnualRevenue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsSubSegmentBasedOnAnnualRevenue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSubSegmentBasedOnEmployeeCount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsSubSegmentBasedOnEmployeeCount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <externalId>true</externalId>
        <label>Segment</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Market Segment Rules</label>
</CustomObject>

wk_taa_taaqa/src/objects/Market_Sub_Segment_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Market Sub Segment Mapping</description>
    <fields>
        <fullName>GTE_AnnualRevenue__c</fullName>
        <description>GTE - greater than or equal</description>
        <label>GTE_AnnualRevenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GTE_NumberOfEmployees__c</fullName>
        <description>GTE - greater than or equal</description>
        <label>GTE_NumberOfEmployees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LTE_AnnualRevenue__c</fullName>
        <description>LTE - less than or equall</description>
        <label>LTE_AnnualRevenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LTE_NumberOfEmployees__c</fullName>
        <description>LTE - less than or equal</description>
        <label>LTE_NumberOfEmployees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Segment__c</fullName>
        <label>Sub Segment</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Market Sub Segment Mapping</label>
</CustomObject>

wk_taa_taaqa/src/objects/National_Account_Management__c.object
<CustomObject>
    <description>Defines the National Account Management Role for Named Accounts with Named Account Type = National</description>
    <fields>
        <fullName>DTN__c</fullName>
        <label>DTN</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>National Account Management</label>
    <nameField>
        <displayFormat>NAM-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>National Account Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Strategic_Account_RoleDTN__c.object
<CustomObject>
    <description>Defines the Strategic Account Roles of Strategic Account Manager (SAM) and Solution Architect (SA) Per DTN</description>
    <fields>
        <fullName>DTN__c</fullName>
        <label>DTN</label>
        <length>7</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Strategic Account Role-DTN</label>
    <nameField>
        <displayFormat>SAM-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Account RoleDTN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>DTN__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>External Id for User</inlineHelpText>
        <label>DTN</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Medium/Large Market</fullName>
                </value>
                <value>
                    <fullName>Research &amp; Learning</fullName>
                </value>
                <value>
                    <fullName>Small Market</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/ZipCodeDTN__c.object
<CustomObject>
    <fields>
        <fullName>ASR_Indirect_Corp_Software__c</fullName>
        <description>ASR Indirect (Corp Software)</description>
        <inlineHelpText>ASR Indirect (Corp Software)</inlineHelpText>
        <label>ASR Indirect (Corp Software)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_Direct__c</fullName>
        <inlineHelpText>FSR - Direct (Corp Software)</inlineHelpText>
        <label>Corp Direct</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_Indirect__c</fullName>
        <inlineHelpText>FSR - Indirect (Corp Sotware)</inlineHelpText>
        <label>Corp Indirect</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISR_Indirect__c</fullName>
        <inlineHelpText>ISR - Indirect (Corp Software)</inlineHelpText>
        <label>ISR Indirect</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NAM_SAM_CNAM__c</fullName>
        <inlineHelpText>CNAM-Corporate Account Manager, SAM-Strategic Account Manager, CNAM-Corporate Account Manager</inlineHelpText>
        <label>NAM/SAM/CNAM</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_SW_FSR__c</fullName>
        <inlineHelpText>FSR- Professional Sotware</inlineHelpText>
        <label>Pro SW FSR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_SW_ISR__c</fullName>
        <inlineHelpText>ISR - Professional Software</inlineHelpText>
        <label>Pro SW ISR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_ASR__c</fullName>
        <inlineHelpText>ASR - Research and Learning</inlineHelpText>
        <label>R&amp;L ASR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_L_FSR__c</fullName>
        <inlineHelpText>FSR - Research and Learning</inlineHelpText>
        <label>R&amp;L FSR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SW_ASR__c</fullName>
        <inlineHelpText>ASR - Professional Software</inlineHelpText>
        <label>SW ASR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Source__c</fullName>
        <inlineHelpText>ASR - R&amp;L - Service Source</inlineHelpText>
        <label>Service Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Zip Code DTN</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes DTN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/TestMassUpdateAccountBatch.cls
/**
 * This class contains unit tests for validating the behavior of
 *Apex class : MassUpdateAccountBatchController, MassUpdateAccountBatch
 */
@isTest(SeeAllData=false)
private class TestMassUpdateAccountBatch {
    /*
    @method : setup
    @description : to setup the require data for other test methods
    */
    static void setup(){
        Market_Segment_Mapping__c msm = new Market_Segment_Mapping__c(Name='Test0092',Segment__c='Accounting Firms',SIC_Code__c='0092');
        insert msm;
        Market_Segment_Rules__c msr =new Market_Segment_Rules__c(Name='Test1',Segment__c='Accounting Firms',IsSubSegmentBasedOnAnnualRevenue__c=True, IsSubSegmentBasedOnEmployeeCount__c=True);
        insert msr;
        Market_Sub_Segment_Mapping__c mss =new Market_Sub_Segment_Mapping__c(Name='Test1',Segment__c='Accounting Firms',Sub_Segment__c='5-9 Total Employees',GTE_AnnualRevenue__c=null,LTE_AnnualRevenue__c=0,GTE_NumberOfEmployees__c=null,LTE_NumberOfEmployees__c=0);
        insert mss;
        User u1 = TestDataFactory.newUser('222a',1);
        User u2 = TestDataFactory.newUser('222b',2);
        User u3 = TestDataFactory.newUser('222c',3);
        User u4 = TestDataFactory.newUser('222d',4);
        User u5 = TestDataFactory.newUser('222e',5);
        User uSAM = TestDataFactory.newUser('222f',6);
        User uSA = TestDataFactory.newUser('222g',7);
        User uCNAM = TestDataFactory.newUser('222h',8);
        User uNAM = TestDataFactory.newUser('222i',9);
        system.debug(loggingLevel.Error,'----u5----::'+[Select id,Name,DTN__c from user where DTN__c='222e']);
        list<ZipCodeDTN__c>zipCodeDTNlist = new list<ZipCodeDTN__c>();
        zipCodeDTNlist.add(TestDataFactory.zipCodeDtn('55555', '222a', '222b'));
        zipCodeDTNlist.add(TestDataFactory.zipCodeDtn('66666', '222c', '222d'));
        zipCodeDTNlist.add(TestDataFactory.zipCodeDtn('wrongDTN', '2220', '222a'));
        /*zipCodeDTN with having values for all fields*/
        ZipCodeDTN__c z = TestDataFactory.zipCodeDtn('77777', '2220', '2221');
        z.ASR_Indirect_Corp_Software__c='222a';
        z.Corp_Direct__c = '222b';
        z.Corp_Indirect__c = '222c';
        z.ISR_Indirect__c = '222d';
        z.NAM_SAM_CNAM__c = '222e';
        z.Pro_SW_FSR__c = '222f';
        z.Pro_SW_ISR__c = '222g';
        z.R_L_ASR__c = '222h';
        z.R_L_FSR__c = '222i';
        z.Service_Source__c = '221j';
        z.SW_ASR__c = '222a';
        update z;
        zipCodeDTNlist.add(z);
        
        list<Assignment_Matrix__c>assignmentMatrix = new list<Assignment_Matrix__c>();
        assignmentMatrix.add(TestDataFactory.assignmentMatrixWithAF('Accounting Firms','5-9 Total Employees'));
        assignmentMatrix.add(TestDataFactory.assignmentMatrixWithLessRolls('Legal Professionals','Law Firm 1-3 Attorneys'));
        String username = [Select id,Name,DTN__c from user where DTN__c='222e'].Name;
        //TAACustomSetting__c taa = TestDataFactory.newTaaCustomSetting(username);
        AccountAutomationSetting__c taa = TestDataFactory.newTaaCustomSetting(username);
        Strategic_Account_RoleDTN__c sam = TestDataFactory.newSAR('DemoSAM','222f',uSA,uSAM);
        Corporate_National_Role_DTN__c cnr = TestDataFactory.newCNR('DemoCNR', uCNAM, '222h');
        National_Account_Management__c nam = TestDataFactory.newNAM('DemoNAM', '222i', uNAM);
    }
    /*
    @method: setSegment
    @description : set the segment, sub-segment as well dtns and team members on the basis of sic code.
    */
    static testMethod void setSegment() {
        Account myAccount = new Account(Name='myAccount',Market_Segment__c='Accounting Firms',Market_Sub_Segment__c='5-9 Total Employees'/*Sic = '0092'*/, IsMassUpdated__c=true, billingPostalCode='55555', AnnualRevenue=0, NumberOfEmployees=0);
        insert myAccount; 
        setup();
        Test.startTest();
            MassUpdateAccountBatch job = new MassUpdateAccountBatch();
            Database.executeBatch(job);
        Test.stopTest();
        
        Account a =[Select id,Name,AISR__c,QP__c,Market_Segment__c,Market_Sub_Segment__c,DTN_Makeup__c,IsMassUpdated__c from Account where name='myAccount' limit 1];
        system.debug(loggingLevel.Error,'>>>>>>>>>>>>>>>>-----------::'+a);
        
        map<String,AccountTeamMember>atmMap = new map<String,AccountTeamMember>();
        for(AccountTeamMember atm: [Select id,user.Name,user.DTN__c,TeamMemberRole from AccountTeamMember where accountid=:a.id]){
            atmMap.put(atm.user.DTN__c,atm);
        }
        system.debug(loggingLevel.Error,'-----atmMap------::'+atmMap);
        system.assertEquals(false, a.IsMassUpdated__c);
        system.assertEquals('Accounting Firms', a.Market_Segment__c);
        system.assertEquals('5-9 Total Employees', a.Market_Sub_Segment__c);
        system.assertEquals('222a',a.AISR__c);
        system.assertEquals('222b',a.QP__c);
       // system.assertEquals(2,atmMap.size());
        //system.assertEquals('Testing1',atmMap.get('222a').user.Name);
       // system.assertEquals('Testing2',atmMap.get('222b').user.Name);
    }
    
    /*
    @method: updateAccountWithZipCodeDTNChange
    @description: update the account with respect to change of zipcodeDTN tab
    */
    static testMethod void updateAccountWithZipCodeDTNChange(){
        setup();
        Account myAccount = new Account(Name='myAccount', Sic = '0092', billingPostalCode='55555', AnnualRevenue=0, NumberOfEmployees=0, Inactive__c=false);
        insert myAccount;
        
        ZipCodeDTN__c zipCode = [Select id,Name,AISR__c,QP__c,IsUpdated__c from ZipCodeDTN__c where Name='55555' limit 1];
        zipCode.AISR__c = '222c';
        zipCode.QP__c = '222d';
        zipCode.IsUpdated__c = true;
        update zipCode;
        
        Account a =[Select id,Name,AISR__c,QP__c,Market_Segment__c,Market_Sub_Segment__c,DTN_Makeup__c,Inactive__c from Account where name='myAccount' limit 1];
        system.debug(loggingLevel.Error,'-----------::'+a);
        
        map<String,AccountTeamMember>atmMap = new map<String,AccountTeamMember>();
        for(AccountTeamMember atm: [Select id,user.Name,user.DTN__c,TeamMemberRole from AccountTeamMember where accountid=:a.id]){
            atmMap.put(atm.user.DTN__c,atm);
        }
        system.debug(loggingLevel.Error,'-----atmMap------::'+atmMap);
        system.assertEquals('Accounting Firms', a.Market_Segment__c);
        system.assertEquals('5-9 Total Employees', a.Market_Sub_Segment__c);
        system.assertEquals('222a',a.AISR__c);
        system.assertEquals('222b',a.QP__c);
        //system.assertEquals(2,atmMap.size());
        system.assertEquals('Testing1',atmMap.get('222a').user.Name);
        system.assertEquals('Testing2',atmMap.get('222b').user.Name);
        
        Test.startTest();
            MassUpdateAccountBatch job = new MassUpdateAccountBatch();
            Database.executeBatch(job);
        Test.stopTest();
        
        Account ab =[Select id,Name,AISR__c,QP__c,Market_Segment__c,Market_Sub_Segment__c,DTN_Makeup__c from Account where name='myAccount' limit 1];
        system.debug(loggingLevel.Error,'-----------::'+ab);
        
        map<String,AccountTeamMember>atmMapa = new map<String,AccountTeamMember>();
        for(AccountTeamMember atm: [Select id,user.Name,user.DTN__c,TeamMemberRole from AccountTeamMember where accountid=:ab.id]){
            atmMapa.put(atm.user.DTN__c,atm);
        }
        system.debug(loggingLevel.Error,'-----atmMap------::'+atmMap);
        system.assertEquals('222c',ab.AISR__c);
        system.assertEquals('222d',ab.QP__c);
        //system.assertEquals(2,atmMapa.size());
        system.assertEquals('Testing3',atmMapa.get('222c').user.Name);
        system.assertEquals('Testing4',atmMapa.get('222d').user.Name);
        
        //verify the change on zipCodeDTN
        ZipCodeDTN__c zipCodeAfter = [Select id,Name,AISR__c,QP__c,IsUpdated__c from ZipCodeDTN__c where Name='55555' limit 1];
        system.assertEquals(false,zipCodeAfter.IsUpdated__c);
    }
}