wk_taa_taaqa/src/objects/AMS_Inventory_Rollup__c.object
<CustomObject>
    <fields>
        <fullName>AccountID__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AMS Inventory Rollups</relationshipLabel>
        <relationshipName>AMS_Inventory_Rollups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>AMS Inventory Rollup</label>
    <nameField>
        <label>AMS Inventory Rollup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AMS Inventory Rollups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/TestHasWorkpaperManagerTrigger.cls
@isTest 
private class TestHasWorkpaperManagerTrigger {

    static testMethod void insertAMSInventoryRollup() {
        Account A = new Account(
            Name = 'myAcct', 
            BillingStreet='25 Upland Drive',
            BillingPostalCode='94127',
            BillingCountry='United States',
            BillingCity='San Francisco' );
        insert A;
        
         
                
        
        
        user u = [select Id from user where lastname = 'Arno'];
AMS_Inventory_Rollup__c M = new AMS_Inventory_rollup__c(accountid__c =A.Id, name= '511000');
       
       insert M;
       
       delete M;
   
  AMS_Inventory_Rollup__c M1 = new AMS_Inventory_rollup__c(accountid__c =A.Id, name= '999999');
  
  insert M1;
        
     
         }
}