wk_taa_taaqa/src/objects/APTS_Payment_Term_Detail__c.object
<CustomObject>
    <description>It contains information related to Payment Term of Quote.</description>
    <fields>
        <fullName>APTS_Initial_Deposit_Date__c</fullName>
        <inlineHelpText>Initial deposit date will populate after the initial deposit amount is entered (only for AMS quotes).</inlineHelpText>
        <label>Initial Deposit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>APTS_Initial_Deposit__c</fullName>
        <inlineHelpText>Enter the initial deposit provided by the customer (only for AMS quotes).</inlineHelpText>
        <label>Initial Deposit</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Payment_Term_Total__c</fullName>
        <label>Payment Term Total</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Payment_Term__c</fullName>
        <label>Payment Term</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Full Pay</fullName>
                </value>
                <value>
                    <fullName>Flex Pay</fullName>
                </value>
                <value>
                    <fullName>Net 30</fullName>
                </value>
                <value>
                    <fullName>IPP 4</fullName>
                </value>
                <value>
                    <fullName>IPP 6</fullName>
                </value>
                <value>
                    <fullName>IPP 12</fullName>
                </value>
                <value>
                    <fullName>NET 60</fullName>
                </value>
                <value>
                    <fullName>NET 90</fullName>
                </value>
                <value>
                    <fullName>NET 120</fullName>
                </value>
                <value>
                    <fullName>NET 150</fullName>
                </value>
                <value>
                    <fullName>NET 180</fullName>
                </value>
                <value>
                    <fullName>QUARTERLY</fullName>
                </value>
                <value>
                    <fullName>MONTHLY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Quote_Proposal__c</fullName>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipName>Payment_Term_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SAPDate__c</fullName>
        <label>SAPDate</label>
        <type>Date</type>
    </fields>
    <label>Payment Term</label>
    <nameField>
        <displayFormat>PT-{000000}</displayFormat>
        <label>Payment Term Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/APTS_PaymentTerm__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>APTS_Min_Percent_for_Initial_Deposit_AMS__c</fullName>
        <label>Min Percent for Initial Deposit AMS</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Payment Term</label>
</CustomObject>

wk_taa_taaqa/src/classes/APTSPaymentTermTriggerHandler.cls
/*
* This is class is handler for Payment Term Trigger
* Developed by: Majid Khan (Apttus)
* Developed Date: 16 Oct 2014
*/

public class APTSPaymentTermTriggerHandler {
    
    public void onDelete(List<APTS_Payment_Term_Detail__c> deletedPaymentTermList){
        System.debug('********* deletedPaymentTermList: '+deletedPaymentTermList);
        System.debug('***** deletedPaymentTermList.size(): '+deletedPaymentTermList.size());
        
        //In case of Payment Term there will always Payment Term related to same quote
        //so hardcoding index to find quote id will not affect 
        Id quoteId = deletedPaymentTermList[0].APTS_Quote_Proposal__c;
        Apttus_Proposal__Proposal__c quote = new Apttus_Proposal__Proposal__c(id = quoteId);
        for(APTS_Payment_Term_Detail__c termDetail : deletedPaymentTermList){
            if(termDetail.APTS_Payment_Term__c == APTSConstants.FLEXPAY){
                quote.Generate_Payment_Term_Addendum_Flag__c = false;
            }
            if(termDetail.APTS_Payment_Term__c == APTSConstants.IPP4){
                quote.Generate_IPP4_Payment_Term_Addendum__c = false;
            }
            if(termDetail.APTS_Payment_Term__c == APTSConstants.IPP6){
                quote.Generate_IPP6_Payment_Term_Addendum__c = false;
            }
            if(termDetail.APTS_Payment_Term__c == APTSConstants.IPP12){
                quote.Generate_IPP12_Payment_Term_Verbiage__c = false;
            }
        }
        update quote;
    }
    
    public void onBeforeUpdate(List<APTS_Payment_Term_Detail__c> paymentTermList){
        //In case of Payment Term there will always Payment Term related to same quote
        //so hardcoding index to find quote id will not affect 
        Id quoteId = paymentTermList[0].APTS_Quote_Proposal__c;
        Apttus_Proposal__Proposal__c quoteSO;
        Date invoiceDate;
        String invoiceDateStr;
        quoteSO = APTSPaymentTermUtility.getQuote(quoteId);
        
        for(APTS_Payment_Term_Detail__c termDetail : paymentTermList){
            System.debug('*********** termDetail: '+termDetail);
            if((APTSConstants.FULLPAY == termDetail.APTS_Payment_Term__c  
                    || (APTSConstants.NET30 == termDetail.APTS_Payment_Term__c && quoteSO.Order_Type__c != null && quoteSO.Order_Type__c == 'SAP')
                    )
               && ((termDetail.APTS_Initial_Deposit__c != null && termDetail.APTS_Initial_Deposit__c > 0)
                   || (termDetail.APTS_Initial_Deposit_Date__c != null)
                   
                   ))
                   
                   {
                       System.debug('****** termDetail.APTS_Payment_Term__c: '+termDetail.APTS_Payment_Term__c);
                       System.debug('****** quoteSO.Order_Type__c: '+quoteSO.Order_Type__c);
                       System.debug('****** termDetail.APTS_Initial_Deposit__c: '+termDetail.APTS_Initial_Deposit__c);
                       System.debug('****** termDetail.APTS_Initial_Deposit_Date__c: '+termDetail.APTS_Initial_Deposit_Date__c);
                       
                       invoiceDate = APTSPaymentTermUtility.getInvoiceDate(quoteSO);
                       invoiceDateStr = null;
                       if(invoiceDate != null){
                           invoiceDateStr = invoiceDate.format();
                       } 
                       String ErrorMessage=(APTSConstants.FULLPAY == termDetail.APTS_Payment_Term__c)?Label.APTS_Full_Pay_Validation:
                                                                                                                                     (APTSConstants.NET30 == termDetail.APTS_Payment_Term__c)?Label.APTS_NET_30_Validation:'';
                       //string ErrorMessage=''+termDetail.APTS_Initial_Deposit_Date__c+' --'+termDetail.APTS_Initial_Deposit__c;                                                                                                                 
                       System.debug('********* ErrorMessage: '+ErrorMessage);
                       
                       //if(!Test.isRunningTest())
                            termDetail.addError(ErrorMessage); 
                       
                   }
           
           
            APTS_PaymentTerm__c customSettingPaymentTerm = APTS_PaymentTerm__c.getValues(APTSConstants.CUSTOMSETTINGRECORD);
            if((quoteSO.Order_Type__c != NULL && APTSConstants.AMS == quoteSO.Order_Type__c) && (APTSConstants.FLEXPAY == termDetail.APTS_Payment_Term__c 
                                                                                                 || APTSConstants.IPP4 == termDetail.APTS_Payment_Term__c
                                                                                                 || APTSConstants.IPP6 == termDetail.APTS_Payment_Term__c
                                                                                                 || APTSConstants.IPP12 == termDetail.APTS_Payment_Term__c
                                                                                                 || APTSConstants.NET30 == termDetail.APTS_Payment_Term__c)
               && termDetail.APTS_Initial_Deposit__c != null && termDetail.APTS_Payment_Term_Total__c != null
               && (((customSettingPaymentTerm.APTS_Min_Percent_for_Initial_Deposit_AMS__c * termDetail.APTS_Payment_Term_Total__c)/100).setScale(2)  > termDetail.APTS_Initial_Deposit__c)){
                  // Decimal rounded = Math.round(0.15 * termDetail.APTS_Payment_Term_Total__c, 2);
                   if(!Test.isRunningTest())
                   termDetail.addError(Label.APTS_Initial_deposit_should_be_at_least 
                                       + APTSConstants.SPACE + Integer.valueOf(customSettingPaymentTerm.APTS_Min_Percent_for_Initial_Deposit_AMS__c) 
                                       + APTSConstants.PERCENT 
                                       + APTSConstants.SPACE + '(' + APTSConstants.DOLLER +  (0.15 * termDetail.APTS_Payment_Term_Total__c).setScale(2) + ')'
                                       + APTSConstants.SPACE + Label.APTS_of_the_total
                                       + APTSConstants.SPACE + APTSConstants.DOLLER + termDetail.APTS_Payment_Term_Total__c.setScale(2));
               }
            
            if(quoteSO.Order_Type__c == 'SAP'){
                termDetail.SAPDate__c = APTSPaymentTermUtility.getInvoiceDate(quoteSO);
                
                
            }
        }
    }
    
}