wk_taa_taaqa/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Segment__c</fullName>
        <label>Business Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Corporate Direct (STG)</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Corporate Indirect (STG)</fullName>
                </value>
                <value>
                    <fullName>R&amp;L</fullName>
                </value>
                <value>
                    <fullName>Software (Corporate)</fullName>
                </value>
                <value>
                    <fullName>Software (Med &amp; Large)</fullName>
                </value>
                <value>
                    <fullName>US Small Firms</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Segment__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Audit and Accounting</fullName>
                </value>
                <value>
                    <fullName>Editorial</fullName>
                </value>
                <value>
                    <fullName>Learning</fullName>
                </value>
                <value>
                    <fullName>Professional Client Services (implementation, training, conversion)</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Workflow</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Sales411</fullName>
        <active>true</active>
        <businessProcess>Standard Case</businessProcess>
        <label>Sales411</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/TestCaseSales411Owner.cls
@isTest (SeeAllData = true)
private class TestCaseSales411Owner {

    static testMethod void insertCase() {
        Account a= [select Id from account where name = 'CCH INC. TECHNICAL SUPPORT-BOESCHEN'LIMIT 1];
        user u = [select Id from user where lastname = 'Arno'];
        RecordType RT = [select id from RecordType where name = 'Sales411'];
Case C = new Case(status='Received',RecordTypeId=RT.id,OwnerId=u.Id, Origin='Web',Subject='TestClass',Type='Pricing',business_segment__c='Software (Med & Large)',
Category__c='Tax',Description='TestClass',Accountid=A.Id);
 

       
       insert C;
   
          
     
         }
}