wk_taa_taaqa/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Software</fullName>
                </value>
                <value>
                    <fullName>Executives</fullName>
                </value>
                <value>
                    <fullName>Inside Sales</fullName>
                </value>
                <value>
                    <fullName>Global &amp; National Accounts</fullName>
                </value>
                <value>
                    <fullName>Research &amp; Learning</fullName>
                </value>
                <value>
                    <fullName>Sales Operations</fullName>
                </value>
                <value>
                    <fullName>Strategic &amp; Mid-Market</fullName>
                </value>
                <value>
                    <fullName>Solution Design</fullName>
                </value>
                <value>
                    <fullName>Training &amp; Consulting</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Sales411</fullName>
        <active>true</active>
        <businessProcess>Standard Case</businessProcess>
        <label>Sales411</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CostCenter__c</fullName>
        <label>Cost Center</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DTN__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>External Id for User</inlineHelpText>
        <label>DTN</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>High_Level_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Executives</fullName>
                    <color>#AFCADF</color>
                </value>
                <value>
                    <fullName>A&amp;A Solution Architects</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Admin</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Alliance</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Billing</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Books &amp; Journal Sales</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Central</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Central Division</fullName>
                    <color>#66E9BD</color>
                </value>
                <value>
                    <fullName>Corp. Solution Architects</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Corp National</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Corporate Business Development</fullName>
                    <color>#641CCF</color>
                </value>
                <value>
                    <fullName>Corporate Direct</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Corporate - SA</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Corporate Software</fullName>
                    <color>#F96FB7</color>
                </value>
                <value>
                    <fullName>Corp SW Energy &amp; Telco</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Corp SW Microsoft</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Corp SW SAP &amp; NetSuite</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>East - SA</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                    <color>#8F6429</color>
                </value>
                <value>
                    <fullName>Global Accounts</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                    <color>#EFAE73</color>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Mid-Atlantic</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Mountain Division</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>N2E Small Firm</fullName>
                </value>
                <value>
                    <fullName>N2N (GW) Small Firm</fullName>
                </value>
                <value>
                    <fullName>N2N (JA) Small Firm</fullName>
                </value>
                <value>
                    <fullName>N2N (LF) Small Firm</fullName>
                </value>
                <value>
                    <fullName>Northeast</fullName>
                    <color>#0B24BE</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>High_Level_Division__c</fullName>
        <label>High Level Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Software</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>National &amp; Strategic Accounts</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Research &amp; Learning</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Software</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>US Small Firms</fullName>
                    <color>#2F5D85</color>
                </value>
                <value>
                    <fullName>Executives</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Sales Operations</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Service Source</fullName>
                </value>
                <value>
                    <fullName>Solution Design</fullName>
                    <color>#66E9BD</color>
                </value>
                <value>
                    <fullName>Training &amp; Consulting</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Cap Gemini</fullName>
                </value>
                <value>
                    <fullName>Mid-Market</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Charge_To__c</fullName>
        <label>License Charge To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Product Development</fullName>
                </value>
                <value>
                    <fullName>Product Management</fullName>
                </value>
                <value>
                    <fullName>R&amp;L</fullName>
                </value>
                <value>
                    <fullName>R&amp;L Marketing</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>SVE</fullName>
                </value>
                <value>
                    <fullName>Training &amp; Consulting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/Testtrg_assignCaseRequestor.cls
@istest
Public class Testtrg_assignCaseRequestor
{
    public static testMethod void PopulateCaseRequestor()
    {
        test.starttest();
         Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
            User u = new User();
            u.Alias = 'standt2';
            u.Email='2standarduser@test.com'; 
            u.EmailEncodingKey='UTF-8'; 
            u.LastName='Testing1'; 
            u.LanguageLocaleKey='en_US';
            u.LocaleSidKey='en_US'; 
            u.ProfileId = p.Id; 
            u.TimeZoneSidKey='America/Los_Angeles'; 
            u.UserName='1standarduser@testorg.com';
            u.DTN__c='7787'; 
            u.High_Level_Division__c='Research and Learning';
            u.Division__c='Northeast';
            u.License_Charge_To__c='Sales';
            u.CostCenter__c='1110';
            insert u;
            
            Group G=[select Id from Group where Name = 'Sales411' and Type = 'Queue'];
            
            Case c = new Case();
            c.Status='Completed';
            c.Origin='Email';
            c.Subject='Sales411';
            c.Description='Test';
            c.SuppliedEmail='2standarduser@test.com';
            c.ownerId=G.id;
            insert c;
            
            test.stoptest();
            
    }
}