wk_taa_taaqa/src/objects/Custodial__c.object
<CustomObject>
    <description>Custody of Accounts if already existing representatives are switching.</description>
    <label>Custodial</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Custodial Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custodials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Monitoring_Log__c.object
<CustomObject>
    <description>This object is used to log informational and error messages - Currently for the Account Team Automation solution - ATA</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Monitoring Logs</relationshipLabel>
        <relationshipName>Monitoring_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apex_Job_ID__c</fullName>
        <description>Id of the batch job</description>
        <label>Apex Job ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <description>The class belong to exception.</description>
        <inlineHelpText>The class belong to exception.</inlineHelpText>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custodial__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Custodial</label>
        <referenceTo>Custodial__c</referenceTo>
        <relationshipLabel>Monitoring Logs</relationshipLabel>
        <relationshipName>Monitoring_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <description>The detail of exception.</description>
        <inlineHelpText>The detail of exception.</inlineHelpText>
        <label>Status Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <description>The method belong to exception.</description>
        <inlineHelpText>The method belong to exception.</inlineHelpText>
        <label>Apex Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Batch Job Result</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Monitoring Log</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monitoring Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/LoggerUtil.cls
public class LoggerUtil {

    public static Monitoring_Log__c createErrorRecord(String className, String controllerClass, String methodName, String detail){
        Monitoring_Log__c  er = new Monitoring_Log__c();
        er.Name = className;
        er.Class__c = controllerClass;
        er.Detail__c = detail;
        er.Method__c = methodName;
        return er;
    }
    
    /*
    @method : createMonitoringLog
    @parameters : String parameters processName, className, detail, methodName, record
    @Description : This method will create monitoring log
    */
    
    public static Monitoring_Log__c  createMonitoringLog(String processName, String className, String detail, String methodName, String accountId, String errorType){
        Monitoring_Log__c  er = new Monitoring_Log__c ();
        er.Name = processName;
        er.Class__c = className;
        er.Detail__c = detail;
        er.Method__c = methodName;
        er.Account__c = accountId;
        er.Type__c = errorType;
        return er;
    }
    
    public static Monitoring_Log__c  createBatchErrorRecord(String className, String controllerClass, String custodialid, String currentRepDtn,String newRepDTN, String custodialRepDTN, String detail,String type,String jobId){
        Monitoring_Log__c  er = new Monitoring_Log__c ();
        er.Name = className;
        er.Class__c = controllerClass;
        er.Detail__c = detail;
        //er.Method__c = methodName;
        //er.Current_Rep_DTN__c=currentRepDtn;
        er.Custodial__c=custodialid;
        //er.New_Rep_DTN__c=newRepDTN;
        er.Type__c=type;
        er.Apex_Job_ID__c= jobId;
        return er;
    }
    
     public static Monitoring_Log__c  createMonitoringLogWithTpe(String processName, String className, String detail, String methodName,String errorType){
        Monitoring_Log__c  er = new Monitoring_Log__c ();
        er.Name = processName;
        er.Class__c = className;
        er.Detail__c = detail;
        er.Method__c = methodName;
        er.Type__c = errorType;
        return er;
    }
    
     public static Monitoring_Log__c  createMonitoringLogWithBatchDetails(String processName, String className, String detail, String methodName, String accountId, String errorType,Id jobId){
        Monitoring_Log__c  er = new Monitoring_Log__c ();
        er.Name = processName;
        er.Class__c = className;
        er.Detail__c = detail;
        er.Method__c = methodName;
        er.Account__c = accountId;
        er.Type__c = errorType;
        er.Apex_Job_ID__c= jobId;
        return er;
        
    }
    
   public static Monitoring_Log__c createErrorRecordWithADM(String processName, String className, String detail, String methodName, String errorType,Id jobId){
        Monitoring_Log__c  er = new Monitoring_Log__c();
        er.Name = processName;
        er.Class__c = className;
        er.Detail__c = detail;
        er.Method__c = methodName;
        er.Type__c = errorType;
        er.Apex_Job_ID__c= jobId;
        return er;
    }
    
}