wk_taa_taaqa/src/objects/ERP_Order__c.object
<CustomObject>
    <description>Holds core data that is necessary for the ERP and downstream accounting systems. This object does not hold fulfillment or other data necessary for other system actions: license provisioning, printing, commissioning, etc.</description>
    <fields>
        <fullName>Order_Submission_Status__c</fullName>
        <description>Value is updated from Order submission process: Submitted means that the order is in transmission to the ERP.
Finalized / Complete means that the ERP accepted the Order and we received an ERP order Key. Order submission failed means retry count or queue timeouts have been exceeded - Manual intervention required for re-submission</description>
        <inlineHelpText>Submission Status across system tiers to ERP system of record.</inlineHelpText>
        <label>Order ERP Submission Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted To ERP</fullName>
                </value>
                <value>
                    <fullName>Finalized / Complete in ERP</fullName>
                </value>
                <value>
                    <fullName>Order Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Ready For Submission</fullName>
                </value>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending ERP Submission</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ERP Order</label>
    <nameField>
        <displayFormat>ORD-{00000000}</displayFormat>
        <label>ERP Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/EOI_ERPOrderTriggerHandler.cls
public with sharing class EOI_ERPOrderTriggerHandler 
{
	public void EOI_placeOrderToIIB()
	{
		List<Id> ERPOrderIdList = new List<Id>();
		for(ERP_Order__c currentERPOrder  : (List<ERP_Order__c>)Trigger.new)
		{
			if(((ERP_Order__c)Trigger.oldMap.get(currentERPOrder.Id)).Order_Submission_Status__c != 'Ready For Submission' && currentERPOrder.Order_Submission_Status__c == 'Ready For Submission')
				ERPOrderIdList.add(currentERPOrder.Id);
		}
		if(!ERPOrderIdList.isEmpty())
		{
			system.debug('Inside EOI_ERPOrderTriggerHandler :: '+ERPOrderIdList);
			EOI_OrderAutomation.EOI_PlaceOrder(ERPOrderIdList);
		}
	}
}