wk_taa_taaqa/src/objects/ERP_Order__c.object
<CustomObject>
    <description>Holds core data that is necessary for the ERP and downstream accounting systems. This object does not hold fulfillment or other data necessary for other system actions: license provisioning, printing, commissioning, etc.</description>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <description>Start date of an Annual Contract. This is the start date of the 1 Year full contract.</description>
        <label>Annual Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>ERP Order</label>
    <nameField>
        <displayFormat>ORD-{00000000}</displayFormat>
        <label>ERP Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/EOI_Test_OrderAutomationScheduler.cls
@isTest
private class EOI_Test_OrderAutomationScheduler 
{
    static testMethod void myUnitTest() 
    {
        //EOI_Test_QuoteProposalTriggerHandler.myUnitTest();
        //ERP_Order__c obj = new ERP_Order__c(Contract_Start_Date__c = System.Today());
        //insert obj;
        Test.startTest();
        EOI_OrderAutomationSchedular objScheduler = new EOI_OrderAutomationSchedular();
        //objScheduler.OrderId = obj.Id;
        String sch = '0 0 23 * * ?'; 
        system.schedule('Test Schedule', sch, objScheduler); 
        Test.stopTest();
    }
}