wk_taa_taaqa/src/objects/ERP_Order__c.object
<CustomObject>
    <description>Holds core data that is necessary for the ERP and downstream accounting systems. This object does not hold fulfillment or other data necessary for other system actions: license provisioning, printing, commissioning, etc.</description>
    <fields>
        <fullName>Order_Submission_Status__c</fullName>
        <description>Value is updated from Order submission process: Submitted means that the order is in transmission to the ERP.
Finalized / Complete means that the ERP accepted the Order and we received an ERP order Key. Order submission failed means retry count or queue timeouts have been exceeded - Manual intervention required for re-submission</description>
        <inlineHelpText>Submission Status across system tiers to ERP system of record.</inlineHelpText>
        <label>Order ERP Submission Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted To ERP</fullName>
                </value>
                <value>
                    <fullName>Finalized / Complete in ERP</fullName>
                </value>
                <value>
                    <fullName>Order Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Ready For Submission</fullName>
                </value>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Pending ERP Submission</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>ERP Orders</relationshipLabel>
        <relationshipName>ERP_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ERP Order</label>
    <nameField>
        <displayFormat>ORD-{00000000}</displayFormat>
        <label>ERP Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/ERP_Order_Line_Item__c.object
<CustomObject>
    <description>Holds order line item data that is necessary for the ERP and downstream accounting systems. This object does not hold fulfillment or other data necessary for other system actions: license provisioning, printing, commissioning, etc</description>
    <fields>
        <fullName>ERP_Order__c</fullName>
        <description>Parent Order object</description>
        <label>ERP Order</label>
        <referenceTo>ERP_Order__c</referenceTo>
        <relationshipLabel>ERP Order Line Items</relationshipLabel>
        <relationshipName>ERP_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ERP Order Line Item</label>
    <nameField>
        <displayFormat>OL-{0000000000}</displayFormat>
        <label>ERP Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/EOI_ERPOrderLineItemTriggerHandler.cls
public with sharing class EOI_ERPOrderLineItemTriggerHandler
{
    public void updateERPOrderStatus(List<ERP_Order_Line_Item__c> ERPOrderLineItemsList)
    {
        Set<Id> ERPOrderIds = new Set<Id>();
        Set<Id> QuoteProposalIds = new Set<Id>();
        List<ERP_Order__c> ERPOrderListToUpdate = new List<ERP_Order__c>();
        for(ERP_Order_Line_Item__c newLineItem : ERPOrderLineItemsList)
        {
            ERPOrderIds.add(newLineItem.ERP_Order__c);
        }
        system.debug('ERP Order Line item trigger ::  ERPOrderIds - '+ERPOrderIds);
        List<ERP_Order__c> ERPOrderRelatedToItems =  [SELECT Id, Proposal__c, (SELECT Id FROM ERP_Order_Line_Items__r) FROM ERP_Order__c WHERE Id in :ERPOrderIds];
        system.debug('ERP Order Line item trigger ::  ERPOrderRelatedToItems - '+ERPOrderRelatedToItems);
        for(ERP_Order__c currentERPOrder : ERPOrderRelatedToItems)
            QuoteProposalIds.add(currentERPOrder.Proposal__c);
        Map<Id, Apttus_Proposal__Proposal__c> QuoteProposalWithItems = new Map<Id,Apttus_Proposal__Proposal__c>([SELECT Id, (SELECT Id FROM R00N70000001yUfBEAU__r) FROM Apttus_Proposal__Proposal__c WHERE Id in :QuoteProposalIds]);
        system.debug('ERP Order Line item trigger ::  QuoteProposalWithItems - '+QuoteProposalWithItems);
        for(ERP_Order__c currentERPOrder : ERPOrderRelatedToItems)
        {
        	//#Would this condition ever occured? Do we need to log alert?
        	if(QuoteProposalWithItems.isEmpty() || QuoteProposalWithItems.get(currentERPOrder.Proposal__c).R00N70000001yUfBEAU.isEmpty())
        		break;
        	system.debug('ERP Order Line item trigger :: currentERPOrder.ERP_Order_Line_Items__r.size()'+currentERPOrder.ERP_Order_Line_Items__r.size());
        	system.debug('ERP Order Line item trigger :: QuoteProposalWithItems.get(currentERPOrder.Proposal__c).Proposal_Line_Items__r.size()'+QuoteProposalWithItems.get(currentERPOrder.Proposal__c).R00N70000001yUfBEAU__r.size());
            if((currentERPOrder.ERP_Order_Line_Items__r.isEmpty() && QuoteProposalWithItems.get(currentERPOrder.Proposal__c).R00N70000001yUfBEAU__r.isEmpty()) || currentERPOrder.ERP_Order_Line_Items__r.size() == QuoteProposalWithItems.get(currentERPOrder.Proposal__c).R00N70000001yUfBEAU__r.size())
            {
                ERP_Order__c newERPOrder = new ERP_Order__c(Id=currentERPOrder.Id, Order_Submission_Status__c='Ready For Submission');
                ERPOrderListToUpdate.add(newERPOrder);
            }
        }
        system.debug('ERP Order Line item trigger ::  ERPOrderListToUpdate - '+ERPOrderListToUpdate);
        system.debug('ERP Order not updated');
        if(!ERPOrderListToUpdate.isEmpty())
        {
            update ERPOrderListToUpdate;
            system.debug('ERP Order updated');
        }
        
    }
}