wk_taa_taaqa/src/objects/Monitoring_Log__c.object
<CustomObject>
    <description>This object is used to log informational and error messages - Currently for the Account Team Automation solution - ATA</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Monitoring Logs</relationshipLabel>
        <relationshipName>Monitoring_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <description>The class belong to exception.</description>
        <inlineHelpText>The class belong to exception.</inlineHelpText>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <description>The detail of exception.</description>
        <inlineHelpText>The detail of exception.</inlineHelpText>
        <label>Status Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <description>The method belong to exception.</description>
        <inlineHelpText>The method belong to exception.</inlineHelpText>
        <label>Apex Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Batch Job Result</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Monitoring Log</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monitoring Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/ATA_LogUtil.cls
/*--------------------------------------------------------------------------
 * Date       Author            Version      Description
 * -------------------------------------------------------------------------
 * 11/28/2017 SHIVAJI           1.0          ATA 2.0
 * ------------------------------------------------------------------------- */
public without sharing class ATA_LogUtil 
{
    //SMS - 1040 updated security model of class from with sharing to without sharing because of insufficient priviledges
    // **** Log Utility for ATA 2.0 functionality
    
    // *** utility method to instantiate the Monitoring_Log__c and return it    
    public static Monitoring_Log__c  createMonitoringLog(String processName, String className, String methodName, String detail, String accountId, String errorType)
    {
        Monitoring_Log__c  er = new Monitoring_Log__c();
        er.Name = processName;          // process name {'Account Team Automation'}             
        er.Class__c = className;        // class name
        er.Method__c = methodName;      // method name
        er.Detail__c = detail;          // detail
        er.Account__c = accountId;      // accountId
        er.Type__c = errorType;         // error type
        return er;
    }       
}