wk_taa_taaqa/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Software</fullName>
                </value>
                <value>
                    <fullName>Med/Large Software</fullName>
                </value>
                <value>
                    <fullName>Small Firm Software</fullName>
                </value>
                <value>
                    <fullName>Research &amp; Learning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <label>Product Sub-Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Product_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Specialty</fullName>
                </value>
                <value>
                    <fullName>iFirm</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Autoflow</fullName>
                </value>
                <value>
                    <fullName>Refunds Today</fullName>
                </value>
                <value>
                    <fullName>SFS Research &amp; Learning</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>AnswerConnect</fullName>
                </value>
                <value>
                    <fullName>Core Library - Corporate Tax</fullName>
                </value>
                <value>
                    <fullName>Core Library - CPA Professional</fullName>
                </value>
                <value>
                    <fullName>Federal Add On</fullName>
                </value>
                <value>
                    <fullName>State Add On</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Certificate Programs</fullName>
                </value>
                <value>
                    <fullName>Seminars</fullName>
                </value>
                <value>
                    <fullName>Books</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Database/Lookups/RADAR</fullName>
                </value>
                <value>
                    <fullName>POS Portal</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Sales Tax Load Utilities</fullName>
                </value>
                <value>
                    <fullName>Sales Tax Returns</fullName>
                </value>
                <value>
                    <fullName>Sales Tax SaaS Core</fullName>
                </value>
                <value>
                    <fullName>STO</fullName>
                </value>
                <value>
                    <fullName>SureTax - General</fullName>
                </value>
                <value>
                    <fullName>SureTax Professional Services</fullName>
                </value>
                <value>
                    <fullName>SureTax - Telco/Energy</fullName>
                </value>
                <value>
                    <fullName>Tax Interchange for Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Promotion__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies if the promotion is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Date from which this promotion becomes effective</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Date after which this promotion ceases to be effective</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promo_Code__c</fullName>
        <label>Promo Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/Quote_Promotion__c.object
<CustomObject>
    <fields>
        <fullName>Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Quote Promotions</relationshipLabel>
        <relationshipName>Quote_Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR 4) AND (5 OR 6)</booleanFilter>
            <errorMessage>Promotion does not match filter criteria.</errorMessage>
            <filterItems>
                <field>Promotion__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Price_List__c</field>
                <operation>equals</operation>
                <valueField>Promotion__c.Price_List__c</valueField>
            </filterItems>
            <filterItems>
                <field>Promotion__c.Effective_Date__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Promotion__c.Effective_Date__c</field>
                <operation>lessOrEqual</operation>
                <valueField>$Source.Today__c</valueField>
            </filterItems>
            <filterItems>
                <field>Promotion__c.Expiration_Date__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Promotion__c.Expiration_Date__c</field>
                <operation>greaterOrEqual</operation>
                <valueField>$Source.Today__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Quote Promotions</relationshipLabel>
        <relationshipName>Promotion_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Has_Others__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Will be checked by a W/F rule specific to a Promo.</description>
        <label>Quote Has Others</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote_Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipName>Promotion_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Promotion</label>
    <nameField>
        <displayFormat>QP-{00000}</displayFormat>
        <label>Quote Promotion ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/TestHasTeamMatePromotion.cls
@isTest
private class TestHasTeamMatePromotion{

static testMethod void insertPromotion() {

Account A = new Account(
            Name = 'myAcct', 
            BillingStreet='25 Upland Drive',
            BillingPostalCode='94127',
            BillingCountry='United States',
            BillingCity='San Francisco' );
        insert A;

 Opportunity O = new Opportunity(
        Name = 'TestOpp',
        accountId = A.Id,
        type = 'New to Existing',
        Closedate = Date.today().addYears(1),
        stagename = '1. Gain Access',
        product_category__c = 'Med/Large Software',
        Amount = 1.00,
        product_Sub_Category__c = 'Tax');
        insert O;

 Apttus_proposal__Proposal__c P = New Apttus_proposal__Proposal__c(
        apttus_proposal__Proposal_Name__c = 'O.Name',
        Apttus_Proposal__Account__c = A.id,
        Apttus_Proposal__Opportunity__c = O.Id,
        RecordTypeId = '012i0000001EOtUAAW',
        Apttus_QPConfig__PriceListId__c = 'a1fi0000000y6L5',
        sap_contact_channel__c = 'Field Sales Rep', 
        sap_sales_channel__c = 'Field Sales Rep',
        Auto_Renewal_SO_Compliance__c = 'Opt-In (OBR)');
        Insert P;
        
        Promotion__c Pr = New promotion__c(name = 'Teammate renewal', 
        promo_code__c = 'TMA', 
        active__c = true,
        price_list__c = 'a1fi0000000y6L5', 
        effective_date__c = Date.newInstance(2017, 1, 1), 
        expiration_date__c = Date.newInstance(2019, 12, 31));
        
        insert Pr;
        
  Quote_Promotion__c QP = New Quote_Promotion__c(
  quote_Proposal__C = p.Id, promotion__c = Pr.Id) ; 
  
  Insert QP ;
  
  QP.Quote_Has_Others__c = true;
  Update QP;
  Delete QP;
        
        
        }
        }