wk_taa_taaqa/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Reason__c</fullName>
        <label>Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Adding to Suite</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Add-on Sale</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Better Price</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>CCH Experience</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Competition - Content / Software issue</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Competition - Platform</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Competition - Price</fullName>
                    <color>#66E9BD</color>
                </value>
                <value>
                    <fullName>Competitive Conversion</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Combining contracts</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Conversion to Better Solution</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Converted By Mistake</fullName>
                    <color>#641CCF</color>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                    <color>#F96FB7</color>
                </value>
                <value>
                    <fullName>Features / Functionality</fullName>
                    <color>#2F5D85</color>
                </value>
                <value>
                    <fullName>Merger with non WK Firm</fullName>
                    <color>#AFCADF</color>
                </value>
                <value>
                    <fullName>Merger with WK Firm</fullName>
                    <color>#8F6429</color>
                </value>
                <value>
                    <fullName>No Decision</fullName>
                    <color>#EFAE73</color>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <color>#57F17C</color>
                </value>
                <value>
                    <fullName>Strong References</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Change effective dates</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Change in business - Bankrupt</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Change in business - Budget cuts</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Change in business - Business focus change</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Change in business - Personnel change</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Change in business - Went out of business</fullName>
                    <color>#66E9BD</color>
                </value>
                <value>
                    <fullName>Conversion - Step Down</fullName>
                    <color>#0B24BE</color>
                </value>
                <value>
                    <fullName>Conversion - Step Over</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Conversion - Step Up</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Correct order entry error</fullName>
                    <color>#641CCF</color>
                </value>
                <value>
                    <fullName>Credit dept cancel</fullName>
                    <color>#F96FB7</color>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                    <color>#2F5D85</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Competitor__c</fullName>
        <label>Competitor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AICPA</fullName>
                </value>
                <value>
                    <fullName>ATX</fullName>
                </value>
                <value>
                    <fullName>Avalara</fullName>
                </value>
                <value>
                    <fullName>BNA</fullName>
                </value>
                <value>
                    <fullName>Cambridge</fullName>
                </value>
                <value>
                    <fullName>Caseware</fullName>
                </value>
                <value>
                    <fullName>Cengage Learning</fullName>
                </value>
                <value>
                    <fullName>Corptax</fullName>
                </value>
                <value>
                    <fullName>Crosslink</fullName>
                </value>
                <value>
                    <fullName>Drake</fullName>
                </value>
                <value>
                    <fullName>Ichannel</fullName>
                </value>
                <value>
                    <fullName>Intuit - Lacerte</fullName>
                </value>
                <value>
                    <fullName>Intuit - Proseries</fullName>
                </value>
                <value>
                    <fullName>Intuit - Tax Online</fullName>
                </value>
                <value>
                    <fullName>McGraw-Hill</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pearson Educational (Formerly PH)</fullName>
                </value>
                <value>
                    <fullName>PFX Merger</fullName>
                </value>
                <value>
                    <fullName>SurePrep</fullName>
                </value>
                <value>
                    <fullName>TaxSlayer</fullName>
                </value>
                <value>
                    <fullName>Taxware</fullName>
                </value>
                <value>
                    <fullName>Thomson</fullName>
                </value>
                <value>
                    <fullName>Thomson - GoSystem</fullName>
                </value>
                <value>
                    <fullName>Thomson – Ultratax</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Vertex</fullName>
                </value>
                <value>
                    <fullName>Wiley Publishing</fullName>
                </value>
                <value>
                    <fullName>XCM Solution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Forecast_Type__c</fullName>
        <label>Forecast Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Low (&lt;50%)</fullName>
                    <color>#DDDDDD</color>
                </value>
                <value>
                    <fullName>Medium (50-90%)</fullName>
                    <color>#FF9900</color>
                </value>
                <value>
                    <fullName>High (&gt;90%)</fullName>
                    <color>#B6E32E</color>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <color>#419249</color>
                </value>
                <value>
                    <fullName>Omitted</fullName>
                    <color>#A53711</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Closed_Reason__c</fullName>
        <label>Other Closed Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Other_Competitor__c</fullName>
        <label>Other Competitor</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Software</fullName>
                </value>
                <value>
                    <fullName>Med/Large Software</fullName>
                </value>
                <value>
                    <fullName>Small Firm Software</fullName>
                </value>
                <value>
                    <fullName>Research &amp; Learning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <label>Product Sub-Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Product_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Specialty</fullName>
                </value>
                <value>
                    <fullName>iFirm</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Autoflow</fullName>
                </value>
                <value>
                    <fullName>Refunds Today</fullName>
                </value>
                <value>
                    <fullName>SFS Research &amp; Learning</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>AnswerConnect</fullName>
                </value>
                <value>
                    <fullName>Core Library - Corporate Tax</fullName>
                </value>
                <value>
                    <fullName>Core Library - CPA Professional</fullName>
                </value>
                <value>
                    <fullName>Federal Add On</fullName>
                </value>
                <value>
                    <fullName>State Add On</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Certificate Programs</fullName>
                </value>
                <value>
                    <fullName>Seminars</fullName>
                </value>
                <value>
                    <fullName>Books</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Database/Lookups/RADAR</fullName>
                </value>
                <value>
                    <fullName>POS Portal</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Sales Tax Load Utilities</fullName>
                </value>
                <value>
                    <fullName>Sales Tax Returns</fullName>
                </value>
                <value>
                    <fullName>Sales Tax SaaS Core</fullName>
                </value>
                <value>
                    <fullName>STO</fullName>
                </value>
                <value>
                    <fullName>SureTax - General</fullName>
                </value>
                <value>
                    <fullName>SureTax Professional Services</fullName>
                </value>
                <value>
                    <fullName>SureTax - Telco/Energy</fullName>
                </value>
                <value>
                    <fullName>Tax Interchange for Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_Details_Other_Reason__c</fullName>
        <inlineHelpText>Required when deal is Closed Lost and Closed Reason = Other. Can also be used to track additional details of why the deal was lost.</inlineHelpText>
        <label>Reason Details/Other Reason</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFS_Opportunity_ID__c</fullName>
        <externalId>true</externalId>
        <label>SFS Opportunity Record ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFS_Primary_Quote_ID_18__c</fullName>
        <description>SFS SF ID</description>
        <label>SFS Primary Quote ID (18)</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SteelBrick_Quote__c</fullName>
        <label>SteelBrick Quote #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TAA_Opportunity_Owner_Id__c</fullName>
        <label>TAA Opportunity Owner Id</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/S2S_LogFile__c.object
<CustomObject>
    <label>API LogFile</label>
    <nameField>
        <displayFormat>S2S-{0000}</displayFormat>
        <label>S2S LogFile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API LogFiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/S2S_Opp_Delete.cls
@RestResource(urlMapping='/OpportunityDeletion/*')  
 global with sharing class S2S_Opp_Delete{  
  /*  
   HttpPost method is used to capture a HttpPost request has been sent to our rest apex class.  
   Used to retrieve data coming in the request body and performing corressponding actions  
  */  
  
  @HttpPost  
   global static Id doPost() {  
     /*  
       RestContext Class - Allows us to access the RestRequest and RestResponse objects in your Apex REST methods.   
       RestRequest class - Allows us to pass request data into our Apex RESTful Web service method.  
       RestResponse class - Allows us to pass or send back response data from our Apex RESTful web service method  
     */  
     //Returns the RestRequest object for our Apex REST method.  
     RestRequest request = RestContext.request;  
     //Returns the RestResponse for our Apex REST method.  
     RestResponse response = RestContext.response;  
     
     //Access the request body with input data coming in the JSON format  
      Blob body = request.requestBody;  
      Datetime stsrttime;
       stsrttime = Datetime.now();
      Integer seconds = stsrttime.second();
      S2S_OppUtil obj;
      String strRequest;
      
       try{
           
      obj = S2S_OppUtil.parse(body.toString());
      List<S2S_OppUtil.opps> setOpplines= new List<S2S_OppUtil.opps> ();
      
       
       setOpplines=obj.opps;
       
       
       strRequest = JSON.serialize(obj);
       
      
           setOpplines=obj.opps;
           Processlines(setOpplines,strRequest,stsrttime ,seconds  );
           
         }catch(Exception e){
         
          String Msg='Something Went wrong'+e.getMessage()+e.getLineNumber()+e.getStackTraceString();
           System.debug('Request here is'+Msg);
                    
               List<S2S_LogFile__c > logList = new List<S2S_LogFile__c >();   logList.add(S2S_Util.prepareLogEntry('Opp Del',strRequest ,null,null,'TAA',Msg,500,stsrttime,seconds)); 
                if(!logList.isEmpty()) Database.insert(logList, false);
            
         }
       
       
       
      System.debug('Request here is'+obj);
      
      
       
      //String Msg='Something Went wrong'+e.getMessage()+e.getLineNumber()+e.getStackTraceString();
                  List<S2S_LogFile__c > logList = new List<S2S_LogFile__c >();    
                logList.add(S2S_Util.prepareLogEntry('Opp Del',strRequest ,null,null,'TAA','Success',201,stsrttime,seconds)); 
                if(!logList.isEmpty())
                Database.insert(logList, false);
                
      return null;
      }
   
   
   Public Static void Processlines(List<S2S_OppUtil.opps> x,String jsn,DateTime stsrttime,Integer seconds){
   
     
    
        
         List<Opportunity> itemsToUpdate = new List<Opportunity>();
          Set<String> oppItemIds = new Set<String>();
        Map<String, S2S_OppUtil.opps> processMap = new Map<String,S2S_OppUtil.opps>();
        
        for(S2S_OppUtil.opps tsp : x){
        
           System.debug('Request here is'+tsp);
            if(tsp.TAAOppRecordId != null && tsp.SFSOppRecordId != null  ) {
              
              oppItemIds.add(tsp.TAAOppRecordId.substring(0,18));
              processMap.put(tsp.TAAOppRecordId.substring(0,18), tsp);
                System.debug('Request here is'+tsp);
                System.debug('maphere is'+processMap);
                
            }    
        
        }
        
        List<Opportunity> oppys ;
        
        if(!Test.isRunningTest()){
         oppys = [SELECT Id, Amount, StageName, CloseDate,Closed_Reason__c,Reason_Details_Other_Reason__c,Competitor__c,Other_Competitor__c,Other_Closed_Reason__c,
                                      Forecast_Type__c,SFS_Opportunity_ID__c,SFS_Primary_Quote_ID_18__c,SteelBrick_Quote__c,TAA_Opportunity_Owner_ID__c,Name,Type,Product_Category__c,Product_Sub_Category__c     
                                      FROM Opportunity 
                                      WHERE Id IN :oppItemIds];
        }else{
        oppys = [SELECT Id, Amount, StageName, CloseDate,Closed_Reason__c,Reason_Details_Other_Reason__c,Competitor__c,Other_Competitor__c,Other_Closed_Reason__c,
                                      Forecast_Type__c,SFS_Opportunity_ID__c,SFS_Primary_Quote_ID_18__c,SteelBrick_Quote__c,TAA_Opportunity_Owner_ID__c,Name,Type,Product_Category__c,Product_Sub_Category__c     
                                      FROM Opportunity ];
        System.debug('Request here is'+oppys );
        }                
                      
       
        
     
         if(!oppys.isEmpty()) {
            try {
                Database.delete(oppys , false); 
            } catch(DmlException e) {
              
               String Msg='Something Went wrong'+e.getMessage()+e.getLineNumber()+e.getStackTraceString();
                     
                 List<S2S_LogFile__c > logList = new List<S2S_LogFile__c >(); logList.add(S2S_Util.prepareLogEntry('Opp Del',jsn,null,null,'TAA',Msg,500,stsrttime,seconds)); 
                if(!logList.isEmpty()) Database.insert(logList, false);
            }
     
          }
   
       }
   
   
   
 }