wk_taa_taaqa/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CPQ_Quote__c</fullName>
        <description>Selection for Apttus or Steelbrick Product Sets</description>
        <label>CPQ System</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Apttus</fullName>
                </value>
                <value>
                    <fullName>Steelbrick</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact_for_Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact(for Proposal)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SFS_Opportunity_ID__c</fullName>
        <externalId>true</externalId>
        <label>SFS Opportunity Record ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/TSM_Custom_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>TSM custom settings for configuration</description>
    <fields>
        <fullName>ConnectionName__c</fullName>
        <label>ConnectionName</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFS_Base_URL__c</fullName>
        <label>SFS_Base_URL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>TSM_Custom_Settings</label>
</CustomObject>

wk_taa_taaqa/src/objects/TSM_Trigger_Control__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is to set the trigger on/off switch for TSM specific triggers.</description>
    <fields>
        <fullName>TriggerOff__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TriggerOff</label>
        <type>Checkbox</type>
    </fields>
    <label>TSM Trigger Control</label>
</CustomObject>

wk_taa_taaqa/src/classes/TestRepliMonitorLogsUpdateBatch.cls
@isTest
public class TestRepliMonitorLogsUpdateBatch 
{
    @testsetup static void startup()
	{
        TSM_Custom_Settings__c config = new TSM_Custom_Settings__c();
        config.ConnectionName__c = 'CCH SFS';
        config.SFS_Base_URL__c = 'https://wksfs--qa.cs61.my.salesforce.com';
        insert config;
        
        List<TSM_Trigger_Control__c> controlList = new List<TSM_Trigger_Control__c>();
        controlList.add(new TSM_Trigger_Control__c(Name = 'Account', TriggerOff__c = false));
        controlList.add(new TSM_Trigger_Control__c(Name='Contact', TriggerOff__c = false));
        controlList.add(new TSM_Trigger_Control__c(Name='Opportunity', TriggerOff__c = false));
        insert controlList;        

        // insert new accounts and contacts for data
        List<Account> accounts = TSM_TestDataUtil.createAccounts(1,1,0,false);
        List<Account> acctsExt = [SELECT Id FROM Account];
        List<Contact> contsExt = [SELECT Id FROM Contact];
        List<Opportunity> opps = new List<Opportunity>();
        for(Integer i = 0; i < 2; i++){
        	opps.add(new Opportunity(StageName = '1. Gain Accesss', CloseDate = System.today()+30,
                                       AccountId = acctsExt[0].Id, Name = 'TrigOpptyTest' + i,
                                       Primary_Contact_for_Proposal__c = contsExt[0].Id,
                                       CPQ_Quote__c = 'Steelbrick', SFS_Opportunity_ID__c = '0062100000F2xA' + i));  
        }
        insert opps;
	}
	
	@isTest
    static void testBatch() 
    {
    	Test.startTest();
    	RepliMonitorLogsUpdateBatchScheduler obj = new RepliMonitorLogsUpdateBatchScheduler();
		String sch = '0 0 23 * * ?'; 
		system.schedule('Test Replication Monitor Logs Update Check', sch, obj); 
		Test.stopTest();
    }
}