wk_taa_taaqa/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Software</fullName>
                </value>
                <value>
                    <fullName>Med/Large Software</fullName>
                </value>
                <value>
                    <fullName>Small Firm Software</fullName>
                </value>
                <value>
                    <fullName>Research &amp; Learning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <label>Product Sub-Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Product_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Specialty</fullName>
                </value>
                <value>
                    <fullName>iFirm</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Autoflow</fullName>
                </value>
                <value>
                    <fullName>Refunds Today</fullName>
                </value>
                <value>
                    <fullName>SFS Research &amp; Learning</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>AnswerConnect</fullName>
                </value>
                <value>
                    <fullName>Core Library - Corporate Tax</fullName>
                </value>
                <value>
                    <fullName>Core Library - CPA Professional</fullName>
                </value>
                <value>
                    <fullName>Federal Add On</fullName>
                </value>
                <value>
                    <fullName>State Add On</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Certificate Programs</fullName>
                </value>
                <value>
                    <fullName>Seminars</fullName>
                </value>
                <value>
                    <fullName>Books</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Database/Lookups/RADAR</fullName>
                </value>
                <value>
                    <fullName>POS Portal</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Sales Tax Load Utilities</fullName>
                </value>
                <value>
                    <fullName>Sales Tax Returns</fullName>
                </value>
                <value>
                    <fullName>Sales Tax SaaS Core</fullName>
                </value>
                <value>
                    <fullName>STO</fullName>
                </value>
                <value>
                    <fullName>SureTax - General</fullName>
                </value>
                <value>
                    <fullName>SureTax Professional Services</fullName>
                </value>
                <value>
                    <fullName>SureTax - Telco/Energy</fullName>
                </value>
                <value>
                    <fullName>Tax Interchange for Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/TeamMemberRoleOppUpdateTest.cls
@isTest  
private class TeamMemberRoleOppUpdateTest {

    static testMethod void validateTeamMemberRoleOppUpdate() {
    
     Account A = new Account(
            Name = 'myAcct', 
            BillingStreet='25 Upland Drive',
            BillingPostalCode='94127',
            BillingCountry='United States',
            BillingCity='San Francisco' );
        insert A;

 Opportunity O = new Opportunity(
        Name = 'TestOpp',
        accountId = A.Id,
        type = 'New to Existing',
        Closedate = Date.today().addYears(1),
        stagename = '1. Gain Access',
        product_category__c = 'Med/Large Software',
        Amount = 1.00,
        product_Sub_Category__c = 'Tax');
        insert O;
        
OpportunityTeamMember M = new OpportunityTeamMember(opportunityid =o.Id, UserID= '005i0000004TuQ0AAK', TeamMemberRole = 'ASR - Research and Learning');
 

      
       insert M;
    
       
    }
}