wk_taa_taaqa/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact_Email__c</fullName>
        <label>Primary Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_Phone__c</fullName>
        <label>Primary Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_for_Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact(for Proposal)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/oppContactRoleHelper.cls
public with sharing class oppContactRoleHelper {
	public static string debugString{get;set;}
	public class UserException Extends Exception{}
    public Opportunity opp;
    public oppContactRoleHelper( ApexPages.StandardController stdController ) {
        opp = ( Opportunity )stdController.getRecord();        
    }
    public void rollupOppContacts(){
        oppContactRoleHelper.rollupOppContactsFuture( opp.Id );    
    }
    //@future 
    public static void rollupOppContactsFuture( Id oppId ) {
        Contact[] contactList = [ SELECT Id,email,phone,name
                                  
                                  FROM Contact
                             WHERE Id IN ( SELECT ContactId FROM OpportunityContactRole
                                         WHERE OpportunityId = :oppId and IsPrimary=true ) ];
        Opportunity opp = [ SELECT Id 
                            ,Primary_Contact_for_Proposal__c 
                            FROM Opportunity WHERE Id = :oppId ];
        
        boolean requireOppUpdate = false;
        //opp.Primary_Contact_for_Proposal__c=null;
        //throw new UserException('no contact');
        for( Contact contact : contactList ) {
        	debugString='Opportunity Primary Contact:'+opp.Primary_Contact_for_Proposal__c+'-- Contact Id'+Contact.id;
        	if(contact.id==opp.Primary_Contact_for_Proposal__c)
        	   return;        	
            opp.Primary_Contact_for_Proposal__c=contact.id;
            //opp.Primary_Contact_Email__c=contact.email;
            //opp.Primary_Contact_Phone__c=contact.phone;
            //opp.Primary_Contact_Name__c=contact.name;
            requireOppUpdate = true;
        }

        if(requireOppUpdate) 
        update opp;
    }


}