wk_taa_taaqa/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ACRO__c</fullName>
        <label>ACRO</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PAC_Code__c</fullName>
        <label>PAC Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>BCN</fullName>
                </value>
                <value>
                    <fullName>BCR</fullName>
                </value>
                <value>
                    <fullName>BGB</fullName>
                </value>
                <value>
                    <fullName>BNH</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>FAB</fullName>
                </value>
                <value>
                    <fullName>FSS</fullName>
                </value>
                <value>
                    <fullName>LSS</fullName>
                </value>
                <value>
                    <fullName>TAI</fullName>
                </value>
                <value>
                    <fullName>TAS</fullName>
                </value>
                <value>
                    <fullName>TAT</fullName>
                </value>
                <value>
                    <fullName>TNS</fullName>
                </value>
                <value>
                    <fullName>TRM</fullName>
                </value>
                <value>
                    <fullName>TST</fullName>
                </value>
                <value>
                    <fullName>WSB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Special_Instructions__c</fullName>
        <label>Special Instructions</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/APTS_CopyFormattedDescriptionTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 *  
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public with sharing class APTS_CopyFormattedDescriptionTest {
	static testmethod void testFormatDescription() {
			Product2 prod1 = new Product2(Name = 'Test Product1', Special_Instructions__c = 'Instructions1' , 
                                          ACRO__c = '4573', PAC_Code__c = '2452');
			
			insert prod1;
	} 
}