wk_taa_taaqa/src/objects/ReplicationMonitoringLog__c.object
<CustomObject>
    <fields>
        <fullName>ObjectID__c</fullName>
        <label>ObjectID</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PartnerNetworkRecord_StartDate__c</fullName>
        <description>This field will hold Date / Time stamp from Partner Network Record reference to calculate the round trip time</description>
        <label>PartnerNetworkRecord_StartDate</label>
        <type>DateTime</type>
    </fields>
    <label>ReplicationMonitoringLog</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>ReplicationMonitoringLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ReplicationMonitoringLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/classes/RepliMonitorLogsUpdateBatch.cls
public class RepliMonitorLogsUpdateBatch implements Database.Batchable<sObject>
{
	public Database.QueryLocator start(Database.BatchableContext BC)
	{
		return Database.getQueryLocator(QueryServiceClass.getReplicationMonitorLogQuery());
   	}

	public void execute(Database.BatchableContext BC, List<ReplicationMonitoringLog__c> scope)
	{
		List<ReplicationMonitoringLog__c> lstUpdateReplMonLog = new List<ReplicationMonitoringLog__c>(); 
		Set<Id> setReplMonLogsId = new Set<Id>();
		Map<Id, ReplicationMonitoringLog__c> mapReplicationMonLogs = new Map<Id, ReplicationMonitoringLog__c>();
		for(ReplicationMonitoringLog__c obj : scope){
			if(obj.ObjectID__c != NULL){
				setReplMonLogsId.add(obj.ObjectID__c);
				mapReplicationMonLogs.put(obj.ObjectID__c, obj);	
			}
		}
		
		Map<Id, PartnerNetworkRecordConnection> mapPartNwCon = new Map<Id, PartnerNetworkRecordConnection>([SELECT Id, LocalRecordId, StartDate, PartnerRecordId, Status FROM PartnerNetworkRecordConnection WHERE ID IN: setReplMonLogsId]);
		
		for(Id objId : mapReplicationMonLogs.keySet()){
			if(mapPartNwCon != NULL && mapPartNwCon.get(objId) != NULL){
				mapReplicationMonLogs.get(objId).PartnerNetworkRecord_StartDate__c = mapPartNwCon.get(objId).StartDate;
				lstUpdateReplMonLog.add(mapReplicationMonLogs.get(objId));	
			}
		}
		
		if(lstUpdateReplMonLog != NULL && lstUpdateReplMonLog.size() > 0)
		{
			upsert lstUpdateReplMonLog;
		}
    }

   	public void finish(Database.BatchableContext BC)
   	{
   	}   
}