wk_taa_taaqa/src/objects/S2S_LogFile__c.object
<CustomObject>
    <fields>
        <fullName>API_Request_Time__c</fullName>
        <label>API Request Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>API_Request_Time_sec__c</fullName>
        <label>API Request Time(sec)</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>API_Response_Code__c</fullName>
        <label>API Response Code</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>API_Response_Time__c</fullName>
        <label>API Response Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>API_Response_Time_sec__c</fullName>
        <label>API Response Time(sec)</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>API_Response__c</fullName>
        <label>API Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>API_Type__c</fullName>
        <label>API Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PFX Book Promo</fullName>
                </value>
                <value>
                    <fullName>One Force</fullName>
                </value>
                <value>
                    <fullName>S2S</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Log_Info__c</fullName>
        <label>Request Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>S2S_LogFiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>S2S_LogFiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ML</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>SFS</fullName>
                </value>
                <value>
                    <fullName>TAA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>API LogFile</label>
    <nameField>
        <displayFormat>S2S-{0000}</displayFormat>
        <label>S2S LogFile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API LogFiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/S2S_Trigger_Control__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is to set the trigger on/off switch for S2S specific triggers.</description>
    <fields>
        <fullName>TriggerOff__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TriggerOff</label>
        <type>Checkbox</type>
    </fields>
    <label>S2S Trigger Control</label>
</CustomObject>

wk_taa_taaqa/src/classes/S2S_Util.cls
public class S2S_Util {
  
    
    
    // prepare the app log record
    public static S2S_LogFile__c prepareLogEntry(String apiType, String info, String accId, String oppId, String surc,String rsp, Integer rspcode,DateTime rqsttm,Integer rqsec) {
        S2S_LogFile__c logEntry = new S2S_LogFile__c();
        logEntry.API_Type__c= apiType;
        logEntry.Log_Info__c= info;
        logEntry.Related_Account__c= accId;
        logEntry.Related_Opportunity__c= oppId;
        logEntry.Source__c= surc;
        
        logEntry.API_Request_Time__c=rqsttm;
        logEntry.API_Response_Time__c=Datetime.now();
        logEntry.API_Request_Time_sec__c=String.valueof(rqsec);
        logEntry.API_Response_Time_sec__c=String.valueof(logEntry.API_Response_Time__c.second());
                       
        logEntry.API_Response__c= rsp;
        logEntry.API_Response_Code__c= rspcode;
        return logEntry;
    }
    
    // utility method for fetching the trigger off flag for each object
    public static Boolean fetchTriggerOffFlag(String objName) {
        Map<String, S2S_Trigger_Control__c> controlMap = S2S_Trigger_Control__c.getAll();
        Boolean isTriggerOff = false;
        if(!controlMap.isEmpty() && controlMap.containsKey(objName)) {
            isTriggerOff = controlMap.get(objName).TriggerOff__c;
        }
        return isTriggerOff;
    }
}