wk_taa_taaqa/src/objects/Solution.object
<CustomObject>
    <fields>
        <fullName>Business_Segment__c</fullName>
        <label>Business Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Indirect (STG)</fullName>
                </value>
                <value>
                    <fullName>R&amp;L</fullName>
                </value>
                <value>
                    <fullName>Software (Corporate)</fullName>
                </value>
                <value>
                    <fullName>Software (CPA)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Audit and Accounting</fullName>
                </value>
                <value>
                    <fullName>Workflow</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Learning</fullName>
                </value>
                <value>
                    <fullName>Professional Client Services (implementation, training, conversion)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Products</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Segment__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Active Data</fullName>
                </value>
                <value>
                    <fullName>AnswerConnect</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>Autoflow</fullName>
                </value>
                <value>
                    <fullName>Axcess Document</fullName>
                </value>
                <value>
                    <fullName>Axcess Practice</fullName>
                </value>
                <value>
                    <fullName>Axcess Tax</fullName>
                </value>
                <value>
                    <fullName>Ax - Doc</fullName>
                </value>
                <value>
                    <fullName>Ax - Other</fullName>
                </value>
                <value>
                    <fullName>Ax - Portal</fullName>
                </value>
                <value>
                    <fullName>Ax - Practice</fullName>
                </value>
                <value>
                    <fullName>Ax Suite</fullName>
                </value>
                <value>
                    <fullName>Ax - Tax</fullName>
                </value>
                <value>
                    <fullName>Ax - WS</fullName>
                </value>
                <value>
                    <fullName>CCH Axcess Document</fullName>
                </value>
                <value>
                    <fullName>Client Relate</fullName>
                </value>
                <value>
                    <fullName>Code Connect</fullName>
                </value>
                <value>
                    <fullName>Compliance Services</fullName>
                </value>
                <value>
                    <fullName>Corp - Direct</fullName>
                </value>
                <value>
                    <fullName>Corp - Indirect</fullName>
                </value>
                <value>
                    <fullName>Database</fullName>
                </value>
                <value>
                    <fullName>Eng &amp; KC</fullName>
                </value>
                <value>
                    <fullName>Engagement</fullName>
                </value>
                <value>
                    <fullName>Fixed Assets</fullName>
                </value>
                <value>
                    <fullName>Intelliconnect</fullName>
                </value>
                <value>
                    <fullName>Knowledge Coach</fullName>
                </value>
                <value>
                    <fullName>Multi State Tax</fullName>
                </value>
                <value>
                    <fullName>PDFlyer</fullName>
                </value>
                <value>
                    <fullName>Pfx - Doc</fullName>
                </value>
                <value>
                    <fullName>PFX Document</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Professional_Client_Services__c</fullName>
        <label>Topics</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Audit and Accounting</fullName>
                </value>
                <value>
                    <fullName>CCH Axcess Document</fullName>
                </value>
                <value>
                    <fullName>Competition</fullName>
                </value>
                <value>
                    <fullName>Deal Coaching</fullName>
                </value>
                <value>
                    <fullName>Help with Sales Process</fullName>
                </value>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>Order Validation and Scheduling</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Product Functionality</fullName>
                </value>
                <value>
                    <fullName>Professional Service Calculator</fullName>
                </value>
                <value>
                    <fullName>ProServ Conversions</fullName>
                </value>
                <value>
                    <fullName>Request for assistance on a sales call</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>Service Recommendations</fullName>
                </value>
                <value>
                    <fullName>Statements of Work</fullName>
                </value>
                <value>
                    <fullName>System Requirements</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Tax Conversions</fullName>
                </value>
                <value>
                    <fullName>Technical Requirements</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Workflow</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

wk_taa_taaqa/src/classes/searchSolutionController.cls
public with sharing class searchSolutionController {
    public String searchString {get; set;}
    public Integer offsetCounter{get; set;}
    public Integer pageSize{get;set;}
    public Integer listSize{get;set;}
    private ApexPages.StandardController controller {get; set;}

    public List<Solution>solutionList = new List<Solution>();
    public List<Solution>getsolutionList(){
     System.debug('Getter is called'+solutionList.size());
     return solutionList ;
    }
    public void setsolutionList(List<Solution> solutionList){
     this.solutionList= solutionList;
    }
    public Boolean isFilterOn{get; set;}
    public String product {get; set;}
    public String category {get; set;}
    public String businessSegment {get; set;}
    public String professionalClientServicesTopics {get; set;}
    public Boolean isSearchStringblank{get; set;}
    
    
    public searchSolutionController(ApexPages.StandardController controller) {
    this.controller= controller;
     isSearchStringblank= true;
     offsetCounter=0;
     isFilterOn= false;
     pageSize=2;
    }
    public void findSolution(){
      isSearchStringblank= true;
     if(String.isNotBlank(searchString)&& searchString.length()>2){
        System.debug('Value of offset Counter>>>>>>>>>>'+offsetCounter);
        System.debug('Value for Search String to be searched==='+searchString);
        isSearchStringblank= false;
     String applyFilter =''; 
     //System.debug('????????????????Sol Business Segment????????????????'+ sol.Business_Segment__c);
     if((String.isBlank(product)|| product.equals('--None--')) && (String.isBlank(category)|| category.equals('--None--')) && (String.isBlank(businessSegment)|| businessSegment.equals('--None--'))&& (String.isBlank(professionalClientServicesTopics)||professionalClientServicesTopics.equals('--None--'))){
       isFilterOn= false;
     }else{
      isFilterOn= true;
     }
     if(isFilterOn){
        System.debug('??????????Filter is on???????????');
       if(String.isnotBlank(product)&& product!='--None--')
         applyFilter+= ( applyFilter=='' ? 'Where' : 'AND' )+ ' '+'Products__c=' + '\''+product+'\''; 
       if(String.isNotBlank(category)&& category!='--None--')
         applyFilter+= ( applyFilter=='' ? 'Where' : 'AND') + ' ' + 'Category__c = '+ '\''+category+'\'';
       if(String.isNotBlank(businessSegment) &&  businessSegment!='--None--')  
        applyFilter+= (applyFilter=='' ? 'Where': 'AND') + ' '+  'Business_Segment__c='+'\''+businessSegment+'\'' ;
       if(String.isNotBlank(professionalClientServicesTopics ) && professionalClientServicesTopics!='--None--')  
         applyFilter+= (applyFilter==''? 'Where' : 'AND') +' ' + 'Professional_Client_Services__c='+ '\''+professionalClientServicesTopics+'\'';
         
     }
     String searchquery= 'Find {'+ searchString+ '} IN ALL FIELDS RETURNING Solution(Id,SolutionNote,SolutionName,Business_Segment__c,Category__c,Products__c,Professional_Client_Services__c' + ' ' + applyFilter +' Limit '+pageSize+' Offset '+ offsetCounter+')';
     System.debug('<<<<<<<<<Query for Search is>>>>>>>>>> '+ searchquery);
     String searchquery2= 'Find {'+ searchString+ '} IN ALL FIELDS RETURNING Solution(Id,SolutionNote,SolutionName,Business_Segment__c,Category__c,Products__c,Professional_Client_Services__c' + ' ' + applyFilter + ')';
     List<List<sObject>> ListOfListOfSObjects = search.query(searchquery);
     if(ListOfListOfSObjects[0]!= null){
         solutionList= ListOfListOfSObjects[0];
         if(solutionList.size()==0){
           ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'No Record Found based on your search criterion');
             ApexPages.addMessage(myMsg);
         }
     }
     List<List<sObject>> listOfListOfSobjectwithoutLimit= search.query(searchquery2);
      if(listOfListOfSobjectwithoutLimit[0]!= null){
       listsize= listOfListOfSobjectwithoutLimit[0].size();
      }
    } else if(String.isBlank(searchString) || searchString.length()==1){
      ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Please enter a search string at least 2 characters long');
      ApexPages.addMessage(myMsg);
    }
   // return null;
    }
    public List<SelectOption> getBusinessSegments(){
      List<SelectOption> options = new List<SelectOption>();        
      options= getOptionsListforfieldType('Business_Segment__c');
      return options;
    }
    public List<SelectOption> getCategories(){
      List<SelectOption> options = new List<SelectOption>();        
      options= getOptionsListforfieldType('Category__c');
      return options;
    }
    public List<SelectOption> getProducts(){
      List<SelectOption> options = new List<SelectOption>();        
      options= getOptionsListforfieldType('Products__c');
      return options;
    }
    public List<SelectOption> getProfessionalClientsServices(){
      List<SelectOption> options = new List<SelectOption>();        
      options= getOptionsListforfieldType('Professional_Client_Services__c');
      return options;
    }
    
   public List<SelectOption> getOptionsListforfieldType(String fieldname){
     List<SelectOption> options = new List<SelectOption>();
     options.add(new SelectOption('--None--','--None--'));       
     Schema.DescribeFieldResult fieldResult =Schema.sObjectType.Solution.fields.getMap().get(fieldname).getDescribe();  
     List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();        
     for( Schema.PicklistEntry f : ple){
      options.add(new SelectOption(f.getLabel(), f.getValue()));
     }       
   return options;
   }
   public void next(){
    if (offsetCounter+pagesize< listSize){
     offsetCounter= offsetCounter+ pagesize;
     findSolution();
    }
   } 
    public void previous(){
    if(offsetCounter-pagesize>=0){
      offsetCounter= offsetCounter-pagesize;
      findSolution();
    }
    }
   
 }