wk_taa_taaqa/src/objects/TSM_Custom_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>TSM custom settings for configuration</description>
    <fields>
        <fullName>ConnectionName__c</fullName>
        <label>ConnectionName</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>TSM_Custom_Settings</label>
</CustomObject>

wk_taa_taaqa/src/objects/TSM_Shared_Product__c.object
<CustomObject>
    <label>TSM Shared Product</label>
    <nameField>
        <displayFormat>TP-{0000000000}</displayFormat>
        <label>TSM_SharedProducts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TSM Shared Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

wk_taa_taaqa/src/objects/TSM_Trigger_Control__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is to set the trigger on/off switch for TSM specific triggers.</description>
    <fields>
        <fullName>TriggerOff__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TriggerOff</label>
        <type>Checkbox</type>
    </fields>
    <label>TSM Trigger Control</label>
</CustomObject>

wk_taa_taaqa/src/classes/TSM_AccountTriggerTest.cls
/*
 * test class to perform the S2S records replication from TAA org to SFS org  
*/
/*--------------------------------------------------------------------------
 * Date       Author            Version      Description
 * -------------------------------------------------------------------------
 * 11/29/2016 Raj               1.0         Initial draft
 * ------------------------------------------------------------------------- */
@isTest
public class TSM_AccountTriggerTest {
    // data prep for preparing the custom settings data
    @testSetup static void dataPrep() {
        TSM_Custom_Settings__c config = new TSM_Custom_Settings__c();
        config.ConnectionName__c='CCH SFS';
        insert config;
        List<TSM_Trigger_Control__c> controlList = new List<TSM_Trigger_Control__c>();
        controlList.add(new TSM_Trigger_Control__c(Name='Account',TriggerOff__c=false));
        controlList.add(new TSM_Trigger_Control__c(Name='Contact',TriggerOff__c=false));
        controlList.add(new TSM_Trigger_Control__c(Name='Opportunity',TriggerOff__c=false));
        controlList.add(new TSM_Trigger_Control__c(Name='OpportunityLineItem',TriggerOff__c=false));
        controlList.add(new TSM_Trigger_Control__c(Name='TSM_Shared_Product__c',TriggerOff__c=false));
        controlList.add(new TSM_Trigger_Control__c(Name='CampaignMember',TriggerOff__c=false));            
        insert controlList;                
    }
    // test case for positive scenario
    @isTest
    static void testPositive() {
        Test.startTest();
        List<Account> accts = TSM_TestDataUtil.createAccounts(2,0,0,true);
        Test.stopTest();
        // assert the one account record is created
        //System.assertEquals(2, accts.size());
        Map<Id, Account> acctMap = new Map<Id, Account>([SELECT Id FROM Account]);
        // assert that one PNRC sharing record is created for respective account
        List<PartnerNetworkRecordConnection> shareAcctExt = [SELECT Id, LocalRecordId, Status, PartnerRecordId FROM
                                                        PartnerNetworkRecordConnection 
                                                         WHERE LocalRecordId IN :acctMap.keyset()];
        //System.assertEquals(2, shareAcctExt.size());        
    }
    // test case for negative scenario
    @isTest static void testNegative() {
        Test.startTest();
        List<Account> accts = TSM_TestDataUtil.createAccounts(2,0,0,false);
        Test.stopTest();
        // assert the one account record is created
        //System.assertEquals(2, accts.size());
        Map<Id, Account> acctMap = new Map<Id, Account>([SELECT Id FROM Account]);
        // assert that no PNRC sharing record is created for respective account
        List<PartnerNetworkRecordConnection> shareAcctExt = [SELECT Id, LocalRecordId, Status, PartnerRecordId FROM
                                                        PartnerNetworkRecordConnection 
                                                         WHERE LocalRecordId IN :acctMap.keyset()];
        //System.assertEquals(0, shareAcctExt.size());
    }
    // test case for bulk records
    @isTest static void testBulk() {
        Test.startTest();
        List<Account> accts = TSM_TestDataUtil.createAccounts(200,0,0,true);
        Test.stopTest();
        // assert the one account record is created
        //System.assertEquals(200, accts.size());
        Map<Id, Account> acctMap = new Map<Id, Account>([SELECT Id FROM Account]);
        // assert that one PNRC sharing record is created for respective account
        List<PartnerNetworkRecordConnection> shareAcctExt = [SELECT Id, LocalRecordId, Status, PartnerRecordId FROM
                                                        PartnerNetworkRecordConnection 
                                                         WHERE LocalRecordId IN :acctMap.keyset()];
       // System.assertEquals(200, shareAcctExt.size());    
    }
}